/*
 * Copyright (c) 2022 Renwei
 *
 * This is a free software; you can redistribute it and/or modify
 * it under the terms of the MIT license. See LICENSE for details.
 *
 * ############################# IMPORTANT INFORMATION ############################
 * The code of this file is automatically generated by tools(Tools/auto_code),
 * please do not modify it manually!
 * ############################# IMPORTANT INFORMATION ############################
 * ================================================================================
 */

#include "dave_base.h"
#include "dave_tools.h"
#include "base_enum.h"
#include "base_retcode.h"
#include "http_param.h"

// =====================================================================

s8 *
t_a2b_RetCode_str(RetCode enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case RetCode_begin_value:
				value_str = "'RetCode_begin_value:1'";
			break;
		case RetCode_OK:
				value_str = "'RetCode_OK:0'";
			break;
		case RetCode_Memory_full:
				value_str = "'RetCode_Memory_full:-1'";
			break;
		case RetCode_Limited_resources:
				value_str = "'RetCode_Limited_resources:-2'";
			break;
		case RetCode_Arithmetic_error:
				value_str = "'RetCode_Arithmetic_error:-3'";
			break;
		case RetCode_Unknown_error:
				value_str = "'RetCode_Unknown_error:-4'";
			break;
		case RetCode_Can_not_find_node:
				value_str = "'RetCode_Can_not_find_node:-5'";
			break;
		case RetCode_Send_failed:
				value_str = "'RetCode_Send_failed:-6'";
			break;
		case RetCode_Recv_failed:
				value_str = "'RetCode_Recv_failed:-7'";
			break;
		case RetCode_Invalid_data:
				value_str = "'RetCode_Invalid_data:-8'";
			break;
		case RetCode_Unsupported_type:
				value_str = "'RetCode_Unsupported_type:-9'";
			break;
		case RetCode_Invalid_user_name:
				value_str = "'RetCode_Invalid_user_name:-10'";
			break;
		case RetCode_Parameter_conflicts:
				value_str = "'RetCode_Parameter_conflicts:-11'";
			break;
		case RetCode_Invalid_device:
				value_str = "'RetCode_Invalid_device:-12'";
			break;
		case RetCode_Invalid_Event:
				value_str = "'RetCode_Invalid_Event:-13'";
			break;
		case RetCode_Heartbeat_timeout:
				value_str = "'RetCode_Heartbeat_timeout:-14'";
			break;
		case RetCode_Invalid_password:
				value_str = "'RetCode_Invalid_password:-15'";
			break;
		case RetCode_save_failed:
				value_str = "'RetCode_save_failed:-16'";
			break;
		case RetCode_Invalid_data_too_short:
				value_str = "'RetCode_Invalid_data_too_short:-17'";
			break;
		case RetCode_Invalid_data_too_long:
				value_str = "'RetCode_Invalid_data_too_long:-18'";
			break;
		case RetCode_Invalid_data_crc_check:
				value_str = "'RetCode_Invalid_data_crc_check:-19'";
			break;
		case RetCode_Invalid_parameter:
				value_str = "'RetCode_Invalid_parameter:-20'";
			break;
		case RetCode_Send_msg_failed:
				value_str = "'RetCode_Send_msg_failed:-21'";
			break;
		case RetCode_Resource_conflicts:
				value_str = "'RetCode_Resource_conflicts:-22'";
			break;
		case RetCode_CREDIT_LIMIT_REACHED:
				value_str = "'RetCode_CREDIT_LIMIT_REACHED:-23'";
			break;
		case RetCode_Exceeded_number:
				value_str = "'RetCode_Exceeded_number:-24'";
			break;
		case RetCode_do_not_free:
				value_str = "'RetCode_do_not_free:-25'";
			break;
		case RetCode_Request_failed:
				value_str = "'RetCode_Request_failed:-26'";
			break;
		case RetCode_can_not_find_ret_code:
				value_str = "'RetCode_can_not_find_ret_code:-27'";
			break;
		case RetCode_user_is_registered:
				value_str = "'RetCode_user_is_registered:-28'";
			break;
		case RetCode_connect_error:
				value_str = "'RetCode_connect_error:-29'";
			break;
		case RetCode_function_not_supported:
				value_str = "'RetCode_function_not_supported:-30'";
			break;
		case RetCode_msg_queue_is_full:
				value_str = "'RetCode_msg_queue_is_full:-31'";
			break;
		case RetCode_msg_can_not_resend_wakeup:
				value_str = "'RetCode_msg_can_not_resend_wakeup:-32'";
			break;
		case RetCode_msg_memory_if_full:
				value_str = "'RetCode_msg_memory_if_full:-33'";
			break;
		case RetCode_msg_competition_for_resources:
				value_str = "'RetCode_msg_competition_for_resources:-34'";
			break;
		case RetCode_wait:
				value_str = "'RetCode_wait:-35'";
			break;
		case RetCode_Invalid_state:
				value_str = "'RetCode_Invalid_state:-36'";
			break;
		case RetCode_usr_default:
				value_str = "'RetCode_usr_default:-37'";
			break;
		case RetCode_timer_out:
				value_str = "'RetCode_timer_out:-38'";
			break;
		case RetCode_invalid_type:
				value_str = "'RetCode_invalid_type:-39'";
			break;
		case RetCode_user_does_not_exist:
				value_str = "'RetCode_user_does_not_exist:-40'";
			break;
		case RetCode_version_new:
				value_str = "'RetCode_version_new:-41'";
			break;
		case RetCode_version_old:
				value_str = "'RetCode_version_old:-42'";
			break;
		case RetCode_ptr_null:
				value_str = "'RetCode_ptr_null:-43'";
			break;
		case RetCode_record_not_exist:
				value_str = "'RetCode_record_not_exist:-44'";
			break;
		case RetCode_db_store_failed:
				value_str = "'RetCode_db_store_failed:-45'";
			break;
		case RetCode_db_not_find:
				value_str = "'RetCode_db_not_find:-46'";
			break;
		case RetCode_Invalid_channel_name:
				value_str = "'RetCode_Invalid_channel_name:-47'";
			break;
		case RetCode_Invalid_db_store:
				value_str = "'RetCode_Invalid_db_store:-48'";
			break;
		case RetCode_version_mismatch:
				value_str = "'RetCode_version_mismatch:-49'";
			break;
		case RetCode_invalid_version_file:
				value_str = "'RetCode_invalid_version_file:-50'";
			break;
		case RetCode_version_identical:
				value_str = "'RetCode_version_identical:-51'";
			break;
		case RetCode_db_sql_failed:
				value_str = "'RetCode_db_sql_failed:-52'";
			break;
		case RetCode_invalid_option:
				value_str = "'RetCode_invalid_option:-53'";
			break;
		case RetCode_Invalid_domain:
				value_str = "'RetCode_Invalid_domain:-54'";
			break;
		case RetCode_Invalid_auth_key:
				value_str = "'RetCode_Invalid_auth_key:-55'";
			break;
		case RetCode_invalid_key:
				value_str = "'RetCode_invalid_key:-56'";
			break;
		case RetCode_no_account_found:
				value_str = "'RetCode_no_account_found:-57'";
			break;
		case RetCode_invalid_phone_number:
				value_str = "'RetCode_invalid_phone_number:-58'";
			break;
		case RetCode_not_match_domain:
				value_str = "'RetCode_not_match_domain:-59'";
			break;
		case RetCode_invalid_account:
				value_str = "'RetCode_invalid_account:-60'";
			break;
		case RetCode_please_help_free:
				value_str = "'RetCode_please_help_free:-61'";
			break;
		case RetCode_db_init_failed:
				value_str = "'RetCode_db_init_failed:-62'";
			break;
		case RetCode_update_fail:
				value_str = "'RetCode_update_fail:-63'";
			break;
		case RetCode_maybe_have_data:
				value_str = "'RetCode_maybe_have_data:-64'";
			break;
		case RetCode_do_not_restart:
				value_str = "'RetCode_do_not_restart:-65'";
			break;
		case RetCode_lost_auth_key:
				value_str = "'RetCode_lost_auth_key:-66'";
			break;
		case RetCode_lost_serial:
				value_str = "'RetCode_lost_serial:-67'";
			break;
		case RetCode_lost_time:
				value_str = "'RetCode_lost_time:-68'";
			break;
		case RetCode_lost_uuid:
				value_str = "'RetCode_lost_uuid:-69'";
			break;
		case RetCode_lost_user:
				value_str = "'RetCode_lost_user:-70'";
			break;
		case RetCode_can_not_find_record:
				value_str = "'RetCode_can_not_find_record:-71'";
			break;
		case RetCode_empty_data:
				value_str = "'RetCode_empty_data:-72'";
			break;
		case RetCode_Channel_closed:
				value_str = "'RetCode_Channel_closed:-73'";
			break;
		case RetCode_lost_link:
				value_str = "'RetCode_lost_link:-74'";
			break;
		case RetCode_record_not_found:
				value_str = "'RetCode_record_not_found:-75'";
			break;
		case RetCode_not_access:
				value_str = "'RetCode_not_access:-76'";
			break;
		case RetCode_can_not_find_thread:
				value_str = "'RetCode_can_not_find_thread:-77'";
			break;
		case RetCode_can_not_find_client:
				value_str = "'RetCode_can_not_find_client:-78'";
			break;
		case RetCode_user_exist:
				value_str = "'RetCode_user_exist:-79'";
			break;
		case RetCode_store_data_failed:
				value_str = "'RetCode_store_data_failed:-80'";
			break;
		case RetCode_Invalid_user_type:
				value_str = "'RetCode_Invalid_user_type:-81'";
			break;
		case RetCode_invalid_user:
				value_str = "'RetCode_invalid_user:-82'";
			break;
		case RetCode_unsupport:
				value_str = "'RetCode_unsupport:-83'";
			break;
		case RetCode_unpackage_failed:
				value_str = "'RetCode_unpackage_failed:-84'";
			break;
		case RetCode_creat_db_failed:
				value_str = "'RetCode_creat_db_failed:-85'";
			break;
		case RetCode_Invalid_channel:
				value_str = "'RetCode_Invalid_channel:-86'";
			break;
		case RetCode_heartbeat_timer_out:
				value_str = "'RetCode_heartbeat_timer_out:-87'";
			break;
		case RetCode_not_my_data:
				value_str = "'RetCode_not_my_data:-88'";
			break;
		case RetCode_Invalid_rules:
				value_str = "'RetCode_Invalid_rules:-89'";
			break;
		case RetCode_busy:
				value_str = "'RetCode_busy:-90'";
			break;
		case RetCode_data_overflow:
				value_str = "'RetCode_data_overflow:-91'";
			break;
		case RetCode_invalid_account_name:
				value_str = "'RetCode_invalid_account_name:-92'";
			break;
		case RetCode_Account_in_use:
				value_str = "'RetCode_Account_in_use:-93'";
			break;
		case RetCode_invalid_address:
				value_str = "'RetCode_invalid_address:-94'";
			break;
		case RetCode_can_not_find_rules:
				value_str = "'RetCode_can_not_find_rules:-95'";
			break;
		case RetCode_refuse_call_self:
				value_str = "'RetCode_refuse_call_self:-96'";
			break;
		case RetCode_Invalid_call:
				value_str = "'RetCode_Invalid_call:-97'";
			break;
		case RetCode_mismatch:
				value_str = "'RetCode_mismatch:-98'";
			break;
		case RetCode_Invalid_call_type:
				value_str = "'RetCode_Invalid_call_type:-99'";
			break;
		case RetCode_Invalid_billing:
				value_str = "'RetCode_Invalid_billing:-100'";
			break;
		case RetCode_invalid_magic:
				value_str = "'RetCode_invalid_magic:-101'";
			break;
		case RetCode_create_thread_failed:
				value_str = "'RetCode_create_thread_failed:-102'";
			break;
		case RetCode_script_execution_error:
				value_str = "'RetCode_script_execution_error:-103'";
			break;
		case RetCode_decode_failed:
				value_str = "'RetCode_decode_failed:-104'";
			break;
		case RetCode_encode_failed:
				value_str = "'RetCode_encode_failed:-105'";
			break;
		case RetCode_invalid_file:
				value_str = "'RetCode_invalid_file:-106'";
			break;
		case RetCode_file_open_failed:
				value_str = "'RetCode_file_open_failed:-107'";
			break;
		case RetCode_process_now:
				value_str = "'RetCode_process_now:-108'";
			break;
		case RetCode_queue_too_large:
				value_str = "'RetCode_queue_too_large:-109'";
			break;
		case RetCode_repeated_request:
				value_str = "'RetCode_repeated_request:-110'";
			break;
		case RetCode_Can_not_find_path:
				value_str = "'RetCode_Can_not_find_path:-111'";
			break;
		case RetCode_invalid_hour:
				value_str = "'RetCode_invalid_hour:-112'";
			break;
		case RetCode_invalid_day:
				value_str = "'RetCode_invalid_day:-113'";
			break;
		case RetCode_invalid_week:
				value_str = "'RetCode_invalid_week:-114'";
			break;
		case RetCode_invalid_month:
				value_str = "'RetCode_invalid_month:-115'";
			break;
		case RetCode_invalid_year:
				value_str = "'RetCode_invalid_year:-116'";
			break;
		case RetCode_invalid_date:
				value_str = "'RetCode_invalid_date:-117'";
			break;
		case RetCode_max:
				value_str = "'RetCode_max:0x1fffffffffffffff'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_SOCTYPE_str(SOCTYPE enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case TYPE_SOCK_STREAM:
				value_str = "'TYPE_SOCK_STREAM:0'";
			break;
		case TYPE_SOCK_DGRAM:
				value_str = "'TYPE_SOCK_DGRAM'";
			break;
		case TYPE_SOCK_RAW:
				value_str = "'TYPE_SOCK_RAW'";
			break;
		case TYPE_SOCK_SCTP:
				value_str = "'TYPE_SOCK_SCTP'";
			break;
		case TYPE_SOCK_max:
				value_str = "'TYPE_SOCK_max'";
			break;
		case TYPE_SOCK_MAX:
				value_str = "'TYPE_SOCK_MAX:0x1fffffff'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_NetAddrType_str(NetAddrType enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case NetAddrIPType:
				value_str = "'NetAddrIPType:0'";
			break;
		case NetAddrIPBroadcastType:
				value_str = "'NetAddrIPBroadcastType'";
			break;
		case NetAddrURLType:
				value_str = "'NetAddrURLType:0x12345678'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_FixedPortFlag_str(FixedPortFlag enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case FixedPort:
				value_str = "'FixedPort:0x01234567'";
			break;
		case NotFixedPort:
				value_str = "'NotFixedPort:0x09abcdef'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_EnableKeepAliveFlag_str(EnableKeepAliveFlag enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case KeepAlive_enable:
				value_str = "'KeepAlive_enable:0x01234567'";
			break;
		case KeepAlive_disable:
				value_str = "'KeepAlive_disable:0x09abcdef'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_EnableNetCardBindFlag_str(EnableNetCardBindFlag enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case NetCardBind_enable:
				value_str = "'NetCardBind_enable:0x01234567'";
			break;
		case NetCardBind_disable:
				value_str = "'NetCardBind_disable:0x09abcdef'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_SOCKETINFO_str(SOCKETINFO enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case SOCKETINFO_BIND:
				value_str = "'SOCKETINFO_BIND:0'";
			break;
		case SOCKETINFO_BIND_OK:
				value_str = "'SOCKETINFO_BIND_OK'";
			break;
		case SOCKETINFO_BIND_FAIL:
				value_str = "'SOCKETINFO_BIND_FAIL'";
			break;
		case SOCKETINFO_CONNECT:
				value_str = "'SOCKETINFO_CONNECT'";
			break;
		case SOCKETINFO_CONNECT_OK:
				value_str = "'SOCKETINFO_CONNECT_OK'";
			break;
		case SOCKETINFO_CONNECT_FAIL:
				value_str = "'SOCKETINFO_CONNECT_FAIL'";
			break;
		case SOCKETINFO_CONNECT_WAIT:
				value_str = "'SOCKETINFO_CONNECT_WAIT'";
			break;
		case SOCKETINFO_DISCONNECT:
				value_str = "'SOCKETINFO_DISCONNECT'";
			break;
		case SOCKETINFO_DISCONNECT_OK:
				value_str = "'SOCKETINFO_DISCONNECT_OK'";
			break;
		case SOCKETINFO_DISCONNECT_FAIL:
				value_str = "'SOCKETINFO_DISCONNECT_FAIL'";
			break;
		case SOCKETINFO_DISCONNECT_WAIT:
				value_str = "'SOCKETINFO_DISCONNECT_WAIT'";
			break;
		case SOCKETINFO_CREAT:
				value_str = "'SOCKETINFO_CREAT'";
			break;
		case SOCKETINFO_WAIT_CREAT:
				value_str = "'SOCKETINFO_WAIT_CREAT'";
			break;
		case SOCKETINFO_ACCEPT:
				value_str = "'SOCKETINFO_ACCEPT'";
			break;
		case SOCKETINFO_REV:
				value_str = "'SOCKETINFO_REV'";
			break;
		case SOCKETINFO_REV_MBUF:
				value_str = "'SOCKETINFO_REV_MBUF'";
			break;
		case SOCKETINFO_SND:
				value_str = "'SOCKETINFO_SND'";
			break;
		case SOCKETINFO_CLOSE:
				value_str = "'SOCKETINFO_CLOSE'";
			break;
		case SOCKETINFO_SILENCE:
				value_str = "'SOCKETINFO_SILENCE'";
			break;
		case SOCKETINFO_DEVICE_CONNECT:
				value_str = "'SOCKETINFO_DEVICE_CONNECT'";
			break;
		case SOCKETINFO_DEVICE_DISCONNECT:
				value_str = "'SOCKETINFO_DEVICE_DISCONNECT'";
			break;
		case SOCKETINFO_LINK_LOST:
				value_str = "'SOCKETINFO_LINK_LOST'";
			break;
		case SOCKETINFO_SEND_TIMER_OUT:
				value_str = "'SOCKETINFO_SEND_TIMER_OUT'";
			break;
		case SOCKETINFO_PORT_EXIST:
				value_str = "'SOCKETINFO_PORT_EXIST'";
			break;
		case SOCKETINFO_WRITE_THEN_CLOSE:
				value_str = "'SOCKETINFO_WRITE_THEN_CLOSE:0x7857aaeb'";
			break;
		case SOCKETINFO_SND_URG:
				value_str = "'SOCKETINFO_SND_URG'";
			break;
		case SOCKETINFO_RAW_EVENT_RECV_LENGTH:
				value_str = "'SOCKETINFO_RAW_EVENT_RECV_LENGTH'";
			break;
		case SOCKETINFO_MAX:
				value_str = "'SOCKETINFO_MAX:0x1fffffff'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_SOCEVENT_str(SOCEVENT enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case SOC_EVENT_START:
				value_str = "'SOC_EVENT_START:0'";
			break;
		case SOC_EVENT_WAIT_CREAT:
				value_str = "'SOC_EVENT_WAIT_CREAT'";
			break;
		case SOC_EVENT_CONNECT:
				value_str = "'SOC_EVENT_CONNECT'";
			break;
		case SOC_EVENT_CONNECT_FAIL:
				value_str = "'SOC_EVENT_CONNECT_FAIL'";
			break;
		case SOC_EVENT_WAIT_CONNECT:
				value_str = "'SOC_EVENT_WAIT_CONNECT'";
			break;
		case SOC_EVENT_ACCEPT:
				value_str = "'SOC_EVENT_ACCEPT'";
			break;
		case SOC_EVENT_REV:
				value_str = "'SOC_EVENT_REV'";
			break;
		case SOC_EVENT_SND:
				value_str = "'SOC_EVENT_SND'";
			break;
		case SOC_EVENT_CLOSE:
				value_str = "'SOC_EVENT_CLOSE'";
			break;
		case SOC_EVENT_SILENCE:
				value_str = "'SOC_EVENT_SILENCE'";
			break;
		case SOC_EVENT_MAX:
				value_str = "'SOC_EVENT_MAX'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_IPVER_str(IPVER enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case IPVER_IPV4:
				value_str = "'IPVER_IPV4:4'";
			break;
		case IPVER_IPV6:
				value_str = "'IPVER_IPV6:6'";
			break;
		case IPVER_MAX:
				value_str = "'IPVER_MAX:0x1fffffff'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_SOCDOMAIN_str(SOCDOMAIN enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case DM_SOC_PF_INET:
				value_str = "'DM_SOC_PF_INET:0'";
			break;
		case DM_SOC_PF_INET6:
				value_str = "'DM_SOC_PF_INET6'";
			break;
		case DM_SOC_PF_UART:
				value_str = "'DM_SOC_PF_UART'";
			break;
		case DM_SOC_PF_LOCAL_INET:
				value_str = "'DM_SOC_PF_LOCAL_INET'";
			break;
		case DM_SOC_PF_LOCAL_INET6:
				value_str = "'DM_SOC_PF_LOCAL_INET6'";
			break;
		case DM_SOC_PF_RAW:
				value_str = "'DM_SOC_PF_RAW'";
			break;
		case DM_SOC_PF_RAW_INET:
				value_str = "'DM_SOC_PF_RAW_INET'";
			break;
		case SOCDOMAIN_MAX:
				value_str = "'SOCDOMAIN_MAX:0x1fffffff'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_IPProtocol_str(IPProtocol enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case IPProtocol_ICMP:
				value_str = "'IPProtocol_ICMP:1'";
			break;
		case IPProtocol_TCP:
				value_str = "'IPProtocol_TCP:6'";
			break;
		case IPProtocol_UDP:
				value_str = "'IPProtocol_UDP:17'";
			break;
		case IPProtocol_GRE:
				value_str = "'IPProtocol_GRE:47'";
			break;
		case IPProtocol_MAX:
				value_str = "'IPProtocol_MAX'";
			break;
		case IPProtocol_max:
				value_str = "'IPProtocol_max:0x1fffffff'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_BuildingBlocksOpt_str(BuildingBlocksOpt enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case BuildingBlocksOpt_none:
				value_str = "'BuildingBlocksOpt_none'";
			break;
		case BuildingBlocksOpt_inq:
				value_str = "'BuildingBlocksOpt_inq'";
			break;
		case BuildingBlocksOpt_mount:
				value_str = "'BuildingBlocksOpt_mount'";
			break;
		case BuildingBlocksOpt_decoupling:
				value_str = "'BuildingBlocksOpt_decoupling'";
			break;
		case BuildingBlocksOpt_State_exchange:
				value_str = "'BuildingBlocksOpt_State_exchange'";
			break;
		case BuildingBlocksOpt_valve:
				value_str = "'BuildingBlocksOpt_valve'";
			break;
		case BuildingBlocksOpt_max:
				value_str = "'BuildingBlocksOpt_max'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_HTTPListenType_str(HTTPListenType enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case ListenHttp:
				value_str = "'ListenHttp'";
			break;
		case ListenHttps:
				value_str = "'ListenHttps'";
			break;
		case ListenWeb:
				value_str = "'ListenWeb'";
			break;
		case ListenMax:
				value_str = "'ListenMax'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_HTTPMathcRule_str(HTTPMathcRule enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case LocationMatch_Accurate:
				value_str = "'LocationMatch_Accurate:0'";
			break;
		case LocationMatch_Prefix:
				value_str = "'LocationMatch_Prefix'";
			break;
		case LocationMatch_CaseRegular:
				value_str = "'LocationMatch_CaseRegular'";
			break;
		case LocationMatch_Regular:
				value_str = "'LocationMatch_Regular'";
			break;
		case LocationMatch_CaseRegularExcl:
				value_str = "'LocationMatch_CaseRegularExcl'";
			break;
		case LocationMatch_RegularExcl:
				value_str = "'LocationMatch_RegularExcl'";
			break;
		case LocationMatch_Wildcard:
				value_str = "'LocationMatch_Wildcard'";
			break;
		case LocationMatch_Max:
				value_str = "'LocationMatch_Max'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_HttpMethod_str(HttpMethod enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case HttpMethod_post:
				value_str = "'HttpMethod_post'";
			break;
		case HttpMethod_get:
				value_str = "'HttpMethod_get'";
			break;
		case HttpMethod_put:
				value_str = "'HttpMethod_put'";
			break;
		case HttpMethod_options:
				value_str = "'HttpMethod_options'";
			break;
		case HttpMethod_delete:
				value_str = "'HttpMethod_delete'";
			break;
		case HttpMethod_max:
				value_str = "'HttpMethod_max'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_HttpContentType_str(HttpContentType enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case HttpContentType_json:
				value_str = "'HttpContentType_json'";
			break;
		case HttpContentType_text:
				value_str = "'HttpContentType_text'";
			break;
		case HttpContentType_xml:
				value_str = "'HttpContentType_xml'";
			break;
		case HttpContentType_xwww:
				value_str = "'HttpContentType_xwww'";
			break;
		case HttpContentType_max:
				value_str = "'HttpContentType_max'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}

s8 *
t_a2b_RPCMSG_str(RPCMSG enum_value)
{
	s8 *value_str = NULL;

	switch(enum_value)
	{
		case MSGID_RESERVED:
				value_str = "'MSGID_RESERVED:0x0000000000000000'";
			break;
		case MSGID_TEST:
				value_str = "'MSGID_TEST:1'";
			break;
		case MSGID_TIMER:
				value_str = "'MSGID_TIMER:2'";
			break;
		case MSGID_WAKEUP:
				value_str = "'MSGID_WAKEUP:3'";
			break;
		case MSGID_RUN_FUNCTION:
				value_str = "'MSGID_RUN_FUNCTION:4'";
			break;
		case MSGID_DEBUG_REQ:
				value_str = "'MSGID_DEBUG_REQ:5'";
			break;
		case MSGID_DEBUG_RSP:
				value_str = "'MSGID_DEBUG_RSP:6'";
			break;
		case MSGID_RESTART_REQ:
				value_str = "'MSGID_RESTART_REQ:7'";
			break;
		case MSGID_RESTART_RSP:
				value_str = "'MSGID_RESTART_RSP:8'";
			break;
		case MSGID_POWER_OFF:
				value_str = "'MSGID_POWER_OFF:9'";
			break;
		case MSGID_REMOTE_THREAD_READY:
				value_str = "'MSGID_REMOTE_THREAD_READY:10'";
			break;
		case MSGID_REMOTE_THREAD_REMOVE:
				value_str = "'MSGID_REMOTE_THREAD_REMOVE:11'";
			break;
		case MSGID_TRACE_SWITCH:
				value_str = "'MSGID_TRACE_SWITCH:12'";
			break;
		case MSGID_PROCESS_MSG_TIMER_OUT:
				value_str = "'MSGID_PROCESS_MSG_TIMER_OUT:13'";
			break;
		case MSGID_TEMPORARILY_DEFINE_MESSAGE:
				value_str = "'MSGID_TEMPORARILY_DEFINE_MESSAGE:14'";
			break;
		case MSGID_CALL_FUNCTION:
				value_str = "'MSGID_CALL_FUNCTION:15'";
			break;
		case MSGID_SYSTEM_MOUNT:
				value_str = "'MSGID_SYSTEM_MOUNT:16'";
			break;
		case MSGID_SYSTEM_DECOUPLING:
				value_str = "'MSGID_SYSTEM_DECOUPLING:17'";
			break;
		case MSGID_MEMORY_WARNING:
				value_str = "'MSGID_MEMORY_WARNING:18'";
			break;
		case MSGID_ECHO:
				value_str = "'MSGID_ECHO:19'";
			break;
		case MSGID_INTERNAL_EVENTS:
				value_str = "'MSGID_INTERNAL_EVENTS:20'";
			break;
		case MSGID_THREAD_BUSY:
				value_str = "'MSGID_THREAD_BUSY:21'";
			break;
		case MSGID_THREAD_IDLE:
				value_str = "'MSGID_THREAD_IDLE:22'";
			break;
		case MSGID_CLIENT_BUSY:
				value_str = "'MSGID_CLIENT_BUSY:23'";
			break;
		case MSGID_CLIENT_IDLE:
				value_str = "'MSGID_CLIENT_IDLE:24'";
			break;
		case MSGID_REMOTE_THREAD_ID_READY:
				value_str = "'MSGID_REMOTE_THREAD_ID_READY:25'";
			break;
		case MSGID_REMOTE_THREAD_ID_REMOVE:
				value_str = "'MSGID_REMOTE_THREAD_ID_REMOVE:26'";
			break;
		case MSGID_LOCAL_THREAD_READY:
				value_str = "'MSGID_LOCAL_THREAD_READY:27'";
			break;
		case MSGID_LOCAL_THREAD_REMOVE:
				value_str = "'MSGID_LOCAL_THREAD_REMOVE:28'";
			break;
		case MSGID_RPC_DEBUG_MSG:
				value_str = "'MSGID_RPC_DEBUG_MSG:29'";
			break;
		case MSGID_CFG_UPDATE:
				value_str = "'MSGID_CFG_UPDATE:30'";
			break;
		case MSGID_BLOCKS_REQ:
				value_str = "'MSGID_BLOCKS_REQ:31'";
			break;
		case MSGID_BLOCKS_RSP:
				value_str = "'MSGID_BLOCKS_RSP:32'";
			break;
		case MSGID_OS_NOTIFY:
				value_str = "'MSGID_OS_NOTIFY:33'";
			break;
		case SOCKET_BIND_REQ:
				value_str = "'SOCKET_BIND_REQ:1000'";
			break;
		case SOCKET_BIND_RSP:
				value_str = "'SOCKET_BIND_RSP:1001'";
			break;
		case SOCKET_CONNECT_REQ:
				value_str = "'SOCKET_CONNECT_REQ:1002'";
			break;
		case SOCKET_CONNECT_RSP:
				value_str = "'SOCKET_CONNECT_RSP:1003'";
			break;
		case SOCKET_DISCONNECT_REQ:
				value_str = "'SOCKET_DISCONNECT_REQ:1004'";
			break;
		case SOCKET_DISCONNECT_RSP:
				value_str = "'SOCKET_DISCONNECT_RSP:1005'";
			break;
		case SOCKET_PLUGIN:
				value_str = "'SOCKET_PLUGIN:1006'";
			break;
		case SOCKET_PLUGOUT:
				value_str = "'SOCKET_PLUGOUT:1007'";
			break;
		case SOCKET_READ:
				value_str = "'SOCKET_READ:1008'";
			break;
		case SOCKET_WRITE:
				value_str = "'SOCKET_WRITE:1009'";
			break;
		case SOCKET_NOTIFY:
				value_str = "'SOCKET_NOTIFY:1010'";
			break;
		case SOCKET_RAW_EVENT:
				value_str = "'SOCKET_RAW_EVENT:1011'";
			break;
		case HTTPMSG_LISTEN_REQ:
				value_str = "'HTTPMSG_LISTEN_REQ:11002'";
			break;
		case HTTPMSG_LISTEN_RSP:
				value_str = "'HTTPMSG_LISTEN_RSP:11003'";
			break;
		case HTTPMSG_CLOSE_REQ:
				value_str = "'HTTPMSG_CLOSE_REQ:11004'";
			break;
		case HTTPMSG_CLOSE_RSP:
				value_str = "'HTTPMSG_CLOSE_RSP:11005'";
			break;
		case HTTPMSG_RECV_REQ:
				value_str = "'HTTPMSG_RECV_REQ:11006'";
			break;
		case HTTPMSG_RECV_RSP:
				value_str = "'HTTPMSG_RECV_RSP:11007'";
			break;
		case MSGID_INVALID:
				value_str = "'MSGID_INVALID:0xffffffffffffffff'";
			break;
		default:
				value_str = "'NULL'";
			break;
	}

	return value_str;
}
