/*
 * Copyright (c) 2022 Renwei
 *
 * This is a free software; you can redistribute it and/or modify
 * it under the terms of the MIT license. See LICENSE for details.
 *
 * ############################# IMPORTANT INFORMATION ############################
 * The code of this file is automatically generated by tools(Tools/rpc),
 * please do not modify it manually!
 * ############################# IMPORTANT INFORMATION ############################
 * ================================================================================
 */

#ifndef _T_RPC_UNIONDATA_H__
#define _T_RPC_UNIONDATA_H__
#include "dave_base.h"

void * t_rpc_ver3_zip_SocNetInfoAddr(SocNetInfoAddr *zip_data);
dave_bool t_rpc_ver3_unzip_SocNetInfoAddr(SocNetInfoAddr *unzip_data, void *pArrayBson);

#endif

