package auto
/*
 * Copyright (c) 2023 Renwei
 *
 * This is a free software; you can redistribute it and/or modify
 * it under the terms of the MIT license. See LICENSE for details.
 *
 * ############################# IMPORTANT INFORMATION ############################
 * The code of this file is automatically generated by tools(Tools/auto_code),
 * please do not modify it manually!
 * ############################# IMPORTANT INFORMATION ############################
 * ================================================================================
 */

import (
   "fmt"
)

func T_auto_AIPlaceType_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case AIPlaceType_accounting: value_str = "'AIPlaceType_accounting'"
		case AIPlaceType_airport: value_str = "'AIPlaceType_airport'"
		case AIPlaceType_amusement_park: value_str = "'AIPlaceType_amusement_park'"
		case AIPlaceType_aquarium: value_str = "'AIPlaceType_aquarium'"
		case AIPlaceType_art_gallery: value_str = "'AIPlaceType_art_gallery'"
		case AIPlaceType_atm: value_str = "'AIPlaceType_atm'"
		case AIPlaceType_bakery: value_str = "'AIPlaceType_bakery'"
		case AIPlaceType_bank: value_str = "'AIPlaceType_bank'"
		case AIPlaceType_bar: value_str = "'AIPlaceType_bar'"
		case AIPlaceType_beauty_salon: value_str = "'AIPlaceType_beauty_salon'"
		case AIPlaceType_bicycle_store: value_str = "'AIPlaceType_bicycle_store'"
		case AIPlaceType_book_store: value_str = "'AIPlaceType_book_store'"
		case AIPlaceType_bowling_alley: value_str = "'AIPlaceType_bowling_alley'"
		case AIPlaceType_bus_station: value_str = "'AIPlaceType_bus_station'"
		case AIPlaceType_cafe: value_str = "'AIPlaceType_cafe'"
		case AIPlaceType_campground: value_str = "'AIPlaceType_campground'"
		case AIPlaceType_car_dealer: value_str = "'AIPlaceType_car_dealer'"
		case AIPlaceType_car_rental: value_str = "'AIPlaceType_car_rental'"
		case AIPlaceType_car_repair: value_str = "'AIPlaceType_car_repair'"
		case AIPlaceType_car_wash: value_str = "'AIPlaceType_car_wash'"
		case AIPlaceType_casino: value_str = "'AIPlaceType_casino'"
		case AIPlaceType_cemetery: value_str = "'AIPlaceType_cemetery'"
		case AIPlaceType_church: value_str = "'AIPlaceType_church'"
		case AIPlaceType_city_hall: value_str = "'AIPlaceType_city_hall'"
		case AIPlaceType_clothing_store: value_str = "'AIPlaceType_clothing_store'"
		case AIPlaceType_convenience_store: value_str = "'AIPlaceType_convenience_store'"
		case AIPlaceType_courthouse: value_str = "'AIPlaceType_courthouse'"
		case AIPlaceType_dentist: value_str = "'AIPlaceType_dentist'"
		case AIPlaceType_department_store: value_str = "'AIPlaceType_department_store'"
		case AIPlaceType_doctor: value_str = "'AIPlaceType_doctor'"
		case AIPlaceType_electrician: value_str = "'AIPlaceType_electrician'"
		case AIPlaceType_electronics_store: value_str = "'AIPlaceType_electronics_store'"
		case AIPlaceType_embassy: value_str = "'AIPlaceType_embassy'"
		case AIPlaceType_fire_station: value_str = "'AIPlaceType_fire_station'"
		case AIPlaceType_florist: value_str = "'AIPlaceType_florist'"
		case AIPlaceType_funeral_home: value_str = "'AIPlaceType_funeral_home'"
		case AIPlaceType_furniture_store: value_str = "'AIPlaceType_furniture_store'"
		case AIPlaceType_gas_station: value_str = "'AIPlaceType_gas_station'"
		case AIPlaceType_gym: value_str = "'AIPlaceType_gym'"
		case AIPlaceType_hair_care: value_str = "'AIPlaceType_hair_care'"
		case AIPlaceType_hardware_store: value_str = "'AIPlaceType_hardware_store'"
		case AIPlaceType_hindu_temple: value_str = "'AIPlaceType_hindu_temple'"
		case AIPlaceType_home_goods_store: value_str = "'AIPlaceType_home_goods_store'"
		case AIPlaceType_hospital: value_str = "'AIPlaceType_hospital'"
		case AIPlaceType_insurance_agency: value_str = "'AIPlaceType_insurance_agency'"
		case AIPlaceType_jewelry_store: value_str = "'AIPlaceType_jewelry_store'"
		case AIPlaceType_laundry: value_str = "'AIPlaceType_laundry'"
		case AIPlaceType_lawyer: value_str = "'AIPlaceType_lawyer'"
		case AIPlaceType_library: value_str = "'AIPlaceType_library'"
		case AIPlaceType_liquor_store: value_str = "'AIPlaceType_liquor_store'"
		case AIPlaceType_local_government_office: value_str = "'AIPlaceType_local_government_office'"
		case AIPlaceType_locksmith: value_str = "'AIPlaceType_locksmith'"
		case AIPlaceType_lodging: value_str = "'AIPlaceType_lodging'"
		case AIPlaceType_meal_delivery: value_str = "'AIPlaceType_meal_delivery'"
		case AIPlaceType_meal_takeaway: value_str = "'AIPlaceType_meal_takeaway'"
		case AIPlaceType_mosque: value_str = "'AIPlaceType_mosque'"
		case AIPlaceType_movie_rental: value_str = "'AIPlaceType_movie_rental'"
		case AIPlaceType_movie_theater: value_str = "'AIPlaceType_movie_theater'"
		case AIPlaceType_moving_company: value_str = "'AIPlaceType_moving_company'"
		case AIPlaceType_museum: value_str = "'AIPlaceType_museum'"
		case AIPlaceType_night_club: value_str = "'AIPlaceType_night_club'"
		case AIPlaceType_painter: value_str = "'AIPlaceType_painter'"
		case AIPlaceType_park: value_str = "'AIPlaceType_park'"
		case AIPlaceType_parking: value_str = "'AIPlaceType_parking'"
		case AIPlaceType_pet_store: value_str = "'AIPlaceType_pet_store'"
		case AIPlaceType_pharmacy: value_str = "'AIPlaceType_pharmacy'"
		case AIPlaceType_physiotherapist: value_str = "'AIPlaceType_physiotherapist'"
		case AIPlaceType_plumber: value_str = "'AIPlaceType_plumber'"
		case AIPlaceType_police: value_str = "'AIPlaceType_police'"
		case AIPlaceType_post_office: value_str = "'AIPlaceType_post_office'"
		case AIPlaceType_real_estate_agency: value_str = "'AIPlaceType_real_estate_agency'"
		case AIPlaceType_restaurant: value_str = "'AIPlaceType_restaurant'"
		case AIPlaceType_roofing_contractor: value_str = "'AIPlaceType_roofing_contractor'"
		case AIPlaceType_rv_park: value_str = "'AIPlaceType_rv_park'"
		case AIPlaceType_school: value_str = "'AIPlaceType_school'"
		case AIPlaceType_shoe_store: value_str = "'AIPlaceType_shoe_store'"
		case AIPlaceType_shopping_mall: value_str = "'AIPlaceType_shopping_mall'"
		case AIPlaceType_spa: value_str = "'AIPlaceType_spa'"
		case AIPlaceType_stadium: value_str = "'AIPlaceType_stadium'"
		case AIPlaceType_storage: value_str = "'AIPlaceType_storage'"
		case AIPlaceType_store: value_str = "'AIPlaceType_store'"
		case AIPlaceType_subway_station: value_str = "'AIPlaceType_subway_station'"
		case AIPlaceType_synagogue: value_str = "'AIPlaceType_synagogue'"
		case AIPlaceType_taxi_stand: value_str = "'AIPlaceType_taxi_stand'"
		case AIPlaceType_train_station: value_str = "'AIPlaceType_train_station'"
		case AIPlaceType_transit_station: value_str = "'AIPlaceType_transit_station'"
		case AIPlaceType_travel_agency: value_str = "'AIPlaceType_travel_agency'"
		case AIPlaceType_university: value_str = "'AIPlaceType_university'"
		case AIPlaceType_veterinary_care: value_str = "'AIPlaceType_veterinary_care'"
		case AIPlaceType_zoo: value_str = "'AIPlaceType_zoo'"
		case AIPlaceType_max: value_str = "'AIPlaceType_max-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_BDataLogLevel_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case BDataLogLevel_normal: value_str = "'BDataLogLevel_normal-0'"
		case BDataLogLevel_report: value_str = "'BDataLogLevel_report'"
		case BDataLogLevel_max: value_str = "'BDataLogLevel_max-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_CVSearchOpt_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case CVSearchOpt_0: value_str = "'CVSearchOpt_0'"
		case CVSearchOpt_1: value_str = "'CVSearchOpt_1'"
		case CVSearchOpt_2: value_str = "'CVSearchOpt_2'"
		case CVSearchOpt_max: value_str = "'CVSearchOpt_max'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_EchoType_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case EchoType_start: value_str = "'EchoType_start'"
		case EchoType_stop: value_str = "'EchoType_stop'"
		case EchoType_single: value_str = "'EchoType_single'"
		case EchoType_random: value_str = "'EchoType_random'"
		case EchoType_max: value_str = "'EchoType_max-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_EnableKeepAliveFlag_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case KeepAlive_enable: value_str = "'KeepAlive_enable-0x01234567'"
		case KeepAlive_disable: value_str = "'KeepAlive_disable-0x09abcdef'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_EnableNetCardBindFlag_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case NetCardBind_enable: value_str = "'NetCardBind_enable-0x01234567'"
		case NetCardBind_disable: value_str = "'NetCardBind_disable-0x09abcdef'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_ErrCode_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case ERRCODE_OK: value_str = "'ERRCODE_OK-0'"
		case ERRCODE_Memory_full: value_str = "'ERRCODE_Memory_full--1'"
		case ERRCODE_Limited_resources: value_str = "'ERRCODE_Limited_resources--2'"
		case ERRCODE_Arithmetic_error: value_str = "'ERRCODE_Arithmetic_error--3'"
		case ERRCODE_Unknown_error: value_str = "'ERRCODE_Unknown_error--4'"
		case ERRCODE_Can_not_find_node: value_str = "'ERRCODE_Can_not_find_node--5'"
		case ERRCODE_Send_failed: value_str = "'ERRCODE_Send_failed--6'"
		case ERRCODE_Recv_failed: value_str = "'ERRCODE_Recv_failed--7'"
		case ERRCODE_Invalid_data: value_str = "'ERRCODE_Invalid_data--8'"
		case ERRCODE_Unsupported_type: value_str = "'ERRCODE_Unsupported_type--9'"
		case ERRCODE_Invalid_user_name: value_str = "'ERRCODE_Invalid_user_name--10'"
		case ERRCODE_Parameter_conflicts: value_str = "'ERRCODE_Parameter_conflicts--11'"
		case ERRCODE_Invalid_device: value_str = "'ERRCODE_Invalid_device--12'"
		case ERRCODE_Invalid_Event: value_str = "'ERRCODE_Invalid_Event--13'"
		case ERRCODE_Heartbeat_timeout: value_str = "'ERRCODE_Heartbeat_timeout--14'"
		case ERRCODE_Invalid_password: value_str = "'ERRCODE_Invalid_password--15'"
		case ERRCODE_save_failed: value_str = "'ERRCODE_save_failed--16'"
		case ERRCODE_Invalid_data_too_short: value_str = "'ERRCODE_Invalid_data_too_short--17'"
		case ERRCODE_Invalid_data_too_long: value_str = "'ERRCODE_Invalid_data_too_long--18'"
		case ERRCODE_Invalid_data_crc_check: value_str = "'ERRCODE_Invalid_data_crc_check--19'"
		case ERRCODE_Invalid_parameter: value_str = "'ERRCODE_Invalid_parameter--20'"
		case ERRCODE_Send_msg_failed: value_str = "'ERRCODE_Send_msg_failed--21'"
		case ERRCODE_Resource_conflicts: value_str = "'ERRCODE_Resource_conflicts--22'"
		case ERRCODE_CREDIT_LIMIT_REACHED: value_str = "'ERRCODE_CREDIT_LIMIT_REACHED--23'"
		case ERRCODE_Exceeded_number: value_str = "'ERRCODE_Exceeded_number--24'"
		case ERRCODE_do_not_free: value_str = "'ERRCODE_do_not_free--25'"
		case ERRCODE_Request_failed: value_str = "'ERRCODE_Request_failed--26'"
		case ERRCODE_can_not_find_ret_code: value_str = "'ERRCODE_can_not_find_ret_code--27'"
		case ERRCODE_user_is_registered: value_str = "'ERRCODE_user_is_registered--28'"
		case ERRCODE_connect_error: value_str = "'ERRCODE_connect_error--29'"
		case ERRCODE_function_not_supported: value_str = "'ERRCODE_function_not_supported--30'"
		case ERRCODE_msg_queue_is_full: value_str = "'ERRCODE_msg_queue_is_full--31'"
		case ERRCODE_msg_can_not_resend_wakeup: value_str = "'ERRCODE_msg_can_not_resend_wakeup--32'"
		case ERRCODE_msg_memory_if_full: value_str = "'ERRCODE_msg_memory_if_full--33'"
		case ERRCODE_msg_competition_for_resources: value_str = "'ERRCODE_msg_competition_for_resources--34'"
		case ERRCODE_wait: value_str = "'ERRCODE_wait--35'"
		case ERRCODE_Invalid_state: value_str = "'ERRCODE_Invalid_state--36'"
		case ERRCODE_usr_default: value_str = "'ERRCODE_usr_default--37'"
		case ERRCODE_timer_out: value_str = "'ERRCODE_timer_out--38'"
		case ERRCODE_invalid_type: value_str = "'ERRCODE_invalid_type--39'"
		case ERRCODE_user_does_not_exist: value_str = "'ERRCODE_user_does_not_exist--40'"
		case ERRCODE_version_new: value_str = "'ERRCODE_version_new--41'"
		case ERRCODE_version_old: value_str = "'ERRCODE_version_old--42'"
		case ERRCODE_ptr_null: value_str = "'ERRCODE_ptr_null--43'"
		case ERRCODE_record_not_exist: value_str = "'ERRCODE_record_not_exist--44'"
		case ERRCODE_db_store_failed: value_str = "'ERRCODE_db_store_failed--45'"
		case ERRCODE_db_not_find: value_str = "'ERRCODE_db_not_find--46'"
		case ERRCODE_Invalid_channel_name: value_str = "'ERRCODE_Invalid_channel_name--47'"
		case ERRCODE_Invalid_db_store: value_str = "'ERRCODE_Invalid_db_store--48'"
		case ERRCODE_version_mismatch: value_str = "'ERRCODE_version_mismatch--49'"
		case ERRCODE_invalid_version_file: value_str = "'ERRCODE_invalid_version_file--50'"
		case ERRCODE_version_identical: value_str = "'ERRCODE_version_identical--51'"
		case ERRCODE_db_sql_failed: value_str = "'ERRCODE_db_sql_failed--52'"
		case ERRCODE_invalid_option: value_str = "'ERRCODE_invalid_option--53'"
		case ERRCODE_Invalid_domain: value_str = "'ERRCODE_Invalid_domain--54'"
		case ERRCODE_Invalid_auth_key: value_str = "'ERRCODE_Invalid_auth_key--55'"
		case ERRCODE_invalid_key: value_str = "'ERRCODE_invalid_key--56'"
		case ERRCODE_no_account_found: value_str = "'ERRCODE_no_account_found--57'"
		case ERRCODE_invalid_phone_number: value_str = "'ERRCODE_invalid_phone_number--58'"
		case ERRCODE_not_match_domain: value_str = "'ERRCODE_not_match_domain--59'"
		case ERRCODE_invalid_account: value_str = "'ERRCODE_invalid_account--60'"
		case ERRCODE_please_help_free: value_str = "'ERRCODE_please_help_free--61'"
		case ERRCODE_db_init_failed: value_str = "'ERRCODE_db_init_failed--62'"
		case ERRCODE_update_fail: value_str = "'ERRCODE_update_fail--63'"
		case ERRCODE_maybe_have_data: value_str = "'ERRCODE_maybe_have_data--64'"
		case ERRCODE_do_not_restart: value_str = "'ERRCODE_do_not_restart--65'"
		case ERRCODE_lost_auth_key: value_str = "'ERRCODE_lost_auth_key--66'"
		case ERRCODE_lost_serial: value_str = "'ERRCODE_lost_serial--67'"
		case ERRCODE_lost_time: value_str = "'ERRCODE_lost_time--68'"
		case ERRCODE_lost_uuid: value_str = "'ERRCODE_lost_uuid--69'"
		case ERRCODE_lost_user: value_str = "'ERRCODE_lost_user--70'"
		case ERRCODE_can_not_find_record: value_str = "'ERRCODE_can_not_find_record--71'"
		case ERRCODE_lost_dial_number: value_str = "'ERRCODE_lost_dial_number--72'"
		case ERRCODE_call_prohibition: value_str = "'ERRCODE_call_prohibition--73'"
		case ERRCODE_lost_link: value_str = "'ERRCODE_lost_link--74'"
		case ERRCODE_record_not_found: value_str = "'ERRCODE_record_not_found--75'"
		case ERRCODE_ims_account_incorrect: value_str = "'ERRCODE_ims_account_incorrect--76'"
		case ERRCODE_invalid_dial_number: value_str = "'ERRCODE_invalid_dial_number--77'"
		case ERRCODE_Invalid_balance: value_str = "'ERRCODE_Invalid_balance--78'"
		case ERRCODE_user_exist: value_str = "'ERRCODE_user_exist--79'"
		case ERRCODE_store_data_failed: value_str = "'ERRCODE_store_data_failed--80'"
		case ERRCODE_Invalid_user_type: value_str = "'ERRCODE_Invalid_user_type--81'"
		case ERRCODE_invalid_user: value_str = "'ERRCODE_invalid_user--82'"
		case ERRCODE_unsupport: value_str = "'ERRCODE_unsupport--83'"
		case ERRCODE_unpackage_failed: value_str = "'ERRCODE_unpackage_failed--84'"
		case ERRCODE_creat_db_failed: value_str = "'ERRCODE_creat_db_failed--85'"
		case ERRCODE_Invalid_channel: value_str = "'ERRCODE_Invalid_channel--86'"
		case ERRCODE_heartbeat_timer_out: value_str = "'ERRCODE_heartbeat_timer_out--87'"
		case ERRCODE_Invalid_package: value_str = "'ERRCODE_Invalid_package--88'"
		case ERRCODE_Invalid_rules: value_str = "'ERRCODE_Invalid_rules--89'"
		case ERRCODE_busy: value_str = "'ERRCODE_busy--90'"
		case ERRCODE_data_overflow: value_str = "'ERRCODE_data_overflow--91'"
		case ERRCODE_invalid_account_name: value_str = "'ERRCODE_invalid_account_name--92'"
		case ERRCODE_Account_in_use: value_str = "'ERRCODE_Account_in_use--93'"
		case ERRCODE_invalid_address: value_str = "'ERRCODE_invalid_address--94'"
		case ERRCODE_can_not_find_rules: value_str = "'ERRCODE_can_not_find_rules--95'"
		case ERRCODE_refuse_call_self: value_str = "'ERRCODE_refuse_call_self--96'"
		case ERRCODE_Invalid_call: value_str = "'ERRCODE_Invalid_call--97'"
		case ERRCODE_mismatch: value_str = "'ERRCODE_mismatch--98'"
		case ERRCODE_Invalid_call_type: value_str = "'ERRCODE_Invalid_call_type--99'"
		case ERRCODE_Invalid_billing: value_str = "'ERRCODE_Invalid_billing--100'"
		case ERRCODE_invalid_magic: value_str = "'ERRCODE_invalid_magic--101'"
		case ERRCODE_create_thread_failed: value_str = "'ERRCODE_create_thread_failed--102'"
		case ERRCODE_execute_sql_failed: value_str = "'ERRCODE_execute_sql_failed--103'"
		case ERRCODE_decode_failed: value_str = "'ERRCODE_decode_failed--104'"
		case ERRCODE_encode_failed: value_str = "'ERRCODE_encode_failed--105'"
		case ERRCODE_invalid_file: value_str = "'ERRCODE_invalid_file--106'"
		case ERRCODE_file_open_failed: value_str = "'ERRCODE_file_open_failed--107'"
		case ERRCODE_process_now: value_str = "'ERRCODE_process_now--108'"
		case ERRCODE_queue_too_large: value_str = "'ERRCODE_queue_too_large--109'"
		case ERRCODE_add_user_name_failed: value_str = "'ERRCODE_add_user_name_failed--110'"
		case ERRCODE_call_time_limited: value_str = "'ERRCODE_call_time_limited--111'"
		case ERRCODE_invalid_hour: value_str = "'ERRCODE_invalid_hour--112'"
		case ERRCODE_invalid_day: value_str = "'ERRCODE_invalid_day--113'"
		case ERRCODE_invalid_week: value_str = "'ERRCODE_invalid_week--114'"
		case ERRCODE_invalid_month: value_str = "'ERRCODE_invalid_month--115'"
		case ERRCODE_invalid_year: value_str = "'ERRCODE_invalid_year--116'"
		case ERRCODE_invalid_unit: value_str = "'ERRCODE_invalid_unit--117'"
		case ERRCODE_invalid_rules_number: value_str = "'ERRCODE_invalid_rules_number--118'"
		case ERRCODE_invalid_package_private: value_str = "'ERRCODE_invalid_package_private--119'"
		case ERRCODE_rules_id_mismatch: value_str = "'ERRCODE_rules_id_mismatch--120'"
		case ERRCODE_channel_not_exist: value_str = "'ERRCODE_channel_not_exist--121'"
		case ERRCODE_invalid_donation_account: value_str = "'ERRCODE_invalid_donation_account--122'"
		case ERRCODE_channel_exist: value_str = "'ERRCODE_channel_exist--123'"
		case ERRCODE_invalid_date: value_str = "'ERRCODE_invalid_date--124'"
		case ERRCODE_not_my_data: value_str = "'ERRCODE_not_my_data--125'"
		case ERRCODE_only_share_user_pwd_can_modify: value_str = "'ERRCODE_only_share_user_pwd_can_modify--126'"
		case ERRCODE_can_not_find_thread: value_str = "'ERRCODE_can_not_find_thread--127'"
		case ERRCODE_lost_register_e164_number: value_str = "'ERRCODE_lost_register_e164_number--128'"
		case ERRCODE_lost_modify_impu_flag: value_str = "'ERRCODE_lost_modify_impu_flag--129'"
		case ERRCODE_lost_country_code_of_e164_number: value_str = "'ERRCODE_lost_country_code_of_e164_number--130'"
		case ERRCODE_lost_sip_password: value_str = "'ERRCODE_lost_sip_password--131'"
		case ERRCODE_invalid_modify_impu_flag: value_str = "'ERRCODE_invalid_modify_impu_flag--132'"
		case ERRCODE_invalid_country_code_of_e164_number: value_str = "'ERRCODE_invalid_country_code_of_e164_number--133'"
		case ERRCODE_invalid_register_e164_number: value_str = "'ERRCODE_invalid_register_e164_number--134'"
		case ERRCODE_modify_impu_failed: value_str = "'ERRCODE_modify_impu_failed--135'"
		case ERRCODE_impu_not_existed: value_str = "'ERRCODE_impu_not_existed--136'"
		case ERRCODE_script_execution_error: value_str = "'ERRCODE_script_execution_error--137'"
		case ERRCODE_invalid_share_ram: value_str = "'ERRCODE_invalid_share_ram--138'"
		case ERRCODE_Duplicate_MSISDN: value_str = "'ERRCODE_Duplicate_MSISDN--139'"
		case ERRCODE_Duplicate_IMSI: value_str = "'ERRCODE_Duplicate_IMSI--140'"
		case ERRCODE_Duplicate_VOIP_MSISDN: value_str = "'ERRCODE_Duplicate_VOIP_MSISDN--141'"
		case ERRCODE_Not_found: value_str = "'ERRCODE_Not_found--142'"
		case ERRCODE_Boot_in_the_territory: value_str = "'ERRCODE_Boot_in_the_territory--143'"
		case ERRCODE_Other_errors: value_str = "'ERRCODE_Other_errors--144'"
		case ERRCODE_lost_result_code: value_str = "'ERRCODE_lost_result_code--145'"
		case ERRCODE_invalid_imsi: value_str = "'ERRCODE_invalid_imsi--146'"
		case ERRCODE_invalid_msisdn: value_str = "'ERRCODE_invalid_msisdn--147'"
		case ERRCODE_invalid_voip_msisdn: value_str = "'ERRCODE_invalid_voip_msisdn--148'"
		case ERRCODE_processing_is_complete: value_str = "'ERRCODE_processing_is_complete--149'"
		case ERRCODE_secondary_number_ass_repeated: value_str = "'ERRCODE_secondary_number_ass_repeated--150'"
		case ERRCODE_secondary_number_not_available: value_str = "'ERRCODE_secondary_number_not_available--151'"
		case ERRCODE_secondary_number_ret_failed: value_str = "'ERRCODE_secondary_number_ret_failed--152'"
		case ERRCODE_secondary_number_inquiry_failed: value_str = "'ERRCODE_secondary_number_inquiry_failed--153'"
		case ERRCODE_lost_secondary_number: value_str = "'ERRCODE_lost_secondary_number--154'"
		case ERRCODE_invalid_e164_number_type: value_str = "'ERRCODE_invalid_e164_number_type--155'"
		case ERRCODE_lost_number_request_type: value_str = "'ERRCODE_lost_number_request_type--156'"
		case ERRCODE_secondary_number_not_existed: value_str = "'ERRCODE_secondary_number_not_existed--157'"
		case ERRCODE_invalid_content: value_str = "'ERRCODE_invalid_content--158'"
		case ERRCODE_invalid_email: value_str = "'ERRCODE_invalid_email--159'"
		case ERRCODE_repeated_request: value_str = "'ERRCODE_repeated_request--160'"
		case ERRCODE_rules_exist: value_str = "'ERRCODE_rules_exist--161'"
		case ERRCODE_lack_of_donor: value_str = "'ERRCODE_lack_of_donor--162'"
		case ERRCODE_lost_im_user_name: value_str = "'ERRCODE_lost_im_user_name--163'"
		case ERRCODE_lost_im_password: value_str = "'ERRCODE_lost_im_password--164'"
		case ERRCODE_invalid_im_nickname: value_str = "'ERRCODE_invalid_im_nickname--165'"
		case ERRCODE_im_user_dereg_failed: value_str = "'ERRCODE_im_user_dereg_failed--166'"
		case ERRCODE_im_user_not_existed: value_str = "'ERRCODE_im_user_not_existed--167'"
		case ERRCODE_im_user_reg_failed: value_str = "'ERRCODE_im_user_reg_failed--168'"
		case ERRCODE_invalid_im_user_name: value_str = "'ERRCODE_invalid_im_user_name--169'"
		case ERRCODE_invalid_im_password: value_str = "'ERRCODE_invalid_im_password--170'"
		case ERRCODE_lost_imsi: value_str = "'ERRCODE_lost_imsi--171'"
		case ERRCODE_lost_binding_status: value_str = "'ERRCODE_lost_binding_status--172'"
		case ERRCODE_invalid_binding_status: value_str = "'ERRCODE_invalid_binding_status--173'"
		case ERRCODE_package_exist: value_str = "'ERRCODE_package_exist--174'"
		case ERRCODE_invalid_billing_user_data: value_str = "'ERRCODE_invalid_billing_user_data--175'"
		case ERRCODE_Failure_to_activate_validity: value_str = "'ERRCODE_Failure_to_activate_validity--176'"
		case ERRCODE_Time_lapse: value_str = "'ERRCODE_Time_lapse--177'"
		case ERRCODE_Billing_reached_the_limit: value_str = "'ERRCODE_Billing_reached_the_limit--178'"
		case ERRCODE_invalid_recharge: value_str = "'ERRCODE_invalid_recharge--179'"
		case ERRCODE_Date_expired: value_str = "'ERRCODE_Date_expired--180'"
		case ERRCODE_lost_package_info: value_str = "'ERRCODE_lost_package_info--181'"
		case ERRCODE_not_access: value_str = "'ERRCODE_not_access--182'"
		case ERRCODE_invalid_minute: value_str = "'ERRCODE_invalid_minute--183'"
		case ERRCODE_invalid_second: value_str = "'ERRCODE_invalid_second--184'"
		case ERRCODE_not_do_anything: value_str = "'ERRCODE_not_do_anything--185'"
		case ERRCODE_empty_data: value_str = "'ERRCODE_empty_data--186'"
		case ERRCODE_not_group_rules: value_str = "'ERRCODE_not_group_rules--187'"
		case ERRCODE_on_billing_operation_not_allowed: value_str = "'ERRCODE_on_billing_operation_not_allowed--188'"
		case ERRCODE_roaming_not_allowed: value_str = "'ERRCODE_roaming_not_allowed--189'"
		case ERRCODE_invalid_mcard: value_str = "'ERRCODE_invalid_mcard--190'"
		case ERRCODE_Too_many_packages: value_str = "'ERRCODE_Too_many_packages--191'"
		case ERRCODE_Too_many_rules: value_str = "'ERRCODE_Too_many_rules--192'"
		case ERRCODE_can_not_find_mcard: value_str = "'ERRCODE_can_not_find_mcard--193'"
		case ERRCODE_Failure_to_be_deactived: value_str = "'ERRCODE_Failure_to_be_deactived--194'"
		case ERRCODE_operating_end: value_str = "'ERRCODE_operating_end--195'"
		case ERRCODE_invalid_voip_setting: value_str = "'ERRCODE_invalid_voip_setting--196'"
		case ERRCODE_Call_barring: value_str = "'ERRCODE_Call_barring--197'"
		case ERRCODE_add_forbidden_user_failed: value_str = "'ERRCODE_add_forbidden_user_failed--198'"
		case ERRCODE_forbidden_register_user: value_str = "'ERRCODE_forbidden_register_user--199'"
		case ERRCODE_Unauthorized: value_str = "'ERRCODE_Unauthorized--200'"
		case ERRCODE_is_rnm_user: value_str = "'ERRCODE_is_rnm_user--201'"
		case ERRCODE_table_exist: value_str = "'ERRCODE_table_exist--202'"
		case ERRCODE_record_empty: value_str = "'ERRCODE_record_empty--203'"
		case ERRCODE_impu_existed: value_str = "'ERRCODE_impu_existed--204'"
		case ERRCODE_invalid_context: value_str = "'ERRCODE_invalid_context--205'"
		case ERRCODE_authorized_failed: value_str = "'ERRCODE_authorized_failed--206'"
		case ERRCODE_logout: value_str = "'ERRCODE_logout--207'"
		case ERRCODE_mute_set_failed: value_str = "'ERRCODE_mute_set_failed--208'"
		case ERRCODE_invalid_url: value_str = "'ERRCODE_invalid_url--209'"
		case ERRCODE_Threshold_limit: value_str = "'ERRCODE_Threshold_limit--210'"
		case ERRCODE_Channel_closed: value_str = "'ERRCODE_Channel_closed--211'"
		case ERRCODE_invalid_request: value_str = "'ERRCODE_invalid_request--212'"
		case ERRCODE_Duplicate_name: value_str = "'ERRCODE_Duplicate_name--213'"
		case ERRCODE_lost_parameter: value_str = "'ERRCODE_lost_parameter--214'"
		case ERRCODE_lost_protocol: value_str = "'ERRCODE_lost_protocol--215'"
		case ERRCODE_system_not_ready: value_str = "'ERRCODE_system_not_ready--216'"
		case ERRCODE_package_check: value_str = "'ERRCODE_package_check--217'"
		case ERRCODE_package_discard: value_str = "'ERRCODE_package_discard--218'"
		case ERRCODE_resend: value_str = "'ERRCODE_resend--219'"
		case ERRCODE_Invalid_object: value_str = "'ERRCODE_Invalid_object--220'"
		case ERRCODE_over_max_package_types: value_str = "'ERRCODE_over_max_package_types--221'"
		case ERRCODE_over_max_package_numbers: value_str = "'ERRCODE_over_max_package_numbers--222'"
		case ERRCODE_wait_more_data: value_str = "'ERRCODE_wait_more_data--223'"
		case ERRCODE_unregister: value_str = "'ERRCODE_unregister--224'"
		case ERRCODE_maximum_intents: value_str = "'ERRCODE_maximum_intents--225'"
		case ERRCODE_intercept: value_str = "'ERRCODE_intercept--226'"
		case ERRCODE_repetitive_operation: value_str = "'ERRCODE_repetitive_operation--227'"
		case ERRCODE_Failed_to_identify: value_str = "'ERRCODE_Failed_to_identify--228'"
		case ERRCODE_Failed_to_features: value_str = "'ERRCODE_Failed_to_features--229'"
		case ERRCODE_No_clear_intention: value_str = "'ERRCODE_No_clear_intention--230'"
		case ERRCODE_db_no_data: value_str = "'ERRCODE_db_no_data--231'"
		case ERRCODE_insufficient_balance: value_str = "'ERRCODE_insufficient_balance--232'"
		case ERRCODE_lost_lock: value_str = "'ERRCODE_lost_lock--233'"
		case ERRCODE_lost_req_type: value_str = "'ERRCODE_lost_req_type--234'"
		case ERRCODE_can_not_find_client: value_str = "'ERRCODE_can_not_find_client--235'"
		case ERRCODE_out_of_bounds: value_str = "'ERRCODE_out_of_bounds--236'"
		case ERRCODE_valuation: value_str = "'ERRCODE_valuation--237'"
		case ERRCODE_Invalid_version: value_str = "'ERRCODE_Invalid_version--238'"
		case ERRCODE_auth_key_exist: value_str = "'ERRCODE_auth_key_exist--239'"
		case ERRCODE_predict_failed: value_str = "'ERRCODE_predict_failed--240'"
		case ERRCODE_internal_server_error: value_str = "'ERRCODE_internal_server_error--241'"
		case ERRCODE_update: value_str = "'ERRCODE_update--242'"
		case ERRCODE_lost_atom_ptl: value_str = "'ERRCODE_lost_atom_ptl--243'"
		case ERRCODE_bs_repeat: value_str = "'ERRCODE_bs_repeat--244'"
		case ERRCODE_can_not_find_user: value_str = "'ERRCODE_can_not_find_user--245'"
		case ERRCODE_name_already_exist: value_str = "'ERRCODE_name_already_exist--246'"
		case ERRCODE_can_not_find_cost_price: value_str = "'ERRCODE_can_not_find_cost_price--247'"
		case ERRCODE_can_not_find_unit_price: value_str = "'ERRCODE_can_not_find_unit_price--248'"
		case ERRCODE_cfg_already_exists: value_str = "'ERRCODE_cfg_already_exists--249'"
		case ERRCODE_storage: value_str = "'ERRCODE_storage--250'"
		case ERRCODE_Can_not_find_path: value_str = "'ERRCODE_Can_not_find_path--251'"
		case ERRCODE_over_time: value_str = "'ERRCODE_over_time--252'"
		case ERRCODE_soft_delete: value_str = "'ERRCODE_soft_delete--253'"
		case ERRCODE_Not_found_ptl_name: value_str = "'ERRCODE_Not_found_ptl_name--254'"
		case ERRCODE_RELEASE: value_str = "'ERRCODE_RELEASE--255'"
		case ERRCODE_Not_found_billing: value_str = "'ERRCODE_Not_found_billing--256'"
		case ERRCODE_Can_not_find_area: value_str = "'ERRCODE_Can_not_find_area--257'"
		case ERRCODE_User_Unregister: value_str = "'ERRCODE_User_Unregister--258'"
		case ERRCODE_Stateless_Sending: value_str = "'ERRCODE_Stateless_Sending--259'"
		case ERRCODE_Can_not_find_business_rules: value_str = "'ERRCODE_Can_not_find_business_rules--260'"
		case ERRCODE_reconnect: value_str = "'ERRCODE_reconnect--261'"
		case ERRCODE_Blacklist_intercept: value_str = "'ERRCODE_Blacklist_intercept--262'"
		case ERRCODE_data_not_exist: value_str = "'ERRCODE_data_not_exist--263'"
		case ERRCODE_Invalid_length: value_str = "'ERRCODE_Invalid_length--264'"
		case ERRCODE_Route_Direct: value_str = "'ERRCODE_Route_Direct--265'"
		case ERRCODE_Can_not_find_isp: value_str = "'ERRCODE_Can_not_find_isp--266'"
		case ERRCODE_DB_Already_Exist: value_str = "'ERRCODE_DB_Already_Exist--267'"
		case ErrCode_max: value_str = "'ErrCode_max-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_FixedPortFlag_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case FixedPort: value_str = "'FixedPort-0x01234567'"
		case NotFixedPort: value_str = "'NotFixedPort-0x09abcdef'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_HTTPListenType_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case ListenHttp: value_str = "'ListenHttp'"
		case ListenHttps: value_str = "'ListenHttps'"
		case ListenWeb: value_str = "'ListenWeb'"
		case ListenMax: value_str = "'ListenMax'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_HTTPMathcRule_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case LocationMatch_Accurate: value_str = "'LocationMatch_Accurate-0'"
		case LocationMatch_Prefix: value_str = "'LocationMatch_Prefix'"
		case LocationMatch_CaseRegular: value_str = "'LocationMatch_CaseRegular'"
		case LocationMatch_Regular: value_str = "'LocationMatch_Regular'"
		case LocationMatch_CaseRegularExcl: value_str = "'LocationMatch_CaseRegularExcl'"
		case LocationMatch_RegularExcl: value_str = "'LocationMatch_RegularExcl'"
		case LocationMatch_Wildcard: value_str = "'LocationMatch_Wildcard'"
		case LocationMatch_Max: value_str = "'LocationMatch_Max'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_HttpContentType_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case HttpContentType_json: value_str = "'HttpContentType_json'"
		case HttpContentType_text: value_str = "'HttpContentType_text'"
		case HttpContentType_xml: value_str = "'HttpContentType_xml'"
		case HttpContentType_xwww: value_str = "'HttpContentType_xwww'"
		case HttpContentType_max: value_str = "'HttpContentType_max'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_HttpMethod_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case HttpMethod_post: value_str = "'HttpMethod_post'"
		case HttpMethod_get: value_str = "'HttpMethod_get'"
		case HttpMethod_put: value_str = "'HttpMethod_put'"
		case HttpMethod_options: value_str = "'HttpMethod_options'"
		case HttpMethod_delete: value_str = "'HttpMethod_delete'"
		case HttpMethod_max: value_str = "'HttpMethod_max'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_IPProtocol_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case IPProtocol_ICMP: value_str = "'IPProtocol_ICMP-1'"
		case IPProtocol_TCP: value_str = "'IPProtocol_TCP-6'"
		case IPProtocol_UDP: value_str = "'IPProtocol_UDP-17'"
		case IPProtocol_GRE: value_str = "'IPProtocol_GRE-47'"
		case IPProtocol_MAX: value_str = "'IPProtocol_MAX-0x1fffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_IPVER_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case IPVER_IPV4: value_str = "'IPVER_IPV4-4'"
		case IPVER_IPV6: value_str = "'IPVER_IPV6-6'"
		case IPVER_MAX: value_str = "'IPVER_MAX-0x1fffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_LanguageCode_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case LanguageCode_Abkhazian: value_str = "'LanguageCode_Abkhazian'"
		case LanguageCode_Afar: value_str = "'LanguageCode_Afar'"
		case LanguageCode_Afrikaans: value_str = "'LanguageCode_Afrikaans'"
		case LanguageCode_Akan: value_str = "'LanguageCode_Akan'"
		case LanguageCode_Albanian: value_str = "'LanguageCode_Albanian'"
		case LanguageCode_Amharic: value_str = "'LanguageCode_Amharic'"
		case LanguageCode_Arabic: value_str = "'LanguageCode_Arabic'"
		case LanguageCode_Aragonese: value_str = "'LanguageCode_Aragonese'"
		case LanguageCode_Armenian: value_str = "'LanguageCode_Armenian'"
		case LanguageCode_Assamese: value_str = "'LanguageCode_Assamese'"
		case LanguageCode_Avaric: value_str = "'LanguageCode_Avaric'"
		case LanguageCode_Avestan: value_str = "'LanguageCode_Avestan'"
		case LanguageCode_Aymara: value_str = "'LanguageCode_Aymara'"
		case LanguageCode_Chinese: value_str = "'LanguageCode_Chinese'"
		case LanguageCode_Chuvash: value_str = "'LanguageCode_Chuvash'"
		case LanguageCode_Cornish: value_str = "'LanguageCode_Cornish'"
		case LanguageCode_Corsican: value_str = "'LanguageCode_Corsican'"
		case LanguageCode_English: value_str = "'LanguageCode_English'"
		case LanguageCode_French: value_str = "'LanguageCode_French'"
		case LanguageCode_German: value_str = "'LanguageCode_German'"
		case LanguageCode_Italian: value_str = "'LanguageCode_Italian'"
		case LanguageCode_Japanese: value_str = "'LanguageCode_Japanese'"
		case LanguageCode_Korean: value_str = "'LanguageCode_Korean'"
		case LanguageCode_Russian: value_str = "'LanguageCode_Russian'"
		case LanguageCode_Spanish_Castilian: value_str = "'LanguageCode_Spanish_Castilian'"
		case LanguageCode_Sundanese: value_str = "'LanguageCode_Sundanese'"
		case LanguageCode_Swahili: value_str = "'LanguageCode_Swahili'"
		case LanguageCode_Swati: value_str = "'LanguageCode_Swati'"
		case LanguageCode_Swedish: value_str = "'LanguageCode_Swedish'"
		case LanguageCode_Tamil: value_str = "'LanguageCode_Tamil'"
		case LanguageCode_Telugu: value_str = "'LanguageCode_Telugu'"
		case LanguageCode_Tajik: value_str = "'LanguageCode_Tajik'"
		case LanguageCode_Thai: value_str = "'LanguageCode_Thai'"
		case LanguageCode_Traditional_Chinese: value_str = "'LanguageCode_Traditional_Chinese'"
		case LanguageCode_Dutch: value_str = "'LanguageCode_Dutch'"
		case LanguageCode_max: value_str = "'LanguageCode_max'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_MCardContentType_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case MCardContentType_begin: value_str = "'MCardContentType_begin'"
		case MCardContentType_utf8: value_str = "'MCardContentType_utf8'"
		case MCardContentType_json: value_str = "'MCardContentType_json'"
		case MCardContentType_xml: value_str = "'MCardContentType_xml'"
		case MCardContentType_login: value_str = "'MCardContentType_login'"
		case MCardContentType_jpg_cropped_bin: value_str = "'MCardContentType_jpg_cropped_bin'"
		case MCardContentType_jpg_uncropped_bin: value_str = "'MCardContentType_jpg_uncropped_bin'"
		case MCardContentType_image_sha1_id: value_str = "'MCardContentType_image_sha1_id'"
		case MCardContentType_face_matching: value_str = "'MCardContentType_face_matching'"
		case MCardContentType_poster_generate: value_str = "'MCardContentType_poster_generate'"
		case MCardContentType_start_up: value_str = "'MCardContentType_start_up'"
		case MCardContentType_museum_page: value_str = "'MCardContentType_museum_page'"
		case MCardContentType_painter_page: value_str = "'MCardContentType_painter_page'"
		case MCardContentType_bbs_comment: value_str = "'MCardContentType_bbs_comment'"
		case MCardContentType_bbs_load: value_str = "'MCardContentType_bbs_load'"
		case MCardContentType_painting_recommend: value_str = "'MCardContentType_painting_recommend'"
		case MCardContentType_portrait_transfer_list: value_str = "'MCardContentType_portrait_transfer_list'"
		case MCardContentType_portrait_transfer_action: value_str = "'MCardContentType_portrait_transfer_action'"
		case MCardContentType_landscape_transfer_list: value_str = "'MCardContentType_landscape_transfer_list'"
		case MCardContentType_landscape_transfer_action: value_str = "'MCardContentType_landscape_transfer_action'"
		case MCardContentType_image_search_cropped_bin: value_str = "'MCardContentType_image_search_cropped_bin'"
		case MCardContentType_image_search_uncropped_bin: value_str = "'MCardContentType_image_search_uncropped_bin'"
		case MCardContentType_sculptures_search_cropped_bin: value_str = "'MCardContentType_sculptures_search_cropped_bin'"
		case MCardContentType_sculptures_search_uncropped_bin: value_str = "'MCardContentType_sculptures_search_uncropped_bin'"
		case MCardContentType_menu_recognition: value_str = "'MCardContentType_menu_recognition'"
		case MCardContentType_tourism_image_search: value_str = "'MCardContentType_tourism_image_search'"
		case MCardContentType_bagword: value_str = "'MCardContentType_bagword'"
		case MCardContentType_museum_recommend: value_str = "'MCardContentType_museum_recommend'"
		case MCardContentType_painting_recommend_page: value_str = "'MCardContentType_painting_recommend_page'"
		case MCardContentType_museum_recommend_page: value_str = "'MCardContentType_museum_recommend_page'"
		case MCardContentType_museum_sha1_id: value_str = "'MCardContentType_museum_sha1_id'"
		case MCardContentType_refresh_recommend_cache: value_str = "'MCardContentType_refresh_recommend_cache'"
		case MCardContentType_detection: value_str = "'MCardContentType_detection'"
		case MCardContentType_generator: value_str = "'MCardContentType_generator'"
		case MCardContentType_end: value_str = "'MCardContentType_end'"
		case MCardContentType_max: value_str = "'MCardContentType_max-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_MCardIdentityType_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case MCardIdentityType_none: value_str = "'MCardIdentityType_none'"
		case MCardIdentityType_initialization: value_str = "'MCardIdentityType_initialization'"
		case MCardIdentityType_user: value_str = "'MCardIdentityType_user'"
		case MCardIdentityType_AI: value_str = "'MCardIdentityType_AI'"
		case MCardIdentityType_max: value_str = "'MCardIdentityType_max'"
		case MCardIdentityType_MAX: value_str = "'MCardIdentityType_MAX-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_MCardSource_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case MCardSource_aia: value_str = "'MCardSource_aia'"
		case MCardSource_google: value_str = "'MCardSource_google'"
		case MCardSource_aws: value_str = "'MCardSource_aws'"
		case MCardSource_aic: value_str = "'MCardSource_aic'"
		case MCardSource_aib: value_str = "'MCardSource_aib'"
		case MCardSource_aib_io: value_str = "'MCardSource_aib_io'"
		case MCardSource_bbs: value_str = "'MCardSource_bbs'"
		case MCardSource_max: value_str = "'MCardSource_max-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_MCardTimeType_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case MCardTimeType_Permanent: value_str = "'MCardTimeType_Permanent'"
		case MCardTimeType_Normal: value_str = "'MCardTimeType_Normal'"
		case MCardTimeType_max: value_str = "'MCardTimeType_max-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_MCardType_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case MCardType_Private_Message_Board: value_str = "'MCardType_Private_Message_Board'"
		case MCardType_Public_Message_Board: value_str = "'MCardType_Public_Message_Board'"
		case MCardType_POI: value_str = "'MCardType_POI'"
		case MCardType_TALK: value_str = "'MCardType_TALK'"
		case MCardType_weichat_talk: value_str = "'MCardType_weichat_talk'"
		case MCardType_h5_talk: value_str = "'MCardType_h5_talk'"
		case MCardType_max: value_str = "'MCardType_max-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_MCardVer_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case MCardVer_reserve: value_str = "'MCardVer_reserve'"
		case MCardVer_text: value_str = "'MCardVer_text'"
		case MCardVer_media: value_str = "'MCardVer_media'"
		case MCardVer_talk: value_str = "'MCardVer_talk'"
		case MCardVer_comment: value_str = "'MCardVer_comment'"
		case MCardVer_max: value_str = "'MCardVer_max-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_NetAddrType_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case NetAddrIPType: value_str = "'NetAddrIPType-0'"
		case NetAddrIPBroadcastType: value_str = "'NetAddrIPBroadcastType'"
		case NetAddrURLType: value_str = "'NetAddrURLType-0x12345678'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_PythonFun_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case PythonFun_painting_aesthetics: value_str = "'PythonFun_painting_aesthetics-0'"
		case PythonFun_image_search_engine: value_str = "'PythonFun_image_search_engine'"
		case PythonFun_painting_recommend: value_str = "'PythonFun_painting_recommend'"
		case PythonFun_style_transfer: value_str = "'PythonFun_style_transfer'"
		case PythonFun_sculptures_search_engine: value_str = "'PythonFun_sculptures_search_engine'"
		case PythonFun_menu_recognition: value_str = "'PythonFun_menu_recognition'"
		case PythonFun_travel_aesthetics: value_str = "'PythonFun_travel_aesthetics'"
		case PythonFun_weichat_openid: value_str = "'PythonFun_weichat_openid'"
		case PythonFun_poster: value_str = "'PythonFun_poster'"
		case PythonFun_bagword: value_str = "'PythonFun_bagword'"
		case PythonFun_museum_recommend: value_str = "'PythonFun_museum_recommend'"
		case PythonFun_painting_recommend_page: value_str = "'PythonFun_painting_recommend_page'"
		case PythonFun_museum_recommend_page: value_str = "'PythonFun_museum_recommend_page'"
		case PythonFun_refresh_recommend_cache: value_str = "'PythonFun_refresh_recommend_cache'"
		case PythonFun_detection: value_str = "'PythonFun_detection'"
		case PythonFun_generator: value_str = "'PythonFun_generator'"
		case PythonFun_max: value_str = "'PythonFun_max-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_RetCode_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case RetCode_begin_value: value_str = "'RetCode_begin_value-1'"
		case RetCode_OK: value_str = "'RetCode_OK-0'"
		case RetCode_Memory_full: value_str = "'RetCode_Memory_full--1'"
		case RetCode_Limited_resources: value_str = "'RetCode_Limited_resources--2'"
		case RetCode_Arithmetic_error: value_str = "'RetCode_Arithmetic_error--3'"
		case RetCode_Unknown_error: value_str = "'RetCode_Unknown_error--4'"
		case RetCode_Can_not_find_node: value_str = "'RetCode_Can_not_find_node--5'"
		case RetCode_Send_failed: value_str = "'RetCode_Send_failed--6'"
		case RetCode_Recv_failed: value_str = "'RetCode_Recv_failed--7'"
		case RetCode_Invalid_data: value_str = "'RetCode_Invalid_data--8'"
		case RetCode_Unsupported_type: value_str = "'RetCode_Unsupported_type--9'"
		case RetCode_Invalid_user_name: value_str = "'RetCode_Invalid_user_name--10'"
		case RetCode_Parameter_conflicts: value_str = "'RetCode_Parameter_conflicts--11'"
		case RetCode_Invalid_device: value_str = "'RetCode_Invalid_device--12'"
		case RetCode_Invalid_Event: value_str = "'RetCode_Invalid_Event--13'"
		case RetCode_Heartbeat_timeout: value_str = "'RetCode_Heartbeat_timeout--14'"
		case RetCode_invalid_content: value_str = "'RetCode_invalid_content--15'"
		case RetCode_save_failed: value_str = "'RetCode_save_failed--16'"
		case RetCode_Invalid_data_too_short: value_str = "'RetCode_Invalid_data_too_short--17'"
		case RetCode_Invalid_data_too_long: value_str = "'RetCode_Invalid_data_too_long--18'"
		case RetCode_Invalid_data_crc_check: value_str = "'RetCode_Invalid_data_crc_check--19'"
		case RetCode_Invalid_parameter: value_str = "'RetCode_Invalid_parameter--20'"
		case RetCode_Send_msg_failed: value_str = "'RetCode_Send_msg_failed--21'"
		case RetCode_Resource_conflicts: value_str = "'RetCode_Resource_conflicts--22'"
		case RetCode_CREDIT_LIMIT_REACHED: value_str = "'RetCode_CREDIT_LIMIT_REACHED--23'"
		case RetCode_Exceeded_number: value_str = "'RetCode_Exceeded_number--24'"
		case RetCode_do_not_free: value_str = "'RetCode_do_not_free--25'"
		case RetCode_Request_failed: value_str = "'RetCode_Request_failed--26'"
		case RetCode_can_not_find_ret_code: value_str = "'RetCode_can_not_find_ret_code--27'"
		case RetCode_user_is_registered: value_str = "'RetCode_user_is_registered--28'"
		case RetCode_connect_error: value_str = "'RetCode_connect_error--29'"
		case RetCode_function_not_supported: value_str = "'RetCode_function_not_supported--30'"
		case RetCode_msg_queue_is_full: value_str = "'RetCode_msg_queue_is_full--31'"
		case RetCode_msg_can_not_resend_wakeup: value_str = "'RetCode_msg_can_not_resend_wakeup--32'"
		case RetCode_msg_memory_if_full: value_str = "'RetCode_msg_memory_if_full--33'"
		case RetCode_msg_competition_for_resources: value_str = "'RetCode_msg_competition_for_resources--34'"
		case RetCode_wait: value_str = "'RetCode_wait--35'"
		case RetCode_Invalid_state: value_str = "'RetCode_Invalid_state--36'"
		case RetCode_usr_default: value_str = "'RetCode_usr_default--37'"
		case RetCode_timer_out: value_str = "'RetCode_timer_out--38'"
		case RetCode_invalid_type: value_str = "'RetCode_invalid_type--39'"
		case RetCode_user_does_not_exist: value_str = "'RetCode_user_does_not_exist--40'"
		case RetCode_version_new: value_str = "'RetCode_version_new--41'"
		case RetCode_version_old: value_str = "'RetCode_version_old--42'"
		case RetCode_ptr_null: value_str = "'RetCode_ptr_null--43'"
		case RetCode_record_not_exist: value_str = "'RetCode_record_not_exist--44'"
		case RetCode_db_store_failed: value_str = "'RetCode_db_store_failed--45'"
		case RetCode_db_not_find: value_str = "'RetCode_db_not_find--46'"
		case RetCode_Invalid_channel_name: value_str = "'RetCode_Invalid_channel_name--47'"
		case RetCode_Invalid_db_store: value_str = "'RetCode_Invalid_db_store--48'"
		case RetCode_version_mismatch: value_str = "'RetCode_version_mismatch--49'"
		case RetCode_invalid_version_file: value_str = "'RetCode_invalid_version_file--50'"
		case RetCode_version_identical: value_str = "'RetCode_version_identical--51'"
		case RetCode_channel_not_exist: value_str = "'RetCode_channel_not_exist--52'"
		case RetCode_invalid_option: value_str = "'RetCode_invalid_option--53'"
		case RetCode_Invalid_domain: value_str = "'RetCode_Invalid_domain--54'"
		case RetCode_Invalid_auth_key: value_str = "'RetCode_Invalid_auth_key--55'"
		case RetCode_invalid_key: value_str = "'RetCode_invalid_key--56'"
		case RetCode_no_account_found: value_str = "'RetCode_no_account_found--57'"
		case RetCode_invalid_phone_number: value_str = "'RetCode_invalid_phone_number--58'"
		case RetCode_not_match_domain: value_str = "'RetCode_not_match_domain--59'"
		case RetCode_invalid_account: value_str = "'RetCode_invalid_account--60'"
		case RetCode_please_help_free: value_str = "'RetCode_please_help_free--61'"
		case RetCode_db_init_failed: value_str = "'RetCode_db_init_failed--62'"
		case RetCode_update_fail: value_str = "'RetCode_update_fail--63'"
		case RetCode_maybe_have_data: value_str = "'RetCode_maybe_have_data--64'"
		case RetCode_do_not_restart: value_str = "'RetCode_do_not_restart--65'"
		case RetCode_lost_auth_key: value_str = "'RetCode_lost_auth_key--66'"
		case RetCode_lost_serial: value_str = "'RetCode_lost_serial--67'"
		case RetCode_lost_time: value_str = "'RetCode_lost_time--68'"
		case RetCode_lost_uuid: value_str = "'RetCode_lost_uuid--69'"
		case RetCode_lost_user: value_str = "'RetCode_lost_user--70'"
		case RetCode_can_not_find_record: value_str = "'RetCode_can_not_find_record--71'"
		case RetCode_empty_data: value_str = "'RetCode_empty_data--72'"
		case RetCode_Channel_closed: value_str = "'RetCode_Channel_closed--73'"
		case RetCode_lost_link: value_str = "'RetCode_lost_link--74'"
		case RetCode_record_not_found: value_str = "'RetCode_record_not_found--75'"
		case RetCode_not_access: value_str = "'RetCode_not_access--76'"
		case RetCode_can_not_find_thread: value_str = "'RetCode_can_not_find_thread--77'"
		case RetCode_can_not_find_client: value_str = "'RetCode_can_not_find_client--78'"
		case RetCode_user_exist: value_str = "'RetCode_user_exist--79'"
		case RetCode_store_data_failed: value_str = "'RetCode_store_data_failed--80'"
		case RetCode_Invalid_user_type: value_str = "'RetCode_Invalid_user_type--81'"
		case RetCode_invalid_user: value_str = "'RetCode_invalid_user--82'"
		case RetCode_unsupport: value_str = "'RetCode_unsupport--83'"
		case RetCode_unpackage_failed: value_str = "'RetCode_unpackage_failed--84'"
		case RetCode_creat_db_failed: value_str = "'RetCode_creat_db_failed--85'"
		case RetCode_Invalid_channel: value_str = "'RetCode_Invalid_channel--86'"
		case RetCode_heartbeat_timer_out: value_str = "'RetCode_heartbeat_timer_out--87'"
		case RetCode_not_my_data: value_str = "'RetCode_not_my_data--88'"
		case RetCode_Invalid_rules: value_str = "'RetCode_Invalid_rules--89'"
		case RetCode_busy: value_str = "'RetCode_busy--90'"
		case RetCode_data_overflow: value_str = "'RetCode_data_overflow--91'"
		case RetCode_invalid_account_name: value_str = "'RetCode_invalid_account_name--92'"
		case RetCode_Account_in_use: value_str = "'RetCode_Account_in_use--93'"
		case RetCode_invalid_address: value_str = "'RetCode_invalid_address--94'"
		case RetCode_can_not_find_rules: value_str = "'RetCode_can_not_find_rules--95'"
		case RetCode_refuse_call_self: value_str = "'RetCode_refuse_call_self--96'"
		case RetCode_Invalid_call: value_str = "'RetCode_Invalid_call--97'"
		case RetCode_mismatch: value_str = "'RetCode_mismatch--98'"
		case RetCode_Invalid_call_type: value_str = "'RetCode_Invalid_call_type--99'"
		case RetCode_Invalid_billing: value_str = "'RetCode_Invalid_billing--100'"
		case RetCode_invalid_magic: value_str = "'RetCode_invalid_magic--101'"
		case RetCode_create_thread_failed: value_str = "'RetCode_create_thread_failed--102'"
		case RetCode_script_execution_error: value_str = "'RetCode_script_execution_error--103'"
		case RetCode_decode_failed: value_str = "'RetCode_decode_failed--104'"
		case RetCode_encode_failed: value_str = "'RetCode_encode_failed--105'"
		case RetCode_invalid_file: value_str = "'RetCode_invalid_file--106'"
		case RetCode_file_open_failed: value_str = "'RetCode_file_open_failed--107'"
		case RetCode_process_now: value_str = "'RetCode_process_now--108'"
		case RetCode_queue_too_large: value_str = "'RetCode_queue_too_large--109'"
		case RetCode_repeated_request: value_str = "'RetCode_repeated_request--110'"
		case RetCode_Can_not_find_path: value_str = "'RetCode_Can_not_find_path--111'"
		case RetCode_invalid_hour: value_str = "'RetCode_invalid_hour--112'"
		case RetCode_invalid_day: value_str = "'RetCode_invalid_day--113'"
		case RetCode_invalid_week: value_str = "'RetCode_invalid_week--114'"
		case RetCode_invalid_month: value_str = "'RetCode_invalid_month--115'"
		case RetCode_invalid_year: value_str = "'RetCode_invalid_year--116'"
		case RetCode_invalid_date: value_str = "'RetCode_invalid_date--117'"
		case RetCode_table_exist: value_str = "'RetCode_table_exist--118'"
		case RetCode_db_sql_failed: value_str = "'RetCode_db_sql_failed--119'"
		case RetCode_Unauthorized_access: value_str = "'RetCode_Unauthorized_access--120'"
		case RetCode_not_ready: value_str = "'RetCode_not_ready--121'"
		case RetCode_Unauthorized: value_str = "'RetCode_Unauthorized--122'"
		case RetCode_can_not_find_method: value_str = "'RetCode_can_not_find_method--123'"
		case RetCode_invalid_call: value_str = "'RetCode_invalid_call--124'"
		case RetCode_max: value_str = "'RetCode_max-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_SOCDOMAIN_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case DM_SOC_PF_INET: value_str = "'DM_SOC_PF_INET-0'"
		case DM_SOC_PF_INET6: value_str = "'DM_SOC_PF_INET6'"
		case DM_SOC_PF_UART: value_str = "'DM_SOC_PF_UART'"
		case DM_SOC_PF_LOCAL_INET: value_str = "'DM_SOC_PF_LOCAL_INET'"
		case DM_SOC_PF_LOCAL_INET6: value_str = "'DM_SOC_PF_LOCAL_INET6'"
		case DM_SOC_PF_RAW: value_str = "'DM_SOC_PF_RAW'"
		case DM_SOC_PF_RAW_INET: value_str = "'DM_SOC_PF_RAW_INET'"
		case SOCDOMAIN_MAX: value_str = "'SOCDOMAIN_MAX-0x1fffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_SOCEVENT_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case SOC_EVENT_START: value_str = "'SOC_EVENT_START-0'"
		case SOC_EVENT_WAIT_CREAT: value_str = "'SOC_EVENT_WAIT_CREAT'"
		case SOC_EVENT_CONNECT: value_str = "'SOC_EVENT_CONNECT'"
		case SOC_EVENT_CONNECT_FAIL: value_str = "'SOC_EVENT_CONNECT_FAIL'"
		case SOC_EVENT_WAIT_CONNECT: value_str = "'SOC_EVENT_WAIT_CONNECT'"
		case SOC_EVENT_ACCEPT: value_str = "'SOC_EVENT_ACCEPT'"
		case SOC_EVENT_REV: value_str = "'SOC_EVENT_REV'"
		case SOC_EVENT_SND: value_str = "'SOC_EVENT_SND'"
		case SOC_EVENT_CLOSE: value_str = "'SOC_EVENT_CLOSE'"
		case SOC_EVENT_SILENCE: value_str = "'SOC_EVENT_SILENCE'"
		case SOC_EVENT_MAX: value_str = "'SOC_EVENT_MAX'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_SOCKETINFO_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case SOCKETINFO_BIND: value_str = "'SOCKETINFO_BIND-0'"
		case SOCKETINFO_BIND_OK: value_str = "'SOCKETINFO_BIND_OK'"
		case SOCKETINFO_BIND_FAIL: value_str = "'SOCKETINFO_BIND_FAIL'"
		case SOCKETINFO_CONNECT: value_str = "'SOCKETINFO_CONNECT'"
		case SOCKETINFO_CONNECT_OK: value_str = "'SOCKETINFO_CONNECT_OK'"
		case SOCKETINFO_CONNECT_FAIL: value_str = "'SOCKETINFO_CONNECT_FAIL'"
		case SOCKETINFO_CONNECT_WAIT: value_str = "'SOCKETINFO_CONNECT_WAIT'"
		case SOCKETINFO_DISCONNECT: value_str = "'SOCKETINFO_DISCONNECT'"
		case SOCKETINFO_DISCONNECT_OK: value_str = "'SOCKETINFO_DISCONNECT_OK'"
		case SOCKETINFO_DISCONNECT_FAIL: value_str = "'SOCKETINFO_DISCONNECT_FAIL'"
		case SOCKETINFO_DISCONNECT_WAIT: value_str = "'SOCKETINFO_DISCONNECT_WAIT'"
		case SOCKETINFO_CREAT: value_str = "'SOCKETINFO_CREAT'"
		case SOCKETINFO_WAIT_CREAT: value_str = "'SOCKETINFO_WAIT_CREAT'"
		case SOCKETINFO_ACCEPT: value_str = "'SOCKETINFO_ACCEPT'"
		case SOCKETINFO_REV: value_str = "'SOCKETINFO_REV'"
		case SOCKETINFO_REV_MBUF: value_str = "'SOCKETINFO_REV_MBUF'"
		case SOCKETINFO_SND: value_str = "'SOCKETINFO_SND'"
		case SOCKETINFO_CLOSE: value_str = "'SOCKETINFO_CLOSE'"
		case SOCKETINFO_SILENCE: value_str = "'SOCKETINFO_SILENCE'"
		case SOCKETINFO_DEVICE_CONNECT: value_str = "'SOCKETINFO_DEVICE_CONNECT'"
		case SOCKETINFO_DEVICE_DISCONNECT: value_str = "'SOCKETINFO_DEVICE_DISCONNECT'"
		case SOCKETINFO_LINK_LOST: value_str = "'SOCKETINFO_LINK_LOST'"
		case SOCKETINFO_SEND_TIMER_OUT: value_str = "'SOCKETINFO_SEND_TIMER_OUT'"
		case SOCKETINFO_PORT_EXIST: value_str = "'SOCKETINFO_PORT_EXIST'"
		case SOCKETINFO_WRITE_THEN_CLOSE: value_str = "'SOCKETINFO_WRITE_THEN_CLOSE'"
		case SOCKETINFO_SND_URG: value_str = "'SOCKETINFO_SND_URG'"
		case SOCKETINFO_RAW_EVENT_RECV_LENGTH: value_str = "'SOCKETINFO_RAW_EVENT_RECV_LENGTH'"
		case SOCKETINFO_MAX: value_str = "'SOCKETINFO_MAX-0x1fffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_SOCTYPE_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case TYPE_SOCK_STREAM: value_str = "'TYPE_SOCK_STREAM-0'"
		case TYPE_SOCK_DGRAM: value_str = "'TYPE_SOCK_DGRAM'"
		case TYPE_SOCK_RAW: value_str = "'TYPE_SOCK_RAW'"
		case TYPE_SOCK_SCTP: value_str = "'TYPE_SOCK_SCTP'"
		case TYPE_SOCK_max: value_str = "'TYPE_SOCK_max'"
		case TYPE_SOCK_MAX: value_str = "'TYPE_SOCK_MAX-0x1fffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_UIPType_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case UIPType_uip: value_str = "'UIPType_uip'"
		case UIPType_json: value_str = "'UIPType_json'"
		case UIPType_h5_form: value_str = "'UIPType_h5_form'"
		case UIPType_wechat_form: value_str = "'UIPType_wechat_form'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

func T_auto_RPCMSG_str(enum_value int64) string {
	var value_str string

	switch enum_value {
		case MSGID_RESERVED: value_str = "'MSGID_RESERVED-0x0000000000000000'"
		case MSGID_TEST: value_str = "'MSGID_TEST-1'"
		case MSGID_TIMER: value_str = "'MSGID_TIMER-2'"
		case MSGID_WAKEUP: value_str = "'MSGID_WAKEUP-3'"
		case MSGID_RUN_FUNCTION: value_str = "'MSGID_RUN_FUNCTION-4'"
		case MSGID_DEBUG_REQ: value_str = "'MSGID_DEBUG_REQ-5'"
		case MSGID_DEBUG_RSP: value_str = "'MSGID_DEBUG_RSP-6'"
		case MSGID_RESTART_REQ: value_str = "'MSGID_RESTART_REQ-7'"
		case MSGID_RESTART_RSP: value_str = "'MSGID_RESTART_RSP-8'"
		case MSGID_POWER_OFF: value_str = "'MSGID_POWER_OFF-9'"
		case MSGID_REMOTE_THREAD_READY: value_str = "'MSGID_REMOTE_THREAD_READY-10'"
		case MSGID_REMOTE_THREAD_REMOVE: value_str = "'MSGID_REMOTE_THREAD_REMOVE-11'"
		case MSGID_TRACE_SWITCH: value_str = "'MSGID_TRACE_SWITCH-12'"
		case MSGID_PROCESS_MSG_TIMER_OUT: value_str = "'MSGID_PROCESS_MSG_TIMER_OUT-13'"
		case MSGID_TEMPORARILY_DEFINE_MESSAGE: value_str = "'MSGID_TEMPORARILY_DEFINE_MESSAGE-14'"
		case MSGID_SYSTEM_MOUNT: value_str = "'MSGID_SYSTEM_MOUNT-16'"
		case MSGID_SYSTEM_DECOUPLING: value_str = "'MSGID_SYSTEM_DECOUPLING-17'"
		case MSGID_ECHO_REQ: value_str = "'MSGID_ECHO_REQ-18'"
		case MSGID_ECHO_RSP: value_str = "'MSGID_ECHO_RSP-19'"
		case MSGID_INTERNAL_EVENTS: value_str = "'MSGID_INTERNAL_EVENTS-20'"
		case MSGID_THREAD_BUSY: value_str = "'MSGID_THREAD_BUSY-21'"
		case MSGID_THREAD_IDLE: value_str = "'MSGID_THREAD_IDLE-22'"
		case MSGID_REMOTE_THREAD_ID_READY: value_str = "'MSGID_REMOTE_THREAD_ID_READY-25'"
		case MSGID_REMOTE_THREAD_ID_REMOVE: value_str = "'MSGID_REMOTE_THREAD_ID_REMOVE-26'"
		case MSGID_LOCAL_THREAD_READY: value_str = "'MSGID_LOCAL_THREAD_READY-27'"
		case MSGID_LOCAL_THREAD_REMOVE: value_str = "'MSGID_LOCAL_THREAD_REMOVE-28'"
		case MSGID_INNER_LOOP: value_str = "'MSGID_INNER_LOOP-29'"
		case MSGID_CFG_UPDATE: value_str = "'MSGID_CFG_UPDATE-30'"
		case MSGID_OS_NOTIFY: value_str = "'MSGID_OS_NOTIFY-33'"
		case MSGID_INTERNAL_LOOP: value_str = "'MSGID_INTERNAL_LOOP-34'"
		case MSGID_COROUTINE_WAKEUP: value_str = "'MSGID_COROUTINE_WAKEUP-35'"
		case MSGID_RPC_DEBUG_REQ: value_str = "'MSGID_RPC_DEBUG_REQ-36'"
		case MSGID_RPC_DEBUG_RSP: value_str = "'MSGID_RPC_DEBUG_RSP-37'"
		case MSGID_CFG_REMOTE_UPDATE: value_str = "'MSGID_CFG_REMOTE_UPDATE-38'"
		case MSGID_DOS_FORWARD: value_str = "'MSGID_DOS_FORWARD-39'"
		case MSGID_CFG_REMOTE_SYNC_UPDATE: value_str = "'MSGID_CFG_REMOTE_SYNC_UPDATE-40'"
		case MSGID_QUEUE_UPLOAD_MESSAGE_REQ: value_str = "'MSGID_QUEUE_UPLOAD_MESSAGE_REQ-41'"
		case MSGID_QUEUE_UPLOAD_MESSAGE_RSP: value_str = "'MSGID_QUEUE_UPLOAD_MESSAGE_RSP-42'"
		case MSGID_QUEUE_DOWNLOAD_MESSAGE_REQ: value_str = "'MSGID_QUEUE_DOWNLOAD_MESSAGE_REQ-43'"
		case MSGID_QUEUE_DOWNLOAD_MESSAGE_RSP: value_str = "'MSGID_QUEUE_DOWNLOAD_MESSAGE_RSP-44'"
		case MSGID_QUEUE_UPDATE_STATE_REQ: value_str = "'MSGID_QUEUE_UPDATE_STATE_REQ-45'"
		case MSGID_QUEUE_UPDATE_STATE_RSP: value_str = "'MSGID_QUEUE_UPDATE_STATE_RSP-46'"
		case MSGID_QUEUE_RUN_MESSAGE_REQ: value_str = "'MSGID_QUEUE_RUN_MESSAGE_REQ-47'"
		case MSGID_QUEUE_RUN_MESSAGE_RSP: value_str = "'MSGID_QUEUE_RUN_MESSAGE_RSP-48'"
		case MSGID_SYSTEM_BUSY: value_str = "'MSGID_SYSTEM_BUSY-49'"
		case MSGID_SYSTEM_IDLE: value_str = "'MSGID_SYSTEM_IDLE-50'"
		case MSGID_GENERAL_REQ: value_str = "'MSGID_GENERAL_REQ-51'"
		case MSGID_GENERAL_RSP: value_str = "'MSGID_GENERAL_RSP-52'"
		case MSGID_APPLICATION_BUSY: value_str = "'MSGID_APPLICATION_BUSY-53'"
		case MSGID_APPLICATION_IDLE: value_str = "'MSGID_APPLICATION_IDLE-54'"
		case MSGID_PROTECTOR_REG: value_str = "'MSGID_PROTECTOR_REG-55'"
		case MSGID_PROTECTOR_UNREG: value_str = "'MSGID_PROTECTOR_UNREG-56'"
		case MSGID_PROTECTOR_WAKEUP: value_str = "'MSGID_PROTECTOR_WAKEUP-57'"
		case FREE_MESSAGE_AREA_1: value_str = "'FREE_MESSAGE_AREA_1-100'"
		case FREE_MESSAGE_AREA_2: value_str = "'FREE_MESSAGE_AREA_2-101'"
		case FREE_MESSAGE_AREA_3: value_str = "'FREE_MESSAGE_AREA_3-102'"
		case FREE_MESSAGE_AREA_4: value_str = "'FREE_MESSAGE_AREA_4-103'"
		case FREE_MESSAGE_AREA_5: value_str = "'FREE_MESSAGE_AREA_5-104'"
		case SOCKET_BIND_REQ: value_str = "'SOCKET_BIND_REQ-1000'"
		case SOCKET_BIND_RSP: value_str = "'SOCKET_BIND_RSP-1001'"
		case SOCKET_CONNECT_REQ: value_str = "'SOCKET_CONNECT_REQ-1002'"
		case SOCKET_CONNECT_RSP: value_str = "'SOCKET_CONNECT_RSP-1003'"
		case SOCKET_DISCONNECT_REQ: value_str = "'SOCKET_DISCONNECT_REQ-1004'"
		case SOCKET_DISCONNECT_RSP: value_str = "'SOCKET_DISCONNECT_RSP-1005'"
		case SOCKET_PLUGIN: value_str = "'SOCKET_PLUGIN-1006'"
		case SOCKET_PLUGOUT: value_str = "'SOCKET_PLUGOUT-1007'"
		case SOCKET_READ: value_str = "'SOCKET_READ-1008'"
		case SOCKET_WRITE: value_str = "'SOCKET_WRITE-1009'"
		case SOCKET_NOTIFY: value_str = "'SOCKET_NOTIFY-1010'"
		case SOCKET_RAW_EVENT: value_str = "'SOCKET_RAW_EVENT-1011'"
		case BDATA_LOG_REQ: value_str = "'BDATA_LOG_REQ-2001'"
		case BDATA_LOG_RSP: value_str = "'BDATA_LOG_RSP-2002'"
		case EMAIL_SEND_REQ: value_str = "'EMAIL_SEND_REQ-2003'"
		case EMAIL_SEND_RSP: value_str = "'EMAIL_SEND_RSP-2004'"
		case RTC_DATA_REQ: value_str = "'RTC_DATA_REQ-2005'"
		case RTC_DATA_RSP: value_str = "'RTC_DATA_RSP-2006'"
		case RTC_REG_REQ: value_str = "'RTC_REG_REQ-2007'"
		case RTC_REG_RSP: value_str = "'RTC_REG_RSP-2008'"
		case RTC_UNREG_REQ: value_str = "'RTC_UNREG_REQ-2009'"
		case RTC_UNREG_RSP: value_str = "'RTC_UNREG_RSP-2010'"
		case RTP_START_REQ: value_str = "'RTP_START_REQ-2011'"
		case RTP_START_RSP: value_str = "'RTP_START_RSP-2012'"
		case RTP_STOP_REQ: value_str = "'RTP_STOP_REQ-2013'"
		case RTP_STOP_RSP: value_str = "'RTP_STOP_RSP-2014'"
		case RTP_DATA_REQ: value_str = "'RTP_DATA_REQ-2015'"
		case RTP_DATA_RSP: value_str = "'RTP_DATA_RSP-2016'"
		case SIP_CALL_REQ: value_str = "'SIP_CALL_REQ-2017'"
		case SIP_CALL_RSP: value_str = "'SIP_CALL_RSP-2018'"
		case SIP_BYE_REQ: value_str = "'SIP_BYE_REQ-2019'"
		case SIP_BYE_RSP: value_str = "'SIP_BYE_RSP-2020'"
		case SIP_START_REQ: value_str = "'SIP_START_REQ-2021'"
		case SIP_START_RSP: value_str = "'SIP_START_RSP-2022'"
		case SIP_STOP_REQ: value_str = "'SIP_STOP_REQ-2023'"
		case SIP_STOP_RSP: value_str = "'SIP_STOP_RSP-2024'"
		case APPMSG_MCARD_REQ: value_str = "'APPMSG_MCARD_REQ-2053'"
		case APPMSG_MCARD_RSP: value_str = "'APPMSG_MCARD_RSP-2054'"
		case APPMSG_TALK_MCARD_REQ: value_str = "'APPMSG_TALK_MCARD_REQ-2085'"
		case APPMSG_TALK_MCARD_RSP: value_str = "'APPMSG_TALK_MCARD_RSP-2086'"
		case UIP_REGISTER_REQ: value_str = "'UIP_REGISTER_REQ-2110'"
		case UIP_REGISTER_RSP: value_str = "'UIP_REGISTER_RSP-2111'"
		case UIP_UNREGISTER_REQ: value_str = "'UIP_UNREGISTER_REQ-2112'"
		case UIP_UNREGISTER_RSP: value_str = "'UIP_UNREGISTER_RSP-2113'"
		case UIP_DATA_RECV_REQ: value_str = "'UIP_DATA_RECV_REQ-2114'"
		case UIP_DATA_RECV_RSP: value_str = "'UIP_DATA_RECV_RSP-2115'"
		case UIP_DATA_SEND_REQ: value_str = "'UIP_DATA_SEND_REQ-2130'"
		case UIP_DATA_SEND_RSP: value_str = "'UIP_DATA_SEND_RSP-2131'"
		case APPMSG_FUNCTION_REGISTER_REQ: value_str = "'APPMSG_FUNCTION_REGISTER_REQ-2132'"
		case APPMSG_FUNCTION_REGISTER_RSP: value_str = "'APPMSG_FUNCTION_REGISTER_RSP-2133'"
		case APPMSG_FUNCTION_UNREGISTER_REQ: value_str = "'APPMSG_FUNCTION_UNREGISTER_REQ-2134'"
		case APPMSG_FUNCTION_UNREGISTER_RSP: value_str = "'APPMSG_FUNCTION_UNREGISTER_RSP-2135'"
		case STORE_MYSQL_REQ: value_str = "'STORE_MYSQL_REQ-3001'"
		case STORE_MYSQL_RSP: value_str = "'STORE_MYSQL_RSP-3002'"
		case STORE_REDIS_REQ: value_str = "'STORE_REDIS_REQ-3003'"
		case STORE_REDIS_RSP: value_str = "'STORE_REDIS_RSP-3004'"
		case DBMSG_SYS_INQ_IMAGE_REQ: value_str = "'DBMSG_SYS_INQ_IMAGE_REQ-4212'"
		case DBMSG_SYS_INQ_IMAGE_RSP: value_str = "'DBMSG_SYS_INQ_IMAGE_RSP-4213'"
		case DBMSG_SYS_INQ_MUSEUM_REQ: value_str = "'DBMSG_SYS_INQ_MUSEUM_REQ-4214'"
		case DBMSG_SYS_INQ_MUSEUM_RSP: value_str = "'DBMSG_SYS_INQ_MUSEUM_RSP-4215'"
		case DBMSG_SYS_INQ_MUSEUM_PAGE_REQ: value_str = "'DBMSG_SYS_INQ_MUSEUM_PAGE_REQ-4226'"
		case DBMSG_SYS_INQ_MUSEUM_PAGE_RSP: value_str = "'DBMSG_SYS_INQ_MUSEUM_PAGE_RSP-4227'"
		case DBMSG_SYS_ADD_WEICHAT_REQ: value_str = "'DBMSG_SYS_ADD_WEICHAT_REQ-4222'"
		case DBMSG_SYS_ADD_WEICHAT_RSP: value_str = "'DBMSG_SYS_ADD_WEICHAT_RSP-4223'"
		case DBMSG_SYS_INQ_WEICHAT_REQ: value_str = "'DBMSG_SYS_INQ_WEICHAT_REQ-4224'"
		case DBMSG_SYS_INQ_WEICHAT_RSP: value_str = "'DBMSG_SYS_INQ_WEICHAT_RSP-4225'"
		case DBMSG_SYS_INQ_PAINTER_PAGE_REQ: value_str = "'DBMSG_SYS_INQ_PAINTER_PAGE_REQ-4230'"
		case DBMSG_SYS_INQ_PAINTER_PAGE_RSP: value_str = "'DBMSG_SYS_INQ_PAINTER_PAGE_RSP-4231'"
		case DBMSG_NOSQL_ADD_TALK_REQ: value_str = "'DBMSG_NOSQL_ADD_TALK_REQ-4175'"
		case DBMSG_NOSQL_ADD_TALK_RSP: value_str = "'DBMSG_NOSQL_ADD_TALK_RSP-4176'"
		case DBMSG_SYS_ADD_IMAGE_FEATURE_REQ: value_str = "'DBMSG_SYS_ADD_IMAGE_FEATURE_REQ-4190'"
		case DBMSG_SYS_ADD_IMAGE_FEATURE_RSP: value_str = "'DBMSG_SYS_ADD_IMAGE_FEATURE_RSP-4191'"
		case DBMSG_SYS_INQ_IMAGE_FEATURE_REQ: value_str = "'DBMSG_SYS_INQ_IMAGE_FEATURE_REQ-4192'"
		case DBMSG_SYS_INQ_IMAGE_FEATURE_RSP: value_str = "'DBMSG_SYS_INQ_IMAGE_FEATURE_RSP-4193'"
		case DBMSG_HYBRID_ADD_LIST_REQ: value_str = "'DBMSG_HYBRID_ADD_LIST_REQ-4077'"
		case DBMSG_HYBRID_ADD_LIST_RSP: value_str = "'DBMSG_HYBRID_ADD_LIST_RSP-4078'"
		case DBMSG_HYBRID_INQ_LIST_REQ: value_str = "'DBMSG_HYBRID_INQ_LIST_REQ-4079'"
		case DBMSG_HYBRID_INQ_LIST_RSP: value_str = "'DBMSG_HYBRID_INQ_LIST_RSP-4080'"
		case MAINMSG_IM_USER_REG_REQ: value_str = "'MAINMSG_IM_USER_REG_REQ-5034'"
		case MAINMSG_IM_USER_REG_RSP: value_str = "'MAINMSG_IM_USER_REG_RSP-5035'"
		case MAINMSG_IM_USER_DEREG_REQ: value_str = "'MAINMSG_IM_USER_DEREG_REQ-5036'"
		case MAINMSG_IM_USER_DEREG_RSP: value_str = "'MAINMSG_IM_USER_DEREG_RSP-5037'"
		case MAINMSG_IM_USER_INQ_REQ: value_str = "'MAINMSG_IM_USER_INQ_REQ-5038'"
		case MAINMSG_IM_USER_INQ_RSP: value_str = "'MAINMSG_IM_USER_INQ_RSP-5039'"
		case MAINMSG_ADD_CHANNEL_REQ: value_str = "'MAINMSG_ADD_CHANNEL_REQ-5013'"
		case MAINMSG_ADD_CHANNEL_RSP: value_str = "'MAINMSG_ADD_CHANNEL_RSP-5014'"
		case MAINMSG_DEL_CHANNEL_REQ: value_str = "'MAINMSG_DEL_CHANNEL_REQ-5015'"
		case MAINMSG_DEL_CHANNEL_RSP: value_str = "'MAINMSG_DEL_CHANNEL_RSP-5016'"
		case MAINMSG_INQ_CHANNEL_REQ: value_str = "'MAINMSG_INQ_CHANNEL_REQ-5017'"
		case MAINMSG_INQ_CHANNEL_RSP: value_str = "'MAINMSG_INQ_CHANNEL_RSP-5018'"
		case MAINMSG_REC_CHANNEL_REQ: value_str = "'MAINMSG_REC_CHANNEL_REQ-5019'"
		case MAINMSG_REC_CHANNEL_RSP: value_str = "'MAINMSG_REC_CHANNEL_RSP-5020'"
		case MAINMSG_ADD_CHANNEL_CMD_REQ: value_str = "'MAINMSG_ADD_CHANNEL_CMD_REQ-5040'"
		case MAINMSG_ADD_CHANNEL_CMD_RSP: value_str = "'MAINMSG_ADD_CHANNEL_CMD_RSP-5041'"
		case MAINMSG_DEL_CHANNEL_CMD_REQ: value_str = "'MAINMSG_DEL_CHANNEL_CMD_REQ-5042'"
		case MAINMSG_DEL_CHANNEL_CMD_RSP: value_str = "'MAINMSG_DEL_CHANNEL_CMD_RSP-5043'"
		case MAINMSG_INQ_CHANNEL_CMD_REQ: value_str = "'MAINMSG_INQ_CHANNEL_CMD_REQ-5044'"
		case MAINMSG_INQ_CHANNEL_CMD_RSP: value_str = "'MAINMSG_INQ_CHANNEL_CMD_RSP-5045'"
		case MAINMSG_ADD_CHANNEL_FORBIDDEN_CMD_REQ: value_str = "'MAINMSG_ADD_CHANNEL_FORBIDDEN_CMD_REQ-5129'"
		case MAINMSG_ADD_CHANNEL_FORBIDDEN_CMD_RSP: value_str = "'MAINMSG_ADD_CHANNEL_FORBIDDEN_CMD_RSP-5130'"
		case MAINMSG_DEL_CHANNEL_FORBIDDEN_CMD_REQ: value_str = "'MAINMSG_DEL_CHANNEL_FORBIDDEN_CMD_REQ-5131'"
		case MAINMSG_DEL_CHANNEL_FORBIDDEN_CMD_RSP: value_str = "'MAINMSG_DEL_CHANNEL_FORBIDDEN_CMD_RSP-5132'"
		case MAINMSG_INQ_CHANNEL_FORBIDDEN_CMD_REQ: value_str = "'MAINMSG_INQ_CHANNEL_FORBIDDEN_CMD_REQ-5133'"
		case MAINMSG_TALK_MCARD_REQ: value_str = "'MAINMSG_TALK_MCARD_REQ-5106'"
		case MAINMSG_TALK_MCARD_RSP: value_str = "'MAINMSG_TALK_MCARD_RSP-5107'"
		case MAINMSG_PYTHON_REQ: value_str = "'MAINMSG_PYTHON_REQ-5135'"
		case MAINMSG_PYTHON_RSP: value_str = "'MAINMSG_PYTHON_RSP-5136'"
		case RTC_TRANSLATION_START_REQ: value_str = "'RTC_TRANSLATION_START_REQ-6001'"
		case RTC_TRANSLATION_START_RSP: value_str = "'RTC_TRANSLATION_START_RSP-6002'"
		case RTC_TRANSLATION_STOP_REQ: value_str = "'RTC_TRANSLATION_STOP_REQ-6003'"
		case RTC_TRANSLATION_STOP_RSP: value_str = "'RTC_TRANSLATION_STOP_RSP-6004'"
		case RTC_TRANSLATION_DATA_REQ: value_str = "'RTC_TRANSLATION_DATA_REQ-6005'"
		case RTC_TRANSLATION_DATA_RSP: value_str = "'RTC_TRANSLATION_DATA_RSP-6006'"
		case CVMSG_IMAGE_SEARCH_REQ: value_str = "'CVMSG_IMAGE_SEARCH_REQ-10001'"
		case CVMSG_IMAGE_SEARCH_RSP: value_str = "'CVMSG_IMAGE_SEARCH_RSP-10002'"
		case CVMSG_FEATURES_DETECTED_REQ: value_str = "'CVMSG_FEATURES_DETECTED_REQ-10003'"
		case CVMSG_FEATURES_DETECTED_RSP: value_str = "'CVMSG_FEATURES_DETECTED_RSP-10004'"
		case CVMSG_PAINTING_AESTHETICS_REQ: value_str = "'CVMSG_PAINTING_AESTHETICS_REQ-10005'"
		case CVMSG_PAINTING_AESTHETICS_RSP: value_str = "'CVMSG_PAINTING_AESTHETICS_RSP-10006'"
		case CVMSG_SCULPTURES_SEARCH_REQ: value_str = "'CVMSG_SCULPTURES_SEARCH_REQ-10007'"
		case CVMSG_SCULPTURES_SEARCH_RSP: value_str = "'CVMSG_SCULPTURES_SEARCH_RSP-10008'"
		case HTTPMSG_POST_REQ: value_str = "'HTTPMSG_POST_REQ-11000'"
		case HTTPMSG_POST_RSP: value_str = "'HTTPMSG_POST_RSP-11001'"
		case HTTPMSG_LISTEN_REQ: value_str = "'HTTPMSG_LISTEN_REQ-11002'"
		case HTTPMSG_LISTEN_RSP: value_str = "'HTTPMSG_LISTEN_RSP-11003'"
		case HTTPMSG_CLOSE_REQ: value_str = "'HTTPMSG_CLOSE_REQ-11004'"
		case HTTPMSG_CLOSE_RSP: value_str = "'HTTPMSG_CLOSE_RSP-11005'"
		case HTTPMSG_RECV_REQ: value_str = "'HTTPMSG_RECV_REQ-11006'"
		case HTTPMSG_RECV_RSP: value_str = "'HTTPMSG_RECV_RSP-11007'"
		case HTTPMSG_LISTEN_AUTO_CLOSE_REQ: value_str = "'HTTPMSG_LISTEN_AUTO_CLOSE_REQ-11008'"
		case HTTPMSG_LISTEN_AUTO_CLOSE_RSP: value_str = "'HTTPMSG_LISTEN_AUTO_CLOSE_RSP-11009'"
		case AIXMSG_IMAGE_CLASSIFICATION_REQ: value_str = "'AIXMSG_IMAGE_CLASSIFICATION_REQ-12001'"
		case AIXMSG_IMAGE_CLASSIFICATION_RSP: value_str = "'AIXMSG_IMAGE_CLASSIFICATION_RSP-12002'"
		case AIXMSG_AESTHETICS_REQ: value_str = "'AIXMSG_AESTHETICS_REQ-12003'"
		case AIXMSG_AESTHETICS_RSP: value_str = "'AIXMSG_AESTHETICS_RSP-12004'"
		case BBSMSG_ADD_COMMENT_REQ: value_str = "'BBSMSG_ADD_COMMENT_REQ-15001'"
		case BBSMSG_ADD_COMMENT_RSP: value_str = "'BBSMSG_ADD_COMMENT_RSP-15002'"
		case BBSMSG_INQ_COMMENT_REQ: value_str = "'BBSMSG_INQ_COMMENT_REQ-15003'"
		case BBSMSG_INQ_COMMENT_RSP: value_str = "'BBSMSG_INQ_COMMENT_RSP-15004'"
		case MSGID_INVALID: value_str = "'MSGID_INVALID-0x1fffffffffffffff'"
		default: value_str = fmt.Sprintf("'%v'", enum_value)
	}

	return value_str
}

