package auto
/*
 * Copyright (c) 2022 Renwei
 *
 * This is a free software; you can redistribute it and/or modify
 * it under the terms of the MIT license. See LICENSE for details.
 *
 * ############################# IMPORTANT INFORMATION ############################
 * The code of this file is automatically generated by tools(Tools/auto_code),
 * please do not modify it manually!
 * ############################# IMPORTANT INFORMATION ############################
 * ================================================================================
 */

const DAVE_AUTH_KEY_LEN = 64
const DAVE_BUILDING_BLOCKS_MAX = 255
const DAVE_COMMENT_MCARD_ARRAY_MAX = 16
const DAVE_DBA_PAGE_MAX = 32
const DAVE_DOMAIN_LEN = 128
const DAVE_E164_NUMBER_LEN = 32
const DAVE_GLOBALLY_IDENTIFIER_LEN = 33
const DAVE_HTTP_HEAD_MAX = 16
const DAVE_HTTP_KEY_LEN = 128
const DAVE_HTTP_VALUE_LEN = 512
const DAVE_IMAGE_TITLE_LEN = 256
const DAVE_KEY_LEN_MAX = 128
const DAVE_KEY_OPT_MAX = 32
const DAVE_LABEL_EXTRA_INFO_MAX = 128
const DAVE_LABEL_STR_MAX = 256
const DAVE_MACRD_HEAD_MAX = 4096
const DAVE_NORMAL_NAME_LEN = 128
const DAVE_NOSQL_KEY_STR_MAX = 64
const DAVE_PASSWORD_LEN = 64
const DAVE_PATH_LEN = 256
const DAVE_POI_ADDRESS_MAX = 256
const DAVE_POI_NAME_MAX = 128
const DAVE_SHA1_HASH_LEN = 20
const DAVE_SMS_String_LEN_128 = 128
const DAVE_TENANT_NAME_LEN = 128
const DAVE_THREAD_NAME_LEN = 32
const DAVE_UIP_CMD_STR_LEN = 2048
const DAVE_UIP_METHOD_MAX_LEN = 64
const DAVE_UIP_METHOD_MAX_NUM = 256
const DAVE_URL_LEN = 128
const DAVE_USER_NAME_LEN = 128
const DAVE_UUID_LEN = 64
const DAVE_VERNO_STR_LEN = 64
const DAVE_VGG_FEATURE_LEN = 1024
const DAVE_AUTH_KEY_STR_LEN = DAVE_AUTH_KEY_LEN*2+1
const DAVE_MSISDN_LEN = DAVE_E164_NUMBER_LEN
const DAVE_SHA1_IMAGE_ID = DAVE_SHA1_HASH_LEN*3+1
