#/*
# * Copyright (c) 2023 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# *
# * ############################# IMPORTANT INFORMATION ############################
# * The code of this file is automatically generated by tools(Tools/auto_code),
# * please do not modify it manually!
# * ############################# IMPORTANT INFORMATION ############################
# * ================================================================================
# */

from .dave_enum import *
from .dave_msg_id import *

def t_auto_AIPlaceType_str(enum_value):
	if enum_value == AIPlaceType_accounting:
		value_str = "'AIPlaceType_accounting'"
	elif enum_value == AIPlaceType_airport:
		value_str = "'AIPlaceType_airport'"
	elif enum_value == AIPlaceType_amusement_park:
		value_str = "'AIPlaceType_amusement_park'"
	elif enum_value == AIPlaceType_aquarium:
		value_str = "'AIPlaceType_aquarium'"
	elif enum_value == AIPlaceType_art_gallery:
		value_str = "'AIPlaceType_art_gallery'"
	elif enum_value == AIPlaceType_atm:
		value_str = "'AIPlaceType_atm'"
	elif enum_value == AIPlaceType_bakery:
		value_str = "'AIPlaceType_bakery'"
	elif enum_value == AIPlaceType_bank:
		value_str = "'AIPlaceType_bank'"
	elif enum_value == AIPlaceType_bar:
		value_str = "'AIPlaceType_bar'"
	elif enum_value == AIPlaceType_beauty_salon:
		value_str = "'AIPlaceType_beauty_salon'"
	elif enum_value == AIPlaceType_bicycle_store:
		value_str = "'AIPlaceType_bicycle_store'"
	elif enum_value == AIPlaceType_book_store:
		value_str = "'AIPlaceType_book_store'"
	elif enum_value == AIPlaceType_bowling_alley:
		value_str = "'AIPlaceType_bowling_alley'"
	elif enum_value == AIPlaceType_bus_station:
		value_str = "'AIPlaceType_bus_station'"
	elif enum_value == AIPlaceType_cafe:
		value_str = "'AIPlaceType_cafe'"
	elif enum_value == AIPlaceType_campground:
		value_str = "'AIPlaceType_campground'"
	elif enum_value == AIPlaceType_car_dealer:
		value_str = "'AIPlaceType_car_dealer'"
	elif enum_value == AIPlaceType_car_rental:
		value_str = "'AIPlaceType_car_rental'"
	elif enum_value == AIPlaceType_car_repair:
		value_str = "'AIPlaceType_car_repair'"
	elif enum_value == AIPlaceType_car_wash:
		value_str = "'AIPlaceType_car_wash'"
	elif enum_value == AIPlaceType_casino:
		value_str = "'AIPlaceType_casino'"
	elif enum_value == AIPlaceType_cemetery:
		value_str = "'AIPlaceType_cemetery'"
	elif enum_value == AIPlaceType_church:
		value_str = "'AIPlaceType_church'"
	elif enum_value == AIPlaceType_city_hall:
		value_str = "'AIPlaceType_city_hall'"
	elif enum_value == AIPlaceType_clothing_store:
		value_str = "'AIPlaceType_clothing_store'"
	elif enum_value == AIPlaceType_convenience_store:
		value_str = "'AIPlaceType_convenience_store'"
	elif enum_value == AIPlaceType_courthouse:
		value_str = "'AIPlaceType_courthouse'"
	elif enum_value == AIPlaceType_dentist:
		value_str = "'AIPlaceType_dentist'"
	elif enum_value == AIPlaceType_department_store:
		value_str = "'AIPlaceType_department_store'"
	elif enum_value == AIPlaceType_doctor:
		value_str = "'AIPlaceType_doctor'"
	elif enum_value == AIPlaceType_electrician:
		value_str = "'AIPlaceType_electrician'"
	elif enum_value == AIPlaceType_electronics_store:
		value_str = "'AIPlaceType_electronics_store'"
	elif enum_value == AIPlaceType_embassy:
		value_str = "'AIPlaceType_embassy'"
	elif enum_value == AIPlaceType_fire_station:
		value_str = "'AIPlaceType_fire_station'"
	elif enum_value == AIPlaceType_florist:
		value_str = "'AIPlaceType_florist'"
	elif enum_value == AIPlaceType_funeral_home:
		value_str = "'AIPlaceType_funeral_home'"
	elif enum_value == AIPlaceType_furniture_store:
		value_str = "'AIPlaceType_furniture_store'"
	elif enum_value == AIPlaceType_gas_station:
		value_str = "'AIPlaceType_gas_station'"
	elif enum_value == AIPlaceType_gym:
		value_str = "'AIPlaceType_gym'"
	elif enum_value == AIPlaceType_hair_care:
		value_str = "'AIPlaceType_hair_care'"
	elif enum_value == AIPlaceType_hardware_store:
		value_str = "'AIPlaceType_hardware_store'"
	elif enum_value == AIPlaceType_hindu_temple:
		value_str = "'AIPlaceType_hindu_temple'"
	elif enum_value == AIPlaceType_home_goods_store:
		value_str = "'AIPlaceType_home_goods_store'"
	elif enum_value == AIPlaceType_hospital:
		value_str = "'AIPlaceType_hospital'"
	elif enum_value == AIPlaceType_insurance_agency:
		value_str = "'AIPlaceType_insurance_agency'"
	elif enum_value == AIPlaceType_jewelry_store:
		value_str = "'AIPlaceType_jewelry_store'"
	elif enum_value == AIPlaceType_laundry:
		value_str = "'AIPlaceType_laundry'"
	elif enum_value == AIPlaceType_lawyer:
		value_str = "'AIPlaceType_lawyer'"
	elif enum_value == AIPlaceType_library:
		value_str = "'AIPlaceType_library'"
	elif enum_value == AIPlaceType_liquor_store:
		value_str = "'AIPlaceType_liquor_store'"
	elif enum_value == AIPlaceType_local_government_office:
		value_str = "'AIPlaceType_local_government_office'"
	elif enum_value == AIPlaceType_locksmith:
		value_str = "'AIPlaceType_locksmith'"
	elif enum_value == AIPlaceType_lodging:
		value_str = "'AIPlaceType_lodging'"
	elif enum_value == AIPlaceType_meal_delivery:
		value_str = "'AIPlaceType_meal_delivery'"
	elif enum_value == AIPlaceType_meal_takeaway:
		value_str = "'AIPlaceType_meal_takeaway'"
	elif enum_value == AIPlaceType_mosque:
		value_str = "'AIPlaceType_mosque'"
	elif enum_value == AIPlaceType_movie_rental:
		value_str = "'AIPlaceType_movie_rental'"
	elif enum_value == AIPlaceType_movie_theater:
		value_str = "'AIPlaceType_movie_theater'"
	elif enum_value == AIPlaceType_moving_company:
		value_str = "'AIPlaceType_moving_company'"
	elif enum_value == AIPlaceType_museum:
		value_str = "'AIPlaceType_museum'"
	elif enum_value == AIPlaceType_night_club:
		value_str = "'AIPlaceType_night_club'"
	elif enum_value == AIPlaceType_painter:
		value_str = "'AIPlaceType_painter'"
	elif enum_value == AIPlaceType_park:
		value_str = "'AIPlaceType_park'"
	elif enum_value == AIPlaceType_parking:
		value_str = "'AIPlaceType_parking'"
	elif enum_value == AIPlaceType_pet_store:
		value_str = "'AIPlaceType_pet_store'"
	elif enum_value == AIPlaceType_pharmacy:
		value_str = "'AIPlaceType_pharmacy'"
	elif enum_value == AIPlaceType_physiotherapist:
		value_str = "'AIPlaceType_physiotherapist'"
	elif enum_value == AIPlaceType_plumber:
		value_str = "'AIPlaceType_plumber'"
	elif enum_value == AIPlaceType_police:
		value_str = "'AIPlaceType_police'"
	elif enum_value == AIPlaceType_post_office:
		value_str = "'AIPlaceType_post_office'"
	elif enum_value == AIPlaceType_real_estate_agency:
		value_str = "'AIPlaceType_real_estate_agency'"
	elif enum_value == AIPlaceType_restaurant:
		value_str = "'AIPlaceType_restaurant'"
	elif enum_value == AIPlaceType_roofing_contractor:
		value_str = "'AIPlaceType_roofing_contractor'"
	elif enum_value == AIPlaceType_rv_park:
		value_str = "'AIPlaceType_rv_park'"
	elif enum_value == AIPlaceType_school:
		value_str = "'AIPlaceType_school'"
	elif enum_value == AIPlaceType_shoe_store:
		value_str = "'AIPlaceType_shoe_store'"
	elif enum_value == AIPlaceType_shopping_mall:
		value_str = "'AIPlaceType_shopping_mall'"
	elif enum_value == AIPlaceType_spa:
		value_str = "'AIPlaceType_spa'"
	elif enum_value == AIPlaceType_stadium:
		value_str = "'AIPlaceType_stadium'"
	elif enum_value == AIPlaceType_storage:
		value_str = "'AIPlaceType_storage'"
	elif enum_value == AIPlaceType_store:
		value_str = "'AIPlaceType_store'"
	elif enum_value == AIPlaceType_subway_station:
		value_str = "'AIPlaceType_subway_station'"
	elif enum_value == AIPlaceType_synagogue:
		value_str = "'AIPlaceType_synagogue'"
	elif enum_value == AIPlaceType_taxi_stand:
		value_str = "'AIPlaceType_taxi_stand'"
	elif enum_value == AIPlaceType_train_station:
		value_str = "'AIPlaceType_train_station'"
	elif enum_value == AIPlaceType_transit_station:
		value_str = "'AIPlaceType_transit_station'"
	elif enum_value == AIPlaceType_travel_agency:
		value_str = "'AIPlaceType_travel_agency'"
	elif enum_value == AIPlaceType_university:
		value_str = "'AIPlaceType_university'"
	elif enum_value == AIPlaceType_veterinary_care:
		value_str = "'AIPlaceType_veterinary_care'"
	elif enum_value == AIPlaceType_zoo:
		value_str = "'AIPlaceType_zoo'"
	elif enum_value == AIPlaceType_max:
		value_str = "'AIPlaceType_max-0x1fffffffffffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_BuildingBlocksOpt_str(enum_value):
	if enum_value == BuildingBlocksOpt_none:
		value_str = "'BuildingBlocksOpt_none'"
	elif enum_value == BuildingBlocksOpt_inq:
		value_str = "'BuildingBlocksOpt_inq'"
	elif enum_value == BuildingBlocksOpt_mount:
		value_str = "'BuildingBlocksOpt_mount'"
	elif enum_value == BuildingBlocksOpt_decoupling:
		value_str = "'BuildingBlocksOpt_decoupling'"
	elif enum_value == BuildingBlocksOpt_State_exchange:
		value_str = "'BuildingBlocksOpt_State_exchange'"
	elif enum_value == BuildingBlocksOpt_valve:
		value_str = "'BuildingBlocksOpt_valve'"
	elif enum_value == BuildingBlocksOpt_max:
		value_str = "'BuildingBlocksOpt_max'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_CVSearchOpt_str(enum_value):
	if enum_value == CVSearchOpt_0:
		value_str = "'CVSearchOpt_0'"
	elif enum_value == CVSearchOpt_1:
		value_str = "'CVSearchOpt_1'"
	elif enum_value == CVSearchOpt_2:
		value_str = "'CVSearchOpt_2'"
	elif enum_value == CVSearchOpt_max:
		value_str = "'CVSearchOpt_max'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_EnableKeepAliveFlag_str(enum_value):
	if enum_value == KeepAlive_enable:
		value_str = "'KeepAlive_enable-0x01234567'"
	elif enum_value == KeepAlive_disable:
		value_str = "'KeepAlive_disable-0x09abcdef'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_EnableNetCardBindFlag_str(enum_value):
	if enum_value == NetCardBind_enable:
		value_str = "'NetCardBind_enable-0x01234567'"
	elif enum_value == NetCardBind_disable:
		value_str = "'NetCardBind_disable-0x09abcdef'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_ErrCode_str(enum_value):
	if enum_value == ERRCODE_OK:
		value_str = "'ERRCODE_OK-0'"
	elif enum_value == ERRCODE_Memory_full:
		value_str = "'ERRCODE_Memory_full--1'"
	elif enum_value == ERRCODE_Limited_resources:
		value_str = "'ERRCODE_Limited_resources--2'"
	elif enum_value == ERRCODE_Arithmetic_error:
		value_str = "'ERRCODE_Arithmetic_error--3'"
	elif enum_value == ERRCODE_Unknown_error:
		value_str = "'ERRCODE_Unknown_error--4'"
	elif enum_value == ERRCODE_Can_not_find_node:
		value_str = "'ERRCODE_Can_not_find_node--5'"
	elif enum_value == ERRCODE_Send_failed:
		value_str = "'ERRCODE_Send_failed--6'"
	elif enum_value == ERRCODE_Recv_failed:
		value_str = "'ERRCODE_Recv_failed--7'"
	elif enum_value == ERRCODE_Invalid_data:
		value_str = "'ERRCODE_Invalid_data--8'"
	elif enum_value == ERRCODE_Unsupported_type:
		value_str = "'ERRCODE_Unsupported_type--9'"
	elif enum_value == ERRCODE_Invalid_user_name:
		value_str = "'ERRCODE_Invalid_user_name--10'"
	elif enum_value == ERRCODE_Parameter_conflicts:
		value_str = "'ERRCODE_Parameter_conflicts--11'"
	elif enum_value == ERRCODE_Invalid_device:
		value_str = "'ERRCODE_Invalid_device--12'"
	elif enum_value == ERRCODE_Invalid_Event:
		value_str = "'ERRCODE_Invalid_Event--13'"
	elif enum_value == ERRCODE_Heartbeat_timeout:
		value_str = "'ERRCODE_Heartbeat_timeout--14'"
	elif enum_value == ERRCODE_Invalid_password:
		value_str = "'ERRCODE_Invalid_password--15'"
	elif enum_value == ERRCODE_save_failed:
		value_str = "'ERRCODE_save_failed--16'"
	elif enum_value == ERRCODE_Invalid_data_too_short:
		value_str = "'ERRCODE_Invalid_data_too_short--17'"
	elif enum_value == ERRCODE_Invalid_data_too_long:
		value_str = "'ERRCODE_Invalid_data_too_long--18'"
	elif enum_value == ERRCODE_Invalid_data_crc_check:
		value_str = "'ERRCODE_Invalid_data_crc_check--19'"
	elif enum_value == ERRCODE_Invalid_parameter:
		value_str = "'ERRCODE_Invalid_parameter--20'"
	elif enum_value == ERRCODE_Send_msg_failed:
		value_str = "'ERRCODE_Send_msg_failed--21'"
	elif enum_value == ERRCODE_Resource_conflicts:
		value_str = "'ERRCODE_Resource_conflicts--22'"
	elif enum_value == ERRCODE_CREDIT_LIMIT_REACHED:
		value_str = "'ERRCODE_CREDIT_LIMIT_REACHED--23'"
	elif enum_value == ERRCODE_Exceeded_number:
		value_str = "'ERRCODE_Exceeded_number--24'"
	elif enum_value == ERRCODE_do_not_free:
		value_str = "'ERRCODE_do_not_free--25'"
	elif enum_value == ERRCODE_Request_failed:
		value_str = "'ERRCODE_Request_failed--26'"
	elif enum_value == ERRCODE_can_not_find_ret_code:
		value_str = "'ERRCODE_can_not_find_ret_code--27'"
	elif enum_value == ERRCODE_user_is_registered:
		value_str = "'ERRCODE_user_is_registered--28'"
	elif enum_value == ERRCODE_connect_error:
		value_str = "'ERRCODE_connect_error--29'"
	elif enum_value == ERRCODE_function_not_supported:
		value_str = "'ERRCODE_function_not_supported--30'"
	elif enum_value == ERRCODE_msg_queue_is_full:
		value_str = "'ERRCODE_msg_queue_is_full--31'"
	elif enum_value == ERRCODE_msg_can_not_resend_wakeup:
		value_str = "'ERRCODE_msg_can_not_resend_wakeup--32'"
	elif enum_value == ERRCODE_msg_memory_if_full:
		value_str = "'ERRCODE_msg_memory_if_full--33'"
	elif enum_value == ERRCODE_msg_competition_for_resources:
		value_str = "'ERRCODE_msg_competition_for_resources--34'"
	elif enum_value == ERRCODE_wait:
		value_str = "'ERRCODE_wait--35'"
	elif enum_value == ERRCODE_Invalid_state:
		value_str = "'ERRCODE_Invalid_state--36'"
	elif enum_value == ERRCODE_usr_default:
		value_str = "'ERRCODE_usr_default--37'"
	elif enum_value == ERRCODE_timer_out:
		value_str = "'ERRCODE_timer_out--38'"
	elif enum_value == ERRCODE_invalid_type:
		value_str = "'ERRCODE_invalid_type--39'"
	elif enum_value == ERRCODE_user_does_not_exist:
		value_str = "'ERRCODE_user_does_not_exist--40'"
	elif enum_value == ERRCODE_version_new:
		value_str = "'ERRCODE_version_new--41'"
	elif enum_value == ERRCODE_version_old:
		value_str = "'ERRCODE_version_old--42'"
	elif enum_value == ERRCODE_ptr_null:
		value_str = "'ERRCODE_ptr_null--43'"
	elif enum_value == ERRCODE_record_not_exist:
		value_str = "'ERRCODE_record_not_exist--44'"
	elif enum_value == ERRCODE_db_store_failed:
		value_str = "'ERRCODE_db_store_failed--45'"
	elif enum_value == ERRCODE_db_not_find:
		value_str = "'ERRCODE_db_not_find--46'"
	elif enum_value == ERRCODE_Invalid_channel_name:
		value_str = "'ERRCODE_Invalid_channel_name--47'"
	elif enum_value == ERRCODE_Invalid_db_store:
		value_str = "'ERRCODE_Invalid_db_store--48'"
	elif enum_value == ERRCODE_version_mismatch:
		value_str = "'ERRCODE_version_mismatch--49'"
	elif enum_value == ERRCODE_invalid_version_file:
		value_str = "'ERRCODE_invalid_version_file--50'"
	elif enum_value == ERRCODE_version_identical:
		value_str = "'ERRCODE_version_identical--51'"
	elif enum_value == ERRCODE_db_sql_failed:
		value_str = "'ERRCODE_db_sql_failed--52'"
	elif enum_value == ERRCODE_invalid_option:
		value_str = "'ERRCODE_invalid_option--53'"
	elif enum_value == ERRCODE_Invalid_domain:
		value_str = "'ERRCODE_Invalid_domain--54'"
	elif enum_value == ERRCODE_Invalid_auth_key:
		value_str = "'ERRCODE_Invalid_auth_key--55'"
	elif enum_value == ERRCODE_invalid_key:
		value_str = "'ERRCODE_invalid_key--56'"
	elif enum_value == ERRCODE_no_account_found:
		value_str = "'ERRCODE_no_account_found--57'"
	elif enum_value == ERRCODE_invalid_phone_number:
		value_str = "'ERRCODE_invalid_phone_number--58'"
	elif enum_value == ERRCODE_not_match_domain:
		value_str = "'ERRCODE_not_match_domain--59'"
	elif enum_value == ERRCODE_invalid_account:
		value_str = "'ERRCODE_invalid_account--60'"
	elif enum_value == ERRCODE_please_help_free:
		value_str = "'ERRCODE_please_help_free--61'"
	elif enum_value == ERRCODE_db_init_failed:
		value_str = "'ERRCODE_db_init_failed--62'"
	elif enum_value == ERRCODE_update_fail:
		value_str = "'ERRCODE_update_fail--63'"
	elif enum_value == ERRCODE_maybe_have_data:
		value_str = "'ERRCODE_maybe_have_data--64'"
	elif enum_value == ERRCODE_do_not_restart:
		value_str = "'ERRCODE_do_not_restart--65'"
	elif enum_value == ERRCODE_lost_auth_key:
		value_str = "'ERRCODE_lost_auth_key--66'"
	elif enum_value == ERRCODE_lost_serial:
		value_str = "'ERRCODE_lost_serial--67'"
	elif enum_value == ERRCODE_lost_time:
		value_str = "'ERRCODE_lost_time--68'"
	elif enum_value == ERRCODE_lost_uuid:
		value_str = "'ERRCODE_lost_uuid--69'"
	elif enum_value == ERRCODE_lost_user:
		value_str = "'ERRCODE_lost_user--70'"
	elif enum_value == ERRCODE_can_not_find_record:
		value_str = "'ERRCODE_can_not_find_record--71'"
	elif enum_value == ERRCODE_lost_dial_number:
		value_str = "'ERRCODE_lost_dial_number--72'"
	elif enum_value == ERRCODE_call_prohibition:
		value_str = "'ERRCODE_call_prohibition--73'"
	elif enum_value == ERRCODE_lost_link:
		value_str = "'ERRCODE_lost_link--74'"
	elif enum_value == ERRCODE_record_not_found:
		value_str = "'ERRCODE_record_not_found--75'"
	elif enum_value == ERRCODE_ims_account_incorrect:
		value_str = "'ERRCODE_ims_account_incorrect--76'"
	elif enum_value == ERRCODE_invalid_dial_number:
		value_str = "'ERRCODE_invalid_dial_number--77'"
	elif enum_value == ERRCODE_Invalid_balance:
		value_str = "'ERRCODE_Invalid_balance--78'"
	elif enum_value == ERRCODE_user_exist:
		value_str = "'ERRCODE_user_exist--79'"
	elif enum_value == ERRCODE_store_data_failed:
		value_str = "'ERRCODE_store_data_failed--80'"
	elif enum_value == ERRCODE_Invalid_user_type:
		value_str = "'ERRCODE_Invalid_user_type--81'"
	elif enum_value == ERRCODE_invalid_user:
		value_str = "'ERRCODE_invalid_user--82'"
	elif enum_value == ERRCODE_unsupport:
		value_str = "'ERRCODE_unsupport--83'"
	elif enum_value == ERRCODE_unpackage_failed:
		value_str = "'ERRCODE_unpackage_failed--84'"
	elif enum_value == ERRCODE_creat_db_failed:
		value_str = "'ERRCODE_creat_db_failed--85'"
	elif enum_value == ERRCODE_Invalid_channel:
		value_str = "'ERRCODE_Invalid_channel--86'"
	elif enum_value == ERRCODE_heartbeat_timer_out:
		value_str = "'ERRCODE_heartbeat_timer_out--87'"
	elif enum_value == ERRCODE_Invalid_package:
		value_str = "'ERRCODE_Invalid_package--88'"
	elif enum_value == ERRCODE_Invalid_rules:
		value_str = "'ERRCODE_Invalid_rules--89'"
	elif enum_value == ERRCODE_busy:
		value_str = "'ERRCODE_busy--90'"
	elif enum_value == ERRCODE_data_overflow:
		value_str = "'ERRCODE_data_overflow--91'"
	elif enum_value == ERRCODE_invalid_account_name:
		value_str = "'ERRCODE_invalid_account_name--92'"
	elif enum_value == ERRCODE_Account_in_use:
		value_str = "'ERRCODE_Account_in_use--93'"
	elif enum_value == ERRCODE_invalid_address:
		value_str = "'ERRCODE_invalid_address--94'"
	elif enum_value == ERRCODE_can_not_find_rules:
		value_str = "'ERRCODE_can_not_find_rules--95'"
	elif enum_value == ERRCODE_refuse_call_self:
		value_str = "'ERRCODE_refuse_call_self--96'"
	elif enum_value == ERRCODE_Invalid_call:
		value_str = "'ERRCODE_Invalid_call--97'"
	elif enum_value == ERRCODE_mismatch:
		value_str = "'ERRCODE_mismatch--98'"
	elif enum_value == ERRCODE_Invalid_call_type:
		value_str = "'ERRCODE_Invalid_call_type--99'"
	elif enum_value == ERRCODE_Invalid_billing:
		value_str = "'ERRCODE_Invalid_billing--100'"
	elif enum_value == ERRCODE_invalid_magic:
		value_str = "'ERRCODE_invalid_magic--101'"
	elif enum_value == ERRCODE_create_thread_failed:
		value_str = "'ERRCODE_create_thread_failed--102'"
	elif enum_value == ERRCODE_execute_sql_failed:
		value_str = "'ERRCODE_execute_sql_failed--103'"
	elif enum_value == ERRCODE_decode_failed:
		value_str = "'ERRCODE_decode_failed--104'"
	elif enum_value == ERRCODE_encode_failed:
		value_str = "'ERRCODE_encode_failed--105'"
	elif enum_value == ERRCODE_invalid_file:
		value_str = "'ERRCODE_invalid_file--106'"
	elif enum_value == ERRCODE_file_open_failed:
		value_str = "'ERRCODE_file_open_failed--107'"
	elif enum_value == ERRCODE_process_now:
		value_str = "'ERRCODE_process_now--108'"
	elif enum_value == ERRCODE_queue_too_large:
		value_str = "'ERRCODE_queue_too_large--109'"
	elif enum_value == ERRCODE_add_user_name_failed:
		value_str = "'ERRCODE_add_user_name_failed--110'"
	elif enum_value == ERRCODE_call_time_limited:
		value_str = "'ERRCODE_call_time_limited--111'"
	elif enum_value == ERRCODE_invalid_hour:
		value_str = "'ERRCODE_invalid_hour--112'"
	elif enum_value == ERRCODE_invalid_day:
		value_str = "'ERRCODE_invalid_day--113'"
	elif enum_value == ERRCODE_invalid_week:
		value_str = "'ERRCODE_invalid_week--114'"
	elif enum_value == ERRCODE_invalid_month:
		value_str = "'ERRCODE_invalid_month--115'"
	elif enum_value == ERRCODE_invalid_year:
		value_str = "'ERRCODE_invalid_year--116'"
	elif enum_value == ERRCODE_invalid_unit:
		value_str = "'ERRCODE_invalid_unit--117'"
	elif enum_value == ERRCODE_invalid_rules_number:
		value_str = "'ERRCODE_invalid_rules_number--118'"
	elif enum_value == ERRCODE_invalid_package_private:
		value_str = "'ERRCODE_invalid_package_private--119'"
	elif enum_value == ERRCODE_rules_id_mismatch:
		value_str = "'ERRCODE_rules_id_mismatch--120'"
	elif enum_value == ERRCODE_channel_not_exist:
		value_str = "'ERRCODE_channel_not_exist--121'"
	elif enum_value == ERRCODE_invalid_donation_account:
		value_str = "'ERRCODE_invalid_donation_account--122'"
	elif enum_value == ERRCODE_channel_exist:
		value_str = "'ERRCODE_channel_exist--123'"
	elif enum_value == ERRCODE_invalid_date:
		value_str = "'ERRCODE_invalid_date--124'"
	elif enum_value == ERRCODE_not_my_data:
		value_str = "'ERRCODE_not_my_data--125'"
	elif enum_value == ERRCODE_only_share_user_pwd_can_modify:
		value_str = "'ERRCODE_only_share_user_pwd_can_modify--126'"
	elif enum_value == ERRCODE_can_not_find_thread:
		value_str = "'ERRCODE_can_not_find_thread--127'"
	elif enum_value == ERRCODE_lost_register_e164_number:
		value_str = "'ERRCODE_lost_register_e164_number--128'"
	elif enum_value == ERRCODE_lost_modify_impu_flag:
		value_str = "'ERRCODE_lost_modify_impu_flag--129'"
	elif enum_value == ERRCODE_lost_country_code_of_e164_number:
		value_str = "'ERRCODE_lost_country_code_of_e164_number--130'"
	elif enum_value == ERRCODE_lost_sip_password:
		value_str = "'ERRCODE_lost_sip_password--131'"
	elif enum_value == ERRCODE_invalid_modify_impu_flag:
		value_str = "'ERRCODE_invalid_modify_impu_flag--132'"
	elif enum_value == ERRCODE_invalid_country_code_of_e164_number:
		value_str = "'ERRCODE_invalid_country_code_of_e164_number--133'"
	elif enum_value == ERRCODE_invalid_register_e164_number:
		value_str = "'ERRCODE_invalid_register_e164_number--134'"
	elif enum_value == ERRCODE_modify_impu_failed:
		value_str = "'ERRCODE_modify_impu_failed--135'"
	elif enum_value == ERRCODE_impu_not_existed:
		value_str = "'ERRCODE_impu_not_existed--136'"
	elif enum_value == ERRCODE_script_execution_error:
		value_str = "'ERRCODE_script_execution_error--137'"
	elif enum_value == ERRCODE_invalid_share_ram:
		value_str = "'ERRCODE_invalid_share_ram--138'"
	elif enum_value == ERRCODE_Duplicate_MSISDN:
		value_str = "'ERRCODE_Duplicate_MSISDN--139'"
	elif enum_value == ERRCODE_Duplicate_IMSI:
		value_str = "'ERRCODE_Duplicate_IMSI--140'"
	elif enum_value == ERRCODE_Duplicate_VOIP_MSISDN:
		value_str = "'ERRCODE_Duplicate_VOIP_MSISDN--141'"
	elif enum_value == ERRCODE_Not_found:
		value_str = "'ERRCODE_Not_found--142'"
	elif enum_value == ERRCODE_Boot_in_the_territory:
		value_str = "'ERRCODE_Boot_in_the_territory--143'"
	elif enum_value == ERRCODE_Other_errors:
		value_str = "'ERRCODE_Other_errors--144'"
	elif enum_value == ERRCODE_lost_result_code:
		value_str = "'ERRCODE_lost_result_code--145'"
	elif enum_value == ERRCODE_invalid_imsi:
		value_str = "'ERRCODE_invalid_imsi--146'"
	elif enum_value == ERRCODE_invalid_msisdn:
		value_str = "'ERRCODE_invalid_msisdn--147'"
	elif enum_value == ERRCODE_invalid_voip_msisdn:
		value_str = "'ERRCODE_invalid_voip_msisdn--148'"
	elif enum_value == ERRCODE_processing_is_complete:
		value_str = "'ERRCODE_processing_is_complete--149'"
	elif enum_value == ERRCODE_secondary_number_ass_repeated:
		value_str = "'ERRCODE_secondary_number_ass_repeated--150'"
	elif enum_value == ERRCODE_secondary_number_not_available:
		value_str = "'ERRCODE_secondary_number_not_available--151'"
	elif enum_value == ERRCODE_secondary_number_ret_failed:
		value_str = "'ERRCODE_secondary_number_ret_failed--152'"
	elif enum_value == ERRCODE_secondary_number_inquiry_failed:
		value_str = "'ERRCODE_secondary_number_inquiry_failed--153'"
	elif enum_value == ERRCODE_lost_secondary_number:
		value_str = "'ERRCODE_lost_secondary_number--154'"
	elif enum_value == ERRCODE_invalid_e164_number_type:
		value_str = "'ERRCODE_invalid_e164_number_type--155'"
	elif enum_value == ERRCODE_lost_number_request_type:
		value_str = "'ERRCODE_lost_number_request_type--156'"
	elif enum_value == ERRCODE_secondary_number_not_existed:
		value_str = "'ERRCODE_secondary_number_not_existed--157'"
	elif enum_value == ERRCODE_invalid_content:
		value_str = "'ERRCODE_invalid_content--158'"
	elif enum_value == ERRCODE_invalid_email:
		value_str = "'ERRCODE_invalid_email--159'"
	elif enum_value == ERRCODE_repeated_request:
		value_str = "'ERRCODE_repeated_request--160'"
	elif enum_value == ERRCODE_rules_exist:
		value_str = "'ERRCODE_rules_exist--161'"
	elif enum_value == ERRCODE_lack_of_donor:
		value_str = "'ERRCODE_lack_of_donor--162'"
	elif enum_value == ERRCODE_lost_im_user_name:
		value_str = "'ERRCODE_lost_im_user_name--163'"
	elif enum_value == ERRCODE_lost_im_password:
		value_str = "'ERRCODE_lost_im_password--164'"
	elif enum_value == ERRCODE_invalid_im_nickname:
		value_str = "'ERRCODE_invalid_im_nickname--165'"
	elif enum_value == ERRCODE_im_user_dereg_failed:
		value_str = "'ERRCODE_im_user_dereg_failed--166'"
	elif enum_value == ERRCODE_im_user_not_existed:
		value_str = "'ERRCODE_im_user_not_existed--167'"
	elif enum_value == ERRCODE_im_user_reg_failed:
		value_str = "'ERRCODE_im_user_reg_failed--168'"
	elif enum_value == ERRCODE_invalid_im_user_name:
		value_str = "'ERRCODE_invalid_im_user_name--169'"
	elif enum_value == ERRCODE_invalid_im_password:
		value_str = "'ERRCODE_invalid_im_password--170'"
	elif enum_value == ERRCODE_lost_imsi:
		value_str = "'ERRCODE_lost_imsi--171'"
	elif enum_value == ERRCODE_lost_binding_status:
		value_str = "'ERRCODE_lost_binding_status--172'"
	elif enum_value == ERRCODE_invalid_binding_status:
		value_str = "'ERRCODE_invalid_binding_status--173'"
	elif enum_value == ERRCODE_package_exist:
		value_str = "'ERRCODE_package_exist--174'"
	elif enum_value == ERRCODE_invalid_billing_user_data:
		value_str = "'ERRCODE_invalid_billing_user_data--175'"
	elif enum_value == ERRCODE_Failure_to_activate_validity:
		value_str = "'ERRCODE_Failure_to_activate_validity--176'"
	elif enum_value == ERRCODE_Time_lapse:
		value_str = "'ERRCODE_Time_lapse--177'"
	elif enum_value == ERRCODE_Billing_reached_the_limit:
		value_str = "'ERRCODE_Billing_reached_the_limit--178'"
	elif enum_value == ERRCODE_invalid_recharge:
		value_str = "'ERRCODE_invalid_recharge--179'"
	elif enum_value == ERRCODE_Date_expired:
		value_str = "'ERRCODE_Date_expired--180'"
	elif enum_value == ERRCODE_lost_package_info:
		value_str = "'ERRCODE_lost_package_info--181'"
	elif enum_value == ERRCODE_not_access:
		value_str = "'ERRCODE_not_access--182'"
	elif enum_value == ERRCODE_invalid_minute:
		value_str = "'ERRCODE_invalid_minute--183'"
	elif enum_value == ERRCODE_invalid_second:
		value_str = "'ERRCODE_invalid_second--184'"
	elif enum_value == ERRCODE_not_do_anything:
		value_str = "'ERRCODE_not_do_anything--185'"
	elif enum_value == ERRCODE_empty_data:
		value_str = "'ERRCODE_empty_data--186'"
	elif enum_value == ERRCODE_not_group_rules:
		value_str = "'ERRCODE_not_group_rules--187'"
	elif enum_value == ERRCODE_on_billing_operation_not_allowed:
		value_str = "'ERRCODE_on_billing_operation_not_allowed--188'"
	elif enum_value == ERRCODE_roaming_not_allowed:
		value_str = "'ERRCODE_roaming_not_allowed--189'"
	elif enum_value == ERRCODE_invalid_mcard:
		value_str = "'ERRCODE_invalid_mcard--190'"
	elif enum_value == ERRCODE_Too_many_packages:
		value_str = "'ERRCODE_Too_many_packages--191'"
	elif enum_value == ERRCODE_Too_many_rules:
		value_str = "'ERRCODE_Too_many_rules--192'"
	elif enum_value == ERRCODE_can_not_find_mcard:
		value_str = "'ERRCODE_can_not_find_mcard--193'"
	elif enum_value == ERRCODE_Failure_to_be_deactived:
		value_str = "'ERRCODE_Failure_to_be_deactived--194'"
	elif enum_value == ERRCODE_operating_end:
		value_str = "'ERRCODE_operating_end--195'"
	elif enum_value == ERRCODE_invalid_voip_setting:
		value_str = "'ERRCODE_invalid_voip_setting--196'"
	elif enum_value == ERRCODE_Call_barring:
		value_str = "'ERRCODE_Call_barring--197'"
	elif enum_value == ERRCODE_add_forbidden_user_failed:
		value_str = "'ERRCODE_add_forbidden_user_failed--198'"
	elif enum_value == ERRCODE_forbidden_register_user:
		value_str = "'ERRCODE_forbidden_register_user--199'"
	elif enum_value == ERRCODE_Unauthorized:
		value_str = "'ERRCODE_Unauthorized--200'"
	elif enum_value == ERRCODE_is_rnm_user:
		value_str = "'ERRCODE_is_rnm_user--201'"
	elif enum_value == ERRCODE_table_exist:
		value_str = "'ERRCODE_table_exist--202'"
	elif enum_value == ERRCODE_record_empty:
		value_str = "'ERRCODE_record_empty--203'"
	elif enum_value == ERRCODE_impu_existed:
		value_str = "'ERRCODE_impu_existed--204'"
	elif enum_value == ERRCODE_invalid_context:
		value_str = "'ERRCODE_invalid_context--205'"
	elif enum_value == ERRCODE_authorized_failed:
		value_str = "'ERRCODE_authorized_failed--206'"
	elif enum_value == ERRCODE_logout:
		value_str = "'ERRCODE_logout--207'"
	elif enum_value == ERRCODE_mute_set_failed:
		value_str = "'ERRCODE_mute_set_failed--208'"
	elif enum_value == ERRCODE_invalid_url:
		value_str = "'ERRCODE_invalid_url--209'"
	elif enum_value == ERRCODE_Threshold_limit:
		value_str = "'ERRCODE_Threshold_limit--210'"
	elif enum_value == ERRCODE_Channel_closed:
		value_str = "'ERRCODE_Channel_closed--211'"
	elif enum_value == ERRCODE_invalid_request:
		value_str = "'ERRCODE_invalid_request--212'"
	elif enum_value == ERRCODE_Duplicate_name:
		value_str = "'ERRCODE_Duplicate_name--213'"
	elif enum_value == ERRCODE_lost_parameter:
		value_str = "'ERRCODE_lost_parameter--214'"
	elif enum_value == ERRCODE_lost_protocol:
		value_str = "'ERRCODE_lost_protocol--215'"
	elif enum_value == ERRCODE_system_not_ready:
		value_str = "'ERRCODE_system_not_ready--216'"
	elif enum_value == ERRCODE_package_check:
		value_str = "'ERRCODE_package_check--217'"
	elif enum_value == ERRCODE_package_discard:
		value_str = "'ERRCODE_package_discard--218'"
	elif enum_value == ERRCODE_resend:
		value_str = "'ERRCODE_resend--219'"
	elif enum_value == ERRCODE_Invalid_object:
		value_str = "'ERRCODE_Invalid_object--220'"
	elif enum_value == ERRCODE_over_max_package_types:
		value_str = "'ERRCODE_over_max_package_types--221'"
	elif enum_value == ERRCODE_over_max_package_numbers:
		value_str = "'ERRCODE_over_max_package_numbers--222'"
	elif enum_value == ERRCODE_wait_more_data:
		value_str = "'ERRCODE_wait_more_data--223'"
	elif enum_value == ERRCODE_unregister:
		value_str = "'ERRCODE_unregister--224'"
	elif enum_value == ERRCODE_maximum_intents:
		value_str = "'ERRCODE_maximum_intents--225'"
	elif enum_value == ERRCODE_intercept:
		value_str = "'ERRCODE_intercept--226'"
	elif enum_value == ERRCODE_repetitive_operation:
		value_str = "'ERRCODE_repetitive_operation--227'"
	elif enum_value == ERRCODE_Failed_to_identify:
		value_str = "'ERRCODE_Failed_to_identify--228'"
	elif enum_value == ERRCODE_Failed_to_features:
		value_str = "'ERRCODE_Failed_to_features--229'"
	elif enum_value == ERRCODE_No_clear_intention:
		value_str = "'ERRCODE_No_clear_intention--230'"
	elif enum_value == ERRCODE_db_no_data:
		value_str = "'ERRCODE_db_no_data--231'"
	elif enum_value == ERRCODE_insufficient_balance:
		value_str = "'ERRCODE_insufficient_balance--232'"
	elif enum_value == ERRCODE_lost_lock:
		value_str = "'ERRCODE_lost_lock--233'"
	elif enum_value == ERRCODE_lost_req_type:
		value_str = "'ERRCODE_lost_req_type--234'"
	elif enum_value == ERRCODE_can_not_find_client:
		value_str = "'ERRCODE_can_not_find_client--235'"
	elif enum_value == ERRCODE_out_of_bounds:
		value_str = "'ERRCODE_out_of_bounds--236'"
	elif enum_value == ERRCODE_valuation:
		value_str = "'ERRCODE_valuation--237'"
	elif enum_value == ERRCODE_Invalid_version:
		value_str = "'ERRCODE_Invalid_version--238'"
	elif enum_value == ERRCODE_auth_key_exist:
		value_str = "'ERRCODE_auth_key_exist--239'"
	elif enum_value == ERRCODE_predict_failed:
		value_str = "'ERRCODE_predict_failed--240'"
	elif enum_value == ERRCODE_internal_server_error:
		value_str = "'ERRCODE_internal_server_error--241'"
	elif enum_value == ERRCODE_update:
		value_str = "'ERRCODE_update--242'"
	elif enum_value == ERRCODE_lost_atom_ptl:
		value_str = "'ERRCODE_lost_atom_ptl--243'"
	elif enum_value == ERRCODE_bs_repeat:
		value_str = "'ERRCODE_bs_repeat--244'"
	elif enum_value == ERRCODE_can_not_find_user:
		value_str = "'ERRCODE_can_not_find_user--245'"
	elif enum_value == ERRCODE_name_already_exist:
		value_str = "'ERRCODE_name_already_exist--246'"
	elif enum_value == ERRCODE_can_not_find_cost_price:
		value_str = "'ERRCODE_can_not_find_cost_price--247'"
	elif enum_value == ERRCODE_can_not_find_unit_price:
		value_str = "'ERRCODE_can_not_find_unit_price--248'"
	elif enum_value == ERRCODE_cfg_already_exists:
		value_str = "'ERRCODE_cfg_already_exists--249'"
	elif enum_value == ERRCODE_storage:
		value_str = "'ERRCODE_storage--250'"
	elif enum_value == ERRCODE_Can_not_find_path:
		value_str = "'ERRCODE_Can_not_find_path--251'"
	elif enum_value == ERRCODE_over_time:
		value_str = "'ERRCODE_over_time--252'"
	elif enum_value == ERRCODE_soft_delete:
		value_str = "'ERRCODE_soft_delete--253'"
	elif enum_value == ERRCODE_Not_found_ptl_name:
		value_str = "'ERRCODE_Not_found_ptl_name--254'"
	elif enum_value == ERRCODE_RELEASE:
		value_str = "'ERRCODE_RELEASE--255'"
	elif enum_value == ERRCODE_Not_found_billing:
		value_str = "'ERRCODE_Not_found_billing--256'"
	elif enum_value == ERRCODE_Can_not_find_area:
		value_str = "'ERRCODE_Can_not_find_area--257'"
	elif enum_value == ERRCODE_User_Unregister:
		value_str = "'ERRCODE_User_Unregister--258'"
	elif enum_value == ERRCODE_Stateless_Sending:
		value_str = "'ERRCODE_Stateless_Sending--259'"
	elif enum_value == ERRCODE_Can_not_find_business_rules:
		value_str = "'ERRCODE_Can_not_find_business_rules--260'"
	elif enum_value == ERRCODE_reconnect:
		value_str = "'ERRCODE_reconnect--261'"
	elif enum_value == ERRCODE_Blacklist_intercept:
		value_str = "'ERRCODE_Blacklist_intercept--262'"
	elif enum_value == ERRCODE_data_not_exist:
		value_str = "'ERRCODE_data_not_exist--263'"
	elif enum_value == ERRCODE_Invalid_length:
		value_str = "'ERRCODE_Invalid_length--264'"
	elif enum_value == ERRCODE_Route_Direct:
		value_str = "'ERRCODE_Route_Direct--265'"
	elif enum_value == ERRCODE_Can_not_find_isp:
		value_str = "'ERRCODE_Can_not_find_isp--266'"
	elif enum_value == ERRCODE_DB_Already_Exist:
		value_str = "'ERRCODE_DB_Already_Exist--267'"
	elif enum_value == ErrCode_max:
		value_str = "'ErrCode_max-0x1fffffffffffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_FixedPortFlag_str(enum_value):
	if enum_value == FixedPort:
		value_str = "'FixedPort-0x01234567'"
	elif enum_value == NotFixedPort:
		value_str = "'NotFixedPort-0x09abcdef'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_HTTPListenType_str(enum_value):
	if enum_value == ListenHttp:
		value_str = "'ListenHttp'"
	elif enum_value == ListenHttps:
		value_str = "'ListenHttps'"
	elif enum_value == ListenWeb:
		value_str = "'ListenWeb'"
	elif enum_value == ListenMax:
		value_str = "'ListenMax'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_HTTPMathcRule_str(enum_value):
	if enum_value == LocationMatch_Accurate:
		value_str = "'LocationMatch_Accurate-0'"
	elif enum_value == LocationMatch_Prefix:
		value_str = "'LocationMatch_Prefix'"
	elif enum_value == LocationMatch_CaseRegular:
		value_str = "'LocationMatch_CaseRegular'"
	elif enum_value == LocationMatch_Regular:
		value_str = "'LocationMatch_Regular'"
	elif enum_value == LocationMatch_CaseRegularExcl:
		value_str = "'LocationMatch_CaseRegularExcl'"
	elif enum_value == LocationMatch_RegularExcl:
		value_str = "'LocationMatch_RegularExcl'"
	elif enum_value == LocationMatch_Wildcard:
		value_str = "'LocationMatch_Wildcard'"
	elif enum_value == LocationMatch_Max:
		value_str = "'LocationMatch_Max'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_HttpContentType_str(enum_value):
	if enum_value == HttpContentType_json:
		value_str = "'HttpContentType_json'"
	elif enum_value == HttpContentType_text:
		value_str = "'HttpContentType_text'"
	elif enum_value == HttpContentType_xml:
		value_str = "'HttpContentType_xml'"
	elif enum_value == HttpContentType_xwww:
		value_str = "'HttpContentType_xwww'"
	elif enum_value == HttpContentType_max:
		value_str = "'HttpContentType_max'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_HttpMethod_str(enum_value):
	if enum_value == HttpMethod_post:
		value_str = "'HttpMethod_post'"
	elif enum_value == HttpMethod_get:
		value_str = "'HttpMethod_get'"
	elif enum_value == HttpMethod_put:
		value_str = "'HttpMethod_put'"
	elif enum_value == HttpMethod_options:
		value_str = "'HttpMethod_options'"
	elif enum_value == HttpMethod_delete:
		value_str = "'HttpMethod_delete'"
	elif enum_value == HttpMethod_max:
		value_str = "'HttpMethod_max'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_IPProtocol_str(enum_value):
	if enum_value == IPProtocol_ICMP:
		value_str = "'IPProtocol_ICMP-1'"
	elif enum_value == IPProtocol_TCP:
		value_str = "'IPProtocol_TCP-6'"
	elif enum_value == IPProtocol_UDP:
		value_str = "'IPProtocol_UDP-17'"
	elif enum_value == IPProtocol_GRE:
		value_str = "'IPProtocol_GRE-47'"
	elif enum_value == IPProtocol_MAX:
		value_str = "'IPProtocol_MAX-0x1fffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_IPVER_str(enum_value):
	if enum_value == IPVER_IPV4:
		value_str = "'IPVER_IPV4-4'"
	elif enum_value == IPVER_IPV6:
		value_str = "'IPVER_IPV6-6'"
	elif enum_value == IPVER_MAX:
		value_str = "'IPVER_MAX-0x1fffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_LanguageCode_str(enum_value):
	if enum_value == LanguageCode_Abkhazian:
		value_str = "'LanguageCode_Abkhazian'"
	elif enum_value == LanguageCode_Afar:
		value_str = "'LanguageCode_Afar'"
	elif enum_value == LanguageCode_Afrikaans:
		value_str = "'LanguageCode_Afrikaans'"
	elif enum_value == LanguageCode_Akan:
		value_str = "'LanguageCode_Akan'"
	elif enum_value == LanguageCode_Albanian:
		value_str = "'LanguageCode_Albanian'"
	elif enum_value == LanguageCode_Amharic:
		value_str = "'LanguageCode_Amharic'"
	elif enum_value == LanguageCode_Arabic:
		value_str = "'LanguageCode_Arabic'"
	elif enum_value == LanguageCode_Aragonese:
		value_str = "'LanguageCode_Aragonese'"
	elif enum_value == LanguageCode_Armenian:
		value_str = "'LanguageCode_Armenian'"
	elif enum_value == LanguageCode_Assamese:
		value_str = "'LanguageCode_Assamese'"
	elif enum_value == LanguageCode_Avaric:
		value_str = "'LanguageCode_Avaric'"
	elif enum_value == LanguageCode_Avestan:
		value_str = "'LanguageCode_Avestan'"
	elif enum_value == LanguageCode_Aymara:
		value_str = "'LanguageCode_Aymara'"
	elif enum_value == LanguageCode_Chinese:
		value_str = "'LanguageCode_Chinese'"
	elif enum_value == LanguageCode_Chuvash:
		value_str = "'LanguageCode_Chuvash'"
	elif enum_value == LanguageCode_Cornish:
		value_str = "'LanguageCode_Cornish'"
	elif enum_value == LanguageCode_Corsican:
		value_str = "'LanguageCode_Corsican'"
	elif enum_value == LanguageCode_English:
		value_str = "'LanguageCode_English'"
	elif enum_value == LanguageCode_French:
		value_str = "'LanguageCode_French'"
	elif enum_value == LanguageCode_German:
		value_str = "'LanguageCode_German'"
	elif enum_value == LanguageCode_Italian:
		value_str = "'LanguageCode_Italian'"
	elif enum_value == LanguageCode_Japanese:
		value_str = "'LanguageCode_Japanese'"
	elif enum_value == LanguageCode_Korean:
		value_str = "'LanguageCode_Korean'"
	elif enum_value == LanguageCode_Russian:
		value_str = "'LanguageCode_Russian'"
	elif enum_value == LanguageCode_Spanish_Castilian:
		value_str = "'LanguageCode_Spanish_Castilian'"
	elif enum_value == LanguageCode_Sundanese:
		value_str = "'LanguageCode_Sundanese'"
	elif enum_value == LanguageCode_Swahili:
		value_str = "'LanguageCode_Swahili'"
	elif enum_value == LanguageCode_Swati:
		value_str = "'LanguageCode_Swati'"
	elif enum_value == LanguageCode_Swedish:
		value_str = "'LanguageCode_Swedish'"
	elif enum_value == LanguageCode_Tamil:
		value_str = "'LanguageCode_Tamil'"
	elif enum_value == LanguageCode_Telugu:
		value_str = "'LanguageCode_Telugu'"
	elif enum_value == LanguageCode_Tajik:
		value_str = "'LanguageCode_Tajik'"
	elif enum_value == LanguageCode_Thai:
		value_str = "'LanguageCode_Thai'"
	elif enum_value == LanguageCode_Traditional_Chinese:
		value_str = "'LanguageCode_Traditional_Chinese'"
	elif enum_value == LanguageCode_Dutch:
		value_str = "'LanguageCode_Dutch'"
	elif enum_value == LanguageCode_max:
		value_str = "'LanguageCode_max'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_MCardContentType_str(enum_value):
	if enum_value == MCardContentType_begin:
		value_str = "'MCardContentType_begin'"
	elif enum_value == MCardContentType_utf8:
		value_str = "'MCardContentType_utf8'"
	elif enum_value == MCardContentType_json:
		value_str = "'MCardContentType_json'"
	elif enum_value == MCardContentType_xml:
		value_str = "'MCardContentType_xml'"
	elif enum_value == MCardContentType_login:
		value_str = "'MCardContentType_login'"
	elif enum_value == MCardContentType_jpg_cropped_bin:
		value_str = "'MCardContentType_jpg_cropped_bin'"
	elif enum_value == MCardContentType_jpg_uncropped_bin:
		value_str = "'MCardContentType_jpg_uncropped_bin'"
	elif enum_value == MCardContentType_image_sha1_id:
		value_str = "'MCardContentType_image_sha1_id'"
	elif enum_value == MCardContentType_face_matching:
		value_str = "'MCardContentType_face_matching'"
	elif enum_value == MCardContentType_poster_generate:
		value_str = "'MCardContentType_poster_generate'"
	elif enum_value == MCardContentType_start_up:
		value_str = "'MCardContentType_start_up'"
	elif enum_value == MCardContentType_museum_page:
		value_str = "'MCardContentType_museum_page'"
	elif enum_value == MCardContentType_painter_page:
		value_str = "'MCardContentType_painter_page'"
	elif enum_value == MCardContentType_bbs_comment:
		value_str = "'MCardContentType_bbs_comment'"
	elif enum_value == MCardContentType_bbs_load:
		value_str = "'MCardContentType_bbs_load'"
	elif enum_value == MCardContentType_painting_recommend:
		value_str = "'MCardContentType_painting_recommend'"
	elif enum_value == MCardContentType_portrait_transfer_list:
		value_str = "'MCardContentType_portrait_transfer_list'"
	elif enum_value == MCardContentType_portrait_transfer_action:
		value_str = "'MCardContentType_portrait_transfer_action'"
	elif enum_value == MCardContentType_landscape_transfer_list:
		value_str = "'MCardContentType_landscape_transfer_list'"
	elif enum_value == MCardContentType_landscape_transfer_action:
		value_str = "'MCardContentType_landscape_transfer_action'"
	elif enum_value == MCardContentType_image_search_cropped_bin:
		value_str = "'MCardContentType_image_search_cropped_bin'"
	elif enum_value == MCardContentType_image_search_uncropped_bin:
		value_str = "'MCardContentType_image_search_uncropped_bin'"
	elif enum_value == MCardContentType_sculptures_search_cropped_bin:
		value_str = "'MCardContentType_sculptures_search_cropped_bin'"
	elif enum_value == MCardContentType_sculptures_search_uncropped_bin:
		value_str = "'MCardContentType_sculptures_search_uncropped_bin'"
	elif enum_value == MCardContentType_menu_recognition:
		value_str = "'MCardContentType_menu_recognition'"
	elif enum_value == MCardContentType_tourism_image_search:
		value_str = "'MCardContentType_tourism_image_search'"
	elif enum_value == MCardContentType_bagword:
		value_str = "'MCardContentType_bagword'"
	elif enum_value == MCardContentType_museum_recommend:
		value_str = "'MCardContentType_museum_recommend'"
	elif enum_value == MCardContentType_painting_recommend_page:
		value_str = "'MCardContentType_painting_recommend_page'"
	elif enum_value == MCardContentType_museum_recommend_page:
		value_str = "'MCardContentType_museum_recommend_page'"
	elif enum_value == MCardContentType_museum_sha1_id:
		value_str = "'MCardContentType_museum_sha1_id'"
	elif enum_value == MCardContentType_refresh_recommend_cache:
		value_str = "'MCardContentType_refresh_recommend_cache'"
	elif enum_value == MCardContentType_detection:
		value_str = "'MCardContentType_detection'"
	elif enum_value == MCardContentType_generator:
		value_str = "'MCardContentType_generator'"
	elif enum_value == MCardContentType_end:
		value_str = "'MCardContentType_end'"
	elif enum_value == MCardContentType_max:
		value_str = "'MCardContentType_max-0x1fffffffffffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_MCardIdentityType_str(enum_value):
	if enum_value == MCardIdentityType_none:
		value_str = "'MCardIdentityType_none'"
	elif enum_value == MCardIdentityType_initialization:
		value_str = "'MCardIdentityType_initialization'"
	elif enum_value == MCardIdentityType_user:
		value_str = "'MCardIdentityType_user'"
	elif enum_value == MCardIdentityType_AI:
		value_str = "'MCardIdentityType_AI'"
	elif enum_value == MCardIdentityType_max:
		value_str = "'MCardIdentityType_max'"
	elif enum_value == MCardIdentityType_MAX:
		value_str = "'MCardIdentityType_MAX-0x1fffffffffffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_MCardSource_str(enum_value):
	if enum_value == MCardSource_aia:
		value_str = "'MCardSource_aia'"
	elif enum_value == MCardSource_google:
		value_str = "'MCardSource_google'"
	elif enum_value == MCardSource_aws:
		value_str = "'MCardSource_aws'"
	elif enum_value == MCardSource_aic:
		value_str = "'MCardSource_aic'"
	elif enum_value == MCardSource_aib:
		value_str = "'MCardSource_aib'"
	elif enum_value == MCardSource_aib_io:
		value_str = "'MCardSource_aib_io'"
	elif enum_value == MCardSource_bbs:
		value_str = "'MCardSource_bbs'"
	elif enum_value == MCardSource_max:
		value_str = "'MCardSource_max-0x1fffffffffffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_MCardTimeType_str(enum_value):
	if enum_value == MCardTimeType_Permanent:
		value_str = "'MCardTimeType_Permanent'"
	elif enum_value == MCardTimeType_Normal:
		value_str = "'MCardTimeType_Normal'"
	elif enum_value == MCardTimeType_max:
		value_str = "'MCardTimeType_max-0x1fffffffffffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_MCardType_str(enum_value):
	if enum_value == MCardType_Private_Message_Board:
		value_str = "'MCardType_Private_Message_Board'"
	elif enum_value == MCardType_Public_Message_Board:
		value_str = "'MCardType_Public_Message_Board'"
	elif enum_value == MCardType_POI:
		value_str = "'MCardType_POI'"
	elif enum_value == MCardType_TALK:
		value_str = "'MCardType_TALK'"
	elif enum_value == MCardType_weichat_talk:
		value_str = "'MCardType_weichat_talk'"
	elif enum_value == MCardType_h5_talk:
		value_str = "'MCardType_h5_talk'"
	elif enum_value == MCardType_max:
		value_str = "'MCardType_max-0x1fffffffffffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_MCardVer_str(enum_value):
	if enum_value == MCardVer_reserve:
		value_str = "'MCardVer_reserve'"
	elif enum_value == MCardVer_text:
		value_str = "'MCardVer_text'"
	elif enum_value == MCardVer_media:
		value_str = "'MCardVer_media'"
	elif enum_value == MCardVer_talk:
		value_str = "'MCardVer_talk'"
	elif enum_value == MCardVer_comment:
		value_str = "'MCardVer_comment'"
	elif enum_value == MCardVer_max:
		value_str = "'MCardVer_max-0x1fffffffffffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_NetAddrType_str(enum_value):
	if enum_value == NetAddrIPType:
		value_str = "'NetAddrIPType-0'"
	elif enum_value == NetAddrIPBroadcastType:
		value_str = "'NetAddrIPBroadcastType'"
	elif enum_value == NetAddrURLType:
		value_str = "'NetAddrURLType-0x12345678'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_PythonFun_str(enum_value):
	if enum_value == PythonFun_painting_aesthetics:
		value_str = "'PythonFun_painting_aesthetics-0'"
	elif enum_value == PythonFun_image_search_engine:
		value_str = "'PythonFun_image_search_engine'"
	elif enum_value == PythonFun_painting_recommend:
		value_str = "'PythonFun_painting_recommend'"
	elif enum_value == PythonFun_style_transfer:
		value_str = "'PythonFun_style_transfer'"
	elif enum_value == PythonFun_sculptures_search_engine:
		value_str = "'PythonFun_sculptures_search_engine'"
	elif enum_value == PythonFun_menu_recognition:
		value_str = "'PythonFun_menu_recognition'"
	elif enum_value == PythonFun_travel_aesthetics:
		value_str = "'PythonFun_travel_aesthetics'"
	elif enum_value == PythonFun_weichat_openid:
		value_str = "'PythonFun_weichat_openid'"
	elif enum_value == PythonFun_poster:
		value_str = "'PythonFun_poster'"
	elif enum_value == PythonFun_bagword:
		value_str = "'PythonFun_bagword'"
	elif enum_value == PythonFun_museum_recommend:
		value_str = "'PythonFun_museum_recommend'"
	elif enum_value == PythonFun_painting_recommend_page:
		value_str = "'PythonFun_painting_recommend_page'"
	elif enum_value == PythonFun_museum_recommend_page:
		value_str = "'PythonFun_museum_recommend_page'"
	elif enum_value == PythonFun_refresh_recommend_cache:
		value_str = "'PythonFun_refresh_recommend_cache'"
	elif enum_value == PythonFun_detection:
		value_str = "'PythonFun_detection'"
	elif enum_value == PythonFun_generator:
		value_str = "'PythonFun_generator'"
	elif enum_value == PythonFun_max:
		value_str = "'PythonFun_max-0x1fffffffffffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_ReqType_str(enum_value):
	if enum_value == REQ_TYPE_MAX:
		value_str = "'REQ_TYPE_MAX-0x1fffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_RetCode_str(enum_value):
	if enum_value == RetCode_begin_value:
		value_str = "'RetCode_begin_value-1'"
	elif enum_value == RetCode_OK:
		value_str = "'RetCode_OK-0'"
	elif enum_value == RetCode_Memory_full:
		value_str = "'RetCode_Memory_full--1'"
	elif enum_value == RetCode_Limited_resources:
		value_str = "'RetCode_Limited_resources--2'"
	elif enum_value == RetCode_Arithmetic_error:
		value_str = "'RetCode_Arithmetic_error--3'"
	elif enum_value == RetCode_Unknown_error:
		value_str = "'RetCode_Unknown_error--4'"
	elif enum_value == RetCode_Can_not_find_node:
		value_str = "'RetCode_Can_not_find_node--5'"
	elif enum_value == RetCode_Send_failed:
		value_str = "'RetCode_Send_failed--6'"
	elif enum_value == RetCode_Recv_failed:
		value_str = "'RetCode_Recv_failed--7'"
	elif enum_value == RetCode_Invalid_data:
		value_str = "'RetCode_Invalid_data--8'"
	elif enum_value == RetCode_Unsupported_type:
		value_str = "'RetCode_Unsupported_type--9'"
	elif enum_value == RetCode_Invalid_user_name:
		value_str = "'RetCode_Invalid_user_name--10'"
	elif enum_value == RetCode_Parameter_conflicts:
		value_str = "'RetCode_Parameter_conflicts--11'"
	elif enum_value == RetCode_Invalid_device:
		value_str = "'RetCode_Invalid_device--12'"
	elif enum_value == RetCode_Invalid_Event:
		value_str = "'RetCode_Invalid_Event--13'"
	elif enum_value == RetCode_Heartbeat_timeout:
		value_str = "'RetCode_Heartbeat_timeout--14'"
	elif enum_value == RetCode_invalid_content:
		value_str = "'RetCode_invalid_content--15'"
	elif enum_value == RetCode_save_failed:
		value_str = "'RetCode_save_failed--16'"
	elif enum_value == RetCode_Invalid_data_too_short:
		value_str = "'RetCode_Invalid_data_too_short--17'"
	elif enum_value == RetCode_Invalid_data_too_long:
		value_str = "'RetCode_Invalid_data_too_long--18'"
	elif enum_value == RetCode_Invalid_data_crc_check:
		value_str = "'RetCode_Invalid_data_crc_check--19'"
	elif enum_value == RetCode_Invalid_parameter:
		value_str = "'RetCode_Invalid_parameter--20'"
	elif enum_value == RetCode_Send_msg_failed:
		value_str = "'RetCode_Send_msg_failed--21'"
	elif enum_value == RetCode_Resource_conflicts:
		value_str = "'RetCode_Resource_conflicts--22'"
	elif enum_value == RetCode_CREDIT_LIMIT_REACHED:
		value_str = "'RetCode_CREDIT_LIMIT_REACHED--23'"
	elif enum_value == RetCode_Exceeded_number:
		value_str = "'RetCode_Exceeded_number--24'"
	elif enum_value == RetCode_do_not_free:
		value_str = "'RetCode_do_not_free--25'"
	elif enum_value == RetCode_Request_failed:
		value_str = "'RetCode_Request_failed--26'"
	elif enum_value == RetCode_can_not_find_ret_code:
		value_str = "'RetCode_can_not_find_ret_code--27'"
	elif enum_value == RetCode_user_is_registered:
		value_str = "'RetCode_user_is_registered--28'"
	elif enum_value == RetCode_connect_error:
		value_str = "'RetCode_connect_error--29'"
	elif enum_value == RetCode_function_not_supported:
		value_str = "'RetCode_function_not_supported--30'"
	elif enum_value == RetCode_msg_queue_is_full:
		value_str = "'RetCode_msg_queue_is_full--31'"
	elif enum_value == RetCode_msg_can_not_resend_wakeup:
		value_str = "'RetCode_msg_can_not_resend_wakeup--32'"
	elif enum_value == RetCode_msg_memory_if_full:
		value_str = "'RetCode_msg_memory_if_full--33'"
	elif enum_value == RetCode_msg_competition_for_resources:
		value_str = "'RetCode_msg_competition_for_resources--34'"
	elif enum_value == RetCode_wait:
		value_str = "'RetCode_wait--35'"
	elif enum_value == RetCode_Invalid_state:
		value_str = "'RetCode_Invalid_state--36'"
	elif enum_value == RetCode_usr_default:
		value_str = "'RetCode_usr_default--37'"
	elif enum_value == RetCode_timer_out:
		value_str = "'RetCode_timer_out--38'"
	elif enum_value == RetCode_invalid_type:
		value_str = "'RetCode_invalid_type--39'"
	elif enum_value == RetCode_user_does_not_exist:
		value_str = "'RetCode_user_does_not_exist--40'"
	elif enum_value == RetCode_version_new:
		value_str = "'RetCode_version_new--41'"
	elif enum_value == RetCode_version_old:
		value_str = "'RetCode_version_old--42'"
	elif enum_value == RetCode_ptr_null:
		value_str = "'RetCode_ptr_null--43'"
	elif enum_value == RetCode_record_not_exist:
		value_str = "'RetCode_record_not_exist--44'"
	elif enum_value == RetCode_db_store_failed:
		value_str = "'RetCode_db_store_failed--45'"
	elif enum_value == RetCode_db_not_find:
		value_str = "'RetCode_db_not_find--46'"
	elif enum_value == RetCode_Invalid_channel_name:
		value_str = "'RetCode_Invalid_channel_name--47'"
	elif enum_value == RetCode_Invalid_db_store:
		value_str = "'RetCode_Invalid_db_store--48'"
	elif enum_value == RetCode_version_mismatch:
		value_str = "'RetCode_version_mismatch--49'"
	elif enum_value == RetCode_invalid_version_file:
		value_str = "'RetCode_invalid_version_file--50'"
	elif enum_value == RetCode_version_identical:
		value_str = "'RetCode_version_identical--51'"
	elif enum_value == RetCode_channel_not_exist:
		value_str = "'RetCode_channel_not_exist--52'"
	elif enum_value == RetCode_invalid_option:
		value_str = "'RetCode_invalid_option--53'"
	elif enum_value == RetCode_Invalid_domain:
		value_str = "'RetCode_Invalid_domain--54'"
	elif enum_value == RetCode_Invalid_auth_key:
		value_str = "'RetCode_Invalid_auth_key--55'"
	elif enum_value == RetCode_invalid_key:
		value_str = "'RetCode_invalid_key--56'"
	elif enum_value == RetCode_no_account_found:
		value_str = "'RetCode_no_account_found--57'"
	elif enum_value == RetCode_invalid_phone_number:
		value_str = "'RetCode_invalid_phone_number--58'"
	elif enum_value == RetCode_not_match_domain:
		value_str = "'RetCode_not_match_domain--59'"
	elif enum_value == RetCode_invalid_account:
		value_str = "'RetCode_invalid_account--60'"
	elif enum_value == RetCode_please_help_free:
		value_str = "'RetCode_please_help_free--61'"
	elif enum_value == RetCode_db_init_failed:
		value_str = "'RetCode_db_init_failed--62'"
	elif enum_value == RetCode_update_fail:
		value_str = "'RetCode_update_fail--63'"
	elif enum_value == RetCode_maybe_have_data:
		value_str = "'RetCode_maybe_have_data--64'"
	elif enum_value == RetCode_do_not_restart:
		value_str = "'RetCode_do_not_restart--65'"
	elif enum_value == RetCode_lost_auth_key:
		value_str = "'RetCode_lost_auth_key--66'"
	elif enum_value == RetCode_lost_serial:
		value_str = "'RetCode_lost_serial--67'"
	elif enum_value == RetCode_lost_time:
		value_str = "'RetCode_lost_time--68'"
	elif enum_value == RetCode_lost_uuid:
		value_str = "'RetCode_lost_uuid--69'"
	elif enum_value == RetCode_lost_user:
		value_str = "'RetCode_lost_user--70'"
	elif enum_value == RetCode_can_not_find_record:
		value_str = "'RetCode_can_not_find_record--71'"
	elif enum_value == RetCode_empty_data:
		value_str = "'RetCode_empty_data--72'"
	elif enum_value == RetCode_Channel_closed:
		value_str = "'RetCode_Channel_closed--73'"
	elif enum_value == RetCode_lost_link:
		value_str = "'RetCode_lost_link--74'"
	elif enum_value == RetCode_record_not_found:
		value_str = "'RetCode_record_not_found--75'"
	elif enum_value == RetCode_not_access:
		value_str = "'RetCode_not_access--76'"
	elif enum_value == RetCode_can_not_find_thread:
		value_str = "'RetCode_can_not_find_thread--77'"
	elif enum_value == RetCode_can_not_find_client:
		value_str = "'RetCode_can_not_find_client--78'"
	elif enum_value == RetCode_user_exist:
		value_str = "'RetCode_user_exist--79'"
	elif enum_value == RetCode_store_data_failed:
		value_str = "'RetCode_store_data_failed--80'"
	elif enum_value == RetCode_Invalid_user_type:
		value_str = "'RetCode_Invalid_user_type--81'"
	elif enum_value == RetCode_invalid_user:
		value_str = "'RetCode_invalid_user--82'"
	elif enum_value == RetCode_unsupport:
		value_str = "'RetCode_unsupport--83'"
	elif enum_value == RetCode_unpackage_failed:
		value_str = "'RetCode_unpackage_failed--84'"
	elif enum_value == RetCode_creat_db_failed:
		value_str = "'RetCode_creat_db_failed--85'"
	elif enum_value == RetCode_Invalid_channel:
		value_str = "'RetCode_Invalid_channel--86'"
	elif enum_value == RetCode_heartbeat_timer_out:
		value_str = "'RetCode_heartbeat_timer_out--87'"
	elif enum_value == RetCode_not_my_data:
		value_str = "'RetCode_not_my_data--88'"
	elif enum_value == RetCode_Invalid_rules:
		value_str = "'RetCode_Invalid_rules--89'"
	elif enum_value == RetCode_busy:
		value_str = "'RetCode_busy--90'"
	elif enum_value == RetCode_data_overflow:
		value_str = "'RetCode_data_overflow--91'"
	elif enum_value == RetCode_invalid_account_name:
		value_str = "'RetCode_invalid_account_name--92'"
	elif enum_value == RetCode_Account_in_use:
		value_str = "'RetCode_Account_in_use--93'"
	elif enum_value == RetCode_invalid_address:
		value_str = "'RetCode_invalid_address--94'"
	elif enum_value == RetCode_can_not_find_rules:
		value_str = "'RetCode_can_not_find_rules--95'"
	elif enum_value == RetCode_refuse_call_self:
		value_str = "'RetCode_refuse_call_self--96'"
	elif enum_value == RetCode_Invalid_call:
		value_str = "'RetCode_Invalid_call--97'"
	elif enum_value == RetCode_mismatch:
		value_str = "'RetCode_mismatch--98'"
	elif enum_value == RetCode_Invalid_call_type:
		value_str = "'RetCode_Invalid_call_type--99'"
	elif enum_value == RetCode_Invalid_billing:
		value_str = "'RetCode_Invalid_billing--100'"
	elif enum_value == RetCode_invalid_magic:
		value_str = "'RetCode_invalid_magic--101'"
	elif enum_value == RetCode_create_thread_failed:
		value_str = "'RetCode_create_thread_failed--102'"
	elif enum_value == RetCode_script_execution_error:
		value_str = "'RetCode_script_execution_error--103'"
	elif enum_value == RetCode_decode_failed:
		value_str = "'RetCode_decode_failed--104'"
	elif enum_value == RetCode_encode_failed:
		value_str = "'RetCode_encode_failed--105'"
	elif enum_value == RetCode_invalid_file:
		value_str = "'RetCode_invalid_file--106'"
	elif enum_value == RetCode_file_open_failed:
		value_str = "'RetCode_file_open_failed--107'"
	elif enum_value == RetCode_process_now:
		value_str = "'RetCode_process_now--108'"
	elif enum_value == RetCode_queue_too_large:
		value_str = "'RetCode_queue_too_large--109'"
	elif enum_value == RetCode_repeated_request:
		value_str = "'RetCode_repeated_request--110'"
	elif enum_value == RetCode_Can_not_find_path:
		value_str = "'RetCode_Can_not_find_path--111'"
	elif enum_value == RetCode_invalid_hour:
		value_str = "'RetCode_invalid_hour--112'"
	elif enum_value == RetCode_invalid_day:
		value_str = "'RetCode_invalid_day--113'"
	elif enum_value == RetCode_invalid_week:
		value_str = "'RetCode_invalid_week--114'"
	elif enum_value == RetCode_invalid_month:
		value_str = "'RetCode_invalid_month--115'"
	elif enum_value == RetCode_invalid_year:
		value_str = "'RetCode_invalid_year--116'"
	elif enum_value == RetCode_invalid_date:
		value_str = "'RetCode_invalid_date--117'"
	elif enum_value == RetCode_table_exist:
		value_str = "'RetCode_table_exist--118'"
	elif enum_value == RetCode_db_sql_failed:
		value_str = "'RetCode_db_sql_failed--119'"
	elif enum_value == RetCode_Unauthorized_access:
		value_str = "'RetCode_Unauthorized_access--120'"
	elif enum_value == RetCode_max:
		value_str = "'RetCode_max-0x1fffffffffffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_SOCDOMAIN_str(enum_value):
	if enum_value == DM_SOC_PF_INET:
		value_str = "'DM_SOC_PF_INET-0'"
	elif enum_value == DM_SOC_PF_INET6:
		value_str = "'DM_SOC_PF_INET6'"
	elif enum_value == DM_SOC_PF_UART:
		value_str = "'DM_SOC_PF_UART'"
	elif enum_value == DM_SOC_PF_LOCAL_INET:
		value_str = "'DM_SOC_PF_LOCAL_INET'"
	elif enum_value == DM_SOC_PF_LOCAL_INET6:
		value_str = "'DM_SOC_PF_LOCAL_INET6'"
	elif enum_value == DM_SOC_PF_RAW:
		value_str = "'DM_SOC_PF_RAW'"
	elif enum_value == DM_SOC_PF_RAW_INET:
		value_str = "'DM_SOC_PF_RAW_INET'"
	elif enum_value == SOCDOMAIN_MAX:
		value_str = "'SOCDOMAIN_MAX-0x1fffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_SOCEVENT_str(enum_value):
	if enum_value == SOC_EVENT_START:
		value_str = "'SOC_EVENT_START-0'"
	elif enum_value == SOC_EVENT_WAIT_CREAT:
		value_str = "'SOC_EVENT_WAIT_CREAT'"
	elif enum_value == SOC_EVENT_CONNECT:
		value_str = "'SOC_EVENT_CONNECT'"
	elif enum_value == SOC_EVENT_CONNECT_FAIL:
		value_str = "'SOC_EVENT_CONNECT_FAIL'"
	elif enum_value == SOC_EVENT_WAIT_CONNECT:
		value_str = "'SOC_EVENT_WAIT_CONNECT'"
	elif enum_value == SOC_EVENT_ACCEPT:
		value_str = "'SOC_EVENT_ACCEPT'"
	elif enum_value == SOC_EVENT_REV:
		value_str = "'SOC_EVENT_REV'"
	elif enum_value == SOC_EVENT_SND:
		value_str = "'SOC_EVENT_SND'"
	elif enum_value == SOC_EVENT_CLOSE:
		value_str = "'SOC_EVENT_CLOSE'"
	elif enum_value == SOC_EVENT_SILENCE:
		value_str = "'SOC_EVENT_SILENCE'"
	elif enum_value == SOC_EVENT_MAX:
		value_str = "'SOC_EVENT_MAX'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_SOCKETINFO_str(enum_value):
	if enum_value == SOCKETINFO_BIND:
		value_str = "'SOCKETINFO_BIND-0'"
	elif enum_value == SOCKETINFO_BIND_OK:
		value_str = "'SOCKETINFO_BIND_OK'"
	elif enum_value == SOCKETINFO_BIND_FAIL:
		value_str = "'SOCKETINFO_BIND_FAIL'"
	elif enum_value == SOCKETINFO_CONNECT:
		value_str = "'SOCKETINFO_CONNECT'"
	elif enum_value == SOCKETINFO_CONNECT_OK:
		value_str = "'SOCKETINFO_CONNECT_OK'"
	elif enum_value == SOCKETINFO_CONNECT_FAIL:
		value_str = "'SOCKETINFO_CONNECT_FAIL'"
	elif enum_value == SOCKETINFO_CONNECT_WAIT:
		value_str = "'SOCKETINFO_CONNECT_WAIT'"
	elif enum_value == SOCKETINFO_DISCONNECT:
		value_str = "'SOCKETINFO_DISCONNECT'"
	elif enum_value == SOCKETINFO_DISCONNECT_OK:
		value_str = "'SOCKETINFO_DISCONNECT_OK'"
	elif enum_value == SOCKETINFO_DISCONNECT_FAIL:
		value_str = "'SOCKETINFO_DISCONNECT_FAIL'"
	elif enum_value == SOCKETINFO_DISCONNECT_WAIT:
		value_str = "'SOCKETINFO_DISCONNECT_WAIT'"
	elif enum_value == SOCKETINFO_CREAT:
		value_str = "'SOCKETINFO_CREAT'"
	elif enum_value == SOCKETINFO_WAIT_CREAT:
		value_str = "'SOCKETINFO_WAIT_CREAT'"
	elif enum_value == SOCKETINFO_ACCEPT:
		value_str = "'SOCKETINFO_ACCEPT'"
	elif enum_value == SOCKETINFO_REV:
		value_str = "'SOCKETINFO_REV'"
	elif enum_value == SOCKETINFO_REV_MBUF:
		value_str = "'SOCKETINFO_REV_MBUF'"
	elif enum_value == SOCKETINFO_SND:
		value_str = "'SOCKETINFO_SND'"
	elif enum_value == SOCKETINFO_CLOSE:
		value_str = "'SOCKETINFO_CLOSE'"
	elif enum_value == SOCKETINFO_SILENCE:
		value_str = "'SOCKETINFO_SILENCE'"
	elif enum_value == SOCKETINFO_DEVICE_CONNECT:
		value_str = "'SOCKETINFO_DEVICE_CONNECT'"
	elif enum_value == SOCKETINFO_DEVICE_DISCONNECT:
		value_str = "'SOCKETINFO_DEVICE_DISCONNECT'"
	elif enum_value == SOCKETINFO_LINK_LOST:
		value_str = "'SOCKETINFO_LINK_LOST'"
	elif enum_value == SOCKETINFO_SEND_TIMER_OUT:
		value_str = "'SOCKETINFO_SEND_TIMER_OUT'"
	elif enum_value == SOCKETINFO_PORT_EXIST:
		value_str = "'SOCKETINFO_PORT_EXIST'"
	elif enum_value == SOCKETINFO_WRITE_THEN_CLOSE:
		value_str = "'SOCKETINFO_WRITE_THEN_CLOSE'"
	elif enum_value == SOCKETINFO_SND_URG:
		value_str = "'SOCKETINFO_SND_URG'"
	elif enum_value == SOCKETINFO_RAW_EVENT_RECV_LENGTH:
		value_str = "'SOCKETINFO_RAW_EVENT_RECV_LENGTH'"
	elif enum_value == SOCKETINFO_MAX:
		value_str = "'SOCKETINFO_MAX-0x1fffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_SOCTYPE_str(enum_value):
	if enum_value == TYPE_SOCK_STREAM:
		value_str = "'TYPE_SOCK_STREAM-0'"
	elif enum_value == TYPE_SOCK_DGRAM:
		value_str = "'TYPE_SOCK_DGRAM'"
	elif enum_value == TYPE_SOCK_RAW:
		value_str = "'TYPE_SOCK_RAW'"
	elif enum_value == TYPE_SOCK_SCTP:
		value_str = "'TYPE_SOCK_SCTP'"
	elif enum_value == TYPE_SOCK_max:
		value_str = "'TYPE_SOCK_max'"
	elif enum_value == TYPE_SOCK_MAX:
		value_str = "'TYPE_SOCK_MAX-0x1fffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_UIPType_str(enum_value):
	if enum_value == UIPType_uip:
		value_str = "'UIPType_uip'"
	elif enum_value == UIPType_json:
		value_str = "'UIPType_json'"
	elif enum_value == UIPType_h5_form:
		value_str = "'UIPType_h5_form'"
	elif enum_value == UIPType_wechat_form:
		value_str = "'UIPType_wechat_form'"
	else:
		value_str = f'{enum_value}'
	return value_str


def t_auto_RPCMSG_str(enum_value):
	if enum_value == MSGID_RESERVED:
		value_str = "'MSGID_RESERVED-0x0000000000000000'"
	elif enum_value == MSGID_TEST:
		value_str = "'MSGID_TEST-1'"
	elif enum_value == MSGID_TIMER:
		value_str = "'MSGID_TIMER-2'"
	elif enum_value == MSGID_WAKEUP:
		value_str = "'MSGID_WAKEUP-3'"
	elif enum_value == MSGID_RUN_FUNCTION:
		value_str = "'MSGID_RUN_FUNCTION-4'"
	elif enum_value == MSGID_DEBUG_REQ:
		value_str = "'MSGID_DEBUG_REQ-5'"
	elif enum_value == MSGID_DEBUG_RSP:
		value_str = "'MSGID_DEBUG_RSP-6'"
	elif enum_value == MSGID_RESTART_REQ:
		value_str = "'MSGID_RESTART_REQ-7'"
	elif enum_value == MSGID_RESTART_RSP:
		value_str = "'MSGID_RESTART_RSP-8'"
	elif enum_value == MSGID_POWER_OFF:
		value_str = "'MSGID_POWER_OFF-9'"
	elif enum_value == MSGID_REMOTE_THREAD_READY:
		value_str = "'MSGID_REMOTE_THREAD_READY-10'"
	elif enum_value == MSGID_REMOTE_THREAD_REMOVE:
		value_str = "'MSGID_REMOTE_THREAD_REMOVE-11'"
	elif enum_value == MSGID_TRACE_SWITCH:
		value_str = "'MSGID_TRACE_SWITCH-12'"
	elif enum_value == MSGID_PROCESS_MSG_TIMER_OUT:
		value_str = "'MSGID_PROCESS_MSG_TIMER_OUT-13'"
	elif enum_value == MSGID_TEMPORARILY_DEFINE_MESSAGE:
		value_str = "'MSGID_TEMPORARILY_DEFINE_MESSAGE-14'"
	elif enum_value == MSGID_CALL_FUNCTION:
		value_str = "'MSGID_CALL_FUNCTION-15'"
	elif enum_value == MSGID_SYSTEM_MOUNT:
		value_str = "'MSGID_SYSTEM_MOUNT-16'"
	elif enum_value == MSGID_SYSTEM_DECOUPLING:
		value_str = "'MSGID_SYSTEM_DECOUPLING-17'"
	elif enum_value == MSGID_MEMORY_WARNING:
		value_str = "'MSGID_MEMORY_WARNING-18'"
	elif enum_value == MSGID_ECHO:
		value_str = "'MSGID_ECHO-19'"
	elif enum_value == MSGID_INTERNAL_EVENTS:
		value_str = "'MSGID_INTERNAL_EVENTS-20'"
	elif enum_value == MSGID_THREAD_BUSY:
		value_str = "'MSGID_THREAD_BUSY-21'"
	elif enum_value == MSGID_THREAD_IDLE:
		value_str = "'MSGID_THREAD_IDLE-22'"
	elif enum_value == MSGID_CLIENT_BUSY:
		value_str = "'MSGID_CLIENT_BUSY-23'"
	elif enum_value == MSGID_CLIENT_IDLE:
		value_str = "'MSGID_CLIENT_IDLE-24'"
	elif enum_value == MSGID_REMOTE_THREAD_ID_READY:
		value_str = "'MSGID_REMOTE_THREAD_ID_READY-25'"
	elif enum_value == MSGID_REMOTE_THREAD_ID_REMOVE:
		value_str = "'MSGID_REMOTE_THREAD_ID_REMOVE-26'"
	elif enum_value == MSGID_LOCAL_THREAD_READY:
		value_str = "'MSGID_LOCAL_THREAD_READY-27'"
	elif enum_value == MSGID_LOCAL_THREAD_REMOVE:
		value_str = "'MSGID_LOCAL_THREAD_REMOVE-28'"
	elif enum_value == MSGID_INNER_LOOP:
		value_str = "'MSGID_INNER_LOOP-29'"
	elif enum_value == MSGID_CFG_UPDATE:
		value_str = "'MSGID_CFG_UPDATE-30'"
	elif enum_value == MSGID_BLOCKS_REQ:
		value_str = "'MSGID_BLOCKS_REQ-31'"
	elif enum_value == MSGID_BLOCKS_RSP:
		value_str = "'MSGID_BLOCKS_RSP-32'"
	elif enum_value == MSGID_OS_NOTIFY:
		value_str = "'MSGID_OS_NOTIFY-33'"
	elif enum_value == MSGID_INTERNAL_LOOP:
		value_str = "'MSGID_INTERNAL_LOOP-34'"
	elif enum_value == MSGID_COROUTINE_WAKEUP:
		value_str = "'MSGID_COROUTINE_WAKEUP-35'"
	elif enum_value == MSGID_RPC_DEBUG_REQ:
		value_str = "'MSGID_RPC_DEBUG_REQ-36'"
	elif enum_value == MSGID_RPC_DEBUG_RSP:
		value_str = "'MSGID_RPC_DEBUG_RSP-37'"
	elif enum_value == MSGID_CFG_REMOTE_UPDATE:
		value_str = "'MSGID_CFG_REMOTE_UPDATE-38'"
	elif enum_value == MSGID_DOS_FORWARD:
		value_str = "'MSGID_DOS_FORWARD-39'"
	elif enum_value == MSGID_CFG_REMOTE_SYNC_UPDATE:
		value_str = "'MSGID_CFG_REMOTE_SYNC_UPDATE-40'"
	elif enum_value == SOCKET_BIND_REQ:
		value_str = "'SOCKET_BIND_REQ-1000'"
	elif enum_value == SOCKET_BIND_RSP:
		value_str = "'SOCKET_BIND_RSP-1001'"
	elif enum_value == SOCKET_CONNECT_REQ:
		value_str = "'SOCKET_CONNECT_REQ-1002'"
	elif enum_value == SOCKET_CONNECT_RSP:
		value_str = "'SOCKET_CONNECT_RSP-1003'"
	elif enum_value == SOCKET_DISCONNECT_REQ:
		value_str = "'SOCKET_DISCONNECT_REQ-1004'"
	elif enum_value == SOCKET_DISCONNECT_RSP:
		value_str = "'SOCKET_DISCONNECT_RSP-1005'"
	elif enum_value == SOCKET_PLUGIN:
		value_str = "'SOCKET_PLUGIN-1006'"
	elif enum_value == SOCKET_PLUGOUT:
		value_str = "'SOCKET_PLUGOUT-1007'"
	elif enum_value == SOCKET_READ:
		value_str = "'SOCKET_READ-1008'"
	elif enum_value == SOCKET_WRITE:
		value_str = "'SOCKET_WRITE-1009'"
	elif enum_value == SOCKET_NOTIFY:
		value_str = "'SOCKET_NOTIFY-1010'"
	elif enum_value == SOCKET_RAW_EVENT:
		value_str = "'SOCKET_RAW_EVENT-1011'"
	elif enum_value == BDATA_LOG_REQ:
		value_str = "'BDATA_LOG_REQ-2001'"
	elif enum_value == BDATA_LOG_RSP:
		value_str = "'BDATA_LOG_RSP-2002'"
	elif enum_value == APPMSG_MCARD_REQ:
		value_str = "'APPMSG_MCARD_REQ-2053'"
	elif enum_value == APPMSG_MCARD_RSP:
		value_str = "'APPMSG_MCARD_RSP-2054'"
	elif enum_value == APPMSG_TALK_MCARD_REQ:
		value_str = "'APPMSG_TALK_MCARD_REQ-2085'"
	elif enum_value == APPMSG_TALK_MCARD_RSP:
		value_str = "'APPMSG_TALK_MCARD_RSP-2086'"
	elif enum_value == UIP_REGISTER_REQ:
		value_str = "'UIP_REGISTER_REQ-2110'"
	elif enum_value == UIP_REGISTER_RSP:
		value_str = "'UIP_REGISTER_RSP-2111'"
	elif enum_value == UIP_UNREGISTER_REQ:
		value_str = "'UIP_UNREGISTER_REQ-2112'"
	elif enum_value == UIP_UNREGISTER_RSP:
		value_str = "'UIP_UNREGISTER_RSP-2113'"
	elif enum_value == UIP_DATA_RECV_REQ:
		value_str = "'UIP_DATA_RECV_REQ-2114'"
	elif enum_value == UIP_DATA_RECV_RSP:
		value_str = "'UIP_DATA_RECV_RSP-2115'"
	elif enum_value == UIP_DATA_SEND_REQ:
		value_str = "'UIP_DATA_SEND_REQ-2130'"
	elif enum_value == UIP_DATA_SEND_RSP:
		value_str = "'UIP_DATA_SEND_RSP-2131'"
	elif enum_value == APPMSG_FUNCTION_REGISTER_REQ:
		value_str = "'APPMSG_FUNCTION_REGISTER_REQ-2132'"
	elif enum_value == APPMSG_FUNCTION_REGISTER_RSP:
		value_str = "'APPMSG_FUNCTION_REGISTER_RSP-2133'"
	elif enum_value == APPMSG_FUNCTION_UNREGISTER_REQ:
		value_str = "'APPMSG_FUNCTION_UNREGISTER_REQ-2134'"
	elif enum_value == APPMSG_FUNCTION_UNREGISTER_RSP:
		value_str = "'APPMSG_FUNCTION_UNREGISTER_RSP-2135'"
	elif enum_value == STORE_MYSQL_REQ:
		value_str = "'STORE_MYSQL_REQ-3001'"
	elif enum_value == STORE_MYSQL_RSP:
		value_str = "'STORE_MYSQL_RSP-3002'"
	elif enum_value == DBMSG_SYS_INQ_CHANNEL_REQ:
		value_str = "'DBMSG_SYS_INQ_CHANNEL_REQ-4029'"
	elif enum_value == DBMSG_SYS_INQ_CHANNEL_RSP:
		value_str = "'DBMSG_SYS_INQ_CHANNEL_RSP-4030'"
	elif enum_value == DBMSG_SYS_INQ_IMAGE_REQ:
		value_str = "'DBMSG_SYS_INQ_IMAGE_REQ-4212'"
	elif enum_value == DBMSG_SYS_INQ_IMAGE_RSP:
		value_str = "'DBMSG_SYS_INQ_IMAGE_RSP-4213'"
	elif enum_value == DBMSG_SYS_INQ_MUSEUM_REQ:
		value_str = "'DBMSG_SYS_INQ_MUSEUM_REQ-4214'"
	elif enum_value == DBMSG_SYS_INQ_MUSEUM_RSP:
		value_str = "'DBMSG_SYS_INQ_MUSEUM_RSP-4215'"
	elif enum_value == DBMSG_SYS_INQ_MUSEUM_PAGE_REQ:
		value_str = "'DBMSG_SYS_INQ_MUSEUM_PAGE_REQ-4226'"
	elif enum_value == DBMSG_SYS_INQ_MUSEUM_PAGE_RSP:
		value_str = "'DBMSG_SYS_INQ_MUSEUM_PAGE_RSP-4227'"
	elif enum_value == DBMSG_SYS_ADD_WEICHAT_REQ:
		value_str = "'DBMSG_SYS_ADD_WEICHAT_REQ-4222'"
	elif enum_value == DBMSG_SYS_ADD_WEICHAT_RSP:
		value_str = "'DBMSG_SYS_ADD_WEICHAT_RSP-4223'"
	elif enum_value == DBMSG_SYS_INQ_WEICHAT_REQ:
		value_str = "'DBMSG_SYS_INQ_WEICHAT_REQ-4224'"
	elif enum_value == DBMSG_SYS_INQ_WEICHAT_RSP:
		value_str = "'DBMSG_SYS_INQ_WEICHAT_RSP-4225'"
	elif enum_value == DBMSG_SYS_INQ_PAINTER_PAGE_REQ:
		value_str = "'DBMSG_SYS_INQ_PAINTER_PAGE_REQ-4230'"
	elif enum_value == DBMSG_SYS_INQ_PAINTER_PAGE_RSP:
		value_str = "'DBMSG_SYS_INQ_PAINTER_PAGE_RSP-4231'"
	elif enum_value == DBMSG_NOSQL_ADD_TALK_REQ:
		value_str = "'DBMSG_NOSQL_ADD_TALK_REQ-4175'"
	elif enum_value == DBMSG_NOSQL_ADD_TALK_RSP:
		value_str = "'DBMSG_NOSQL_ADD_TALK_RSP-4176'"
	elif enum_value == DBMSG_REDIS_DEL_TABLE_REQ:
		value_str = "'DBMSG_REDIS_DEL_TABLE_REQ-4131'"
	elif enum_value == DBMSG_REDIS_DEL_TABLE_RSP:
		value_str = "'DBMSG_REDIS_DEL_TABLE_RSP-4132'"
	elif enum_value == DBMSG_SYS_ADD_IMAGE_FEATURE_REQ:
		value_str = "'DBMSG_SYS_ADD_IMAGE_FEATURE_REQ-4190'"
	elif enum_value == DBMSG_SYS_ADD_IMAGE_FEATURE_RSP:
		value_str = "'DBMSG_SYS_ADD_IMAGE_FEATURE_RSP-4191'"
	elif enum_value == DBMSG_SYS_INQ_IMAGE_FEATURE_REQ:
		value_str = "'DBMSG_SYS_INQ_IMAGE_FEATURE_REQ-4192'"
	elif enum_value == DBMSG_SYS_INQ_IMAGE_FEATURE_RSP:
		value_str = "'DBMSG_SYS_INQ_IMAGE_FEATURE_RSP-4193'"
	elif enum_value == DBMSG_HYBRID_ADD_LIST_REQ:
		value_str = "'DBMSG_HYBRID_ADD_LIST_REQ-4077'"
	elif enum_value == DBMSG_HYBRID_ADD_LIST_RSP:
		value_str = "'DBMSG_HYBRID_ADD_LIST_RSP-4078'"
	elif enum_value == DBMSG_HYBRID_INQ_LIST_REQ:
		value_str = "'DBMSG_HYBRID_INQ_LIST_REQ-4079'"
	elif enum_value == DBMSG_HYBRID_INQ_LIST_RSP:
		value_str = "'DBMSG_HYBRID_INQ_LIST_RSP-4080'"
	elif enum_value == MAINMSG_IM_USER_REG_REQ:
		value_str = "'MAINMSG_IM_USER_REG_REQ-5034'"
	elif enum_value == MAINMSG_IM_USER_REG_RSP:
		value_str = "'MAINMSG_IM_USER_REG_RSP-5035'"
	elif enum_value == MAINMSG_IM_USER_DEREG_REQ:
		value_str = "'MAINMSG_IM_USER_DEREG_REQ-5036'"
	elif enum_value == MAINMSG_IM_USER_DEREG_RSP:
		value_str = "'MAINMSG_IM_USER_DEREG_RSP-5037'"
	elif enum_value == MAINMSG_IM_USER_INQ_REQ:
		value_str = "'MAINMSG_IM_USER_INQ_REQ-5038'"
	elif enum_value == MAINMSG_IM_USER_INQ_RSP:
		value_str = "'MAINMSG_IM_USER_INQ_RSP-5039'"
	elif enum_value == MAINMSG_ADD_CHANNEL_REQ:
		value_str = "'MAINMSG_ADD_CHANNEL_REQ-5013'"
	elif enum_value == MAINMSG_ADD_CHANNEL_RSP:
		value_str = "'MAINMSG_ADD_CHANNEL_RSP-5014'"
	elif enum_value == MAINMSG_DEL_CHANNEL_REQ:
		value_str = "'MAINMSG_DEL_CHANNEL_REQ-5015'"
	elif enum_value == MAINMSG_DEL_CHANNEL_RSP:
		value_str = "'MAINMSG_DEL_CHANNEL_RSP-5016'"
	elif enum_value == MAINMSG_INQ_CHANNEL_REQ:
		value_str = "'MAINMSG_INQ_CHANNEL_REQ-5017'"
	elif enum_value == MAINMSG_INQ_CHANNEL_RSP:
		value_str = "'MAINMSG_INQ_CHANNEL_RSP-5018'"
	elif enum_value == MAINMSG_REC_CHANNEL_REQ:
		value_str = "'MAINMSG_REC_CHANNEL_REQ-5019'"
	elif enum_value == MAINMSG_REC_CHANNEL_RSP:
		value_str = "'MAINMSG_REC_CHANNEL_RSP-5020'"
	elif enum_value == MAINMSG_ADD_CHANNEL_CMD_REQ:
		value_str = "'MAINMSG_ADD_CHANNEL_CMD_REQ-5040'"
	elif enum_value == MAINMSG_ADD_CHANNEL_CMD_RSP:
		value_str = "'MAINMSG_ADD_CHANNEL_CMD_RSP-5041'"
	elif enum_value == MAINMSG_DEL_CHANNEL_CMD_REQ:
		value_str = "'MAINMSG_DEL_CHANNEL_CMD_REQ-5042'"
	elif enum_value == MAINMSG_DEL_CHANNEL_CMD_RSP:
		value_str = "'MAINMSG_DEL_CHANNEL_CMD_RSP-5043'"
	elif enum_value == MAINMSG_INQ_CHANNEL_CMD_REQ:
		value_str = "'MAINMSG_INQ_CHANNEL_CMD_REQ-5044'"
	elif enum_value == MAINMSG_INQ_CHANNEL_CMD_RSP:
		value_str = "'MAINMSG_INQ_CHANNEL_CMD_RSP-5045'"
	elif enum_value == MAINMSG_ADD_CHANNEL_FORBIDDEN_CMD_REQ:
		value_str = "'MAINMSG_ADD_CHANNEL_FORBIDDEN_CMD_REQ-5129'"
	elif enum_value == MAINMSG_ADD_CHANNEL_FORBIDDEN_CMD_RSP:
		value_str = "'MAINMSG_ADD_CHANNEL_FORBIDDEN_CMD_RSP-5130'"
	elif enum_value == MAINMSG_DEL_CHANNEL_FORBIDDEN_CMD_REQ:
		value_str = "'MAINMSG_DEL_CHANNEL_FORBIDDEN_CMD_REQ-5131'"
	elif enum_value == MAINMSG_DEL_CHANNEL_FORBIDDEN_CMD_RSP:
		value_str = "'MAINMSG_DEL_CHANNEL_FORBIDDEN_CMD_RSP-5132'"
	elif enum_value == MAINMSG_INQ_CHANNEL_FORBIDDEN_CMD_REQ:
		value_str = "'MAINMSG_INQ_CHANNEL_FORBIDDEN_CMD_REQ-5133'"
	elif enum_value == MAINMSG_TALK_MCARD_REQ:
		value_str = "'MAINMSG_TALK_MCARD_REQ-5106'"
	elif enum_value == MAINMSG_TALK_MCARD_RSP:
		value_str = "'MAINMSG_TALK_MCARD_RSP-5107'"
	elif enum_value == MAINMSG_PYTHON_REQ:
		value_str = "'MAINMSG_PYTHON_REQ-5135'"
	elif enum_value == MAINMSG_PYTHON_RSP:
		value_str = "'MAINMSG_PYTHON_RSP-5136'"
	elif enum_value == CVMSG_IMAGE_SEARCH_REQ:
		value_str = "'CVMSG_IMAGE_SEARCH_REQ-10001'"
	elif enum_value == CVMSG_IMAGE_SEARCH_RSP:
		value_str = "'CVMSG_IMAGE_SEARCH_RSP-10002'"
	elif enum_value == CVMSG_FEATURES_DETECTED_REQ:
		value_str = "'CVMSG_FEATURES_DETECTED_REQ-10003'"
	elif enum_value == CVMSG_FEATURES_DETECTED_RSP:
		value_str = "'CVMSG_FEATURES_DETECTED_RSP-10004'"
	elif enum_value == CVMSG_PAINTING_AESTHETICS_REQ:
		value_str = "'CVMSG_PAINTING_AESTHETICS_REQ-10005'"
	elif enum_value == CVMSG_PAINTING_AESTHETICS_RSP:
		value_str = "'CVMSG_PAINTING_AESTHETICS_RSP-10006'"
	elif enum_value == CVMSG_SCULPTURES_SEARCH_REQ:
		value_str = "'CVMSG_SCULPTURES_SEARCH_REQ-10007'"
	elif enum_value == CVMSG_SCULPTURES_SEARCH_RSP:
		value_str = "'CVMSG_SCULPTURES_SEARCH_RSP-10008'"
	elif enum_value == HTTPMSG_POST_REQ:
		value_str = "'HTTPMSG_POST_REQ-11000'"
	elif enum_value == HTTPMSG_POST_RSP:
		value_str = "'HTTPMSG_POST_RSP-11001'"
	elif enum_value == HTTPMSG_LISTEN_REQ:
		value_str = "'HTTPMSG_LISTEN_REQ-11002'"
	elif enum_value == HTTPMSG_LISTEN_RSP:
		value_str = "'HTTPMSG_LISTEN_RSP-11003'"
	elif enum_value == HTTPMSG_CLOSE_REQ:
		value_str = "'HTTPMSG_CLOSE_REQ-11004'"
	elif enum_value == HTTPMSG_CLOSE_RSP:
		value_str = "'HTTPMSG_CLOSE_RSP-11005'"
	elif enum_value == HTTPMSG_RECV_REQ:
		value_str = "'HTTPMSG_RECV_REQ-11006'"
	elif enum_value == HTTPMSG_RECV_RSP:
		value_str = "'HTTPMSG_RECV_RSP-11007'"
	elif enum_value == HTTPMSG_LISTEN_AUTO_CLOSE_REQ:
		value_str = "'HTTPMSG_LISTEN_AUTO_CLOSE_REQ-11008'"
	elif enum_value == HTTPMSG_LISTEN_AUTO_CLOSE_RSP:
		value_str = "'HTTPMSG_LISTEN_AUTO_CLOSE_RSP-11009'"
	elif enum_value == AIXMSG_IMAGE_CLASSIFICATION_REQ:
		value_str = "'AIXMSG_IMAGE_CLASSIFICATION_REQ-12001'"
	elif enum_value == AIXMSG_IMAGE_CLASSIFICATION_RSP:
		value_str = "'AIXMSG_IMAGE_CLASSIFICATION_RSP-12002'"
	elif enum_value == AIXMSG_AESTHETICS_REQ:
		value_str = "'AIXMSG_AESTHETICS_REQ-12003'"
	elif enum_value == AIXMSG_AESTHETICS_RSP:
		value_str = "'AIXMSG_AESTHETICS_RSP-12004'"
	elif enum_value == BBSMSG_ADD_COMMENT_REQ:
		value_str = "'BBSMSG_ADD_COMMENT_REQ-15001'"
	elif enum_value == BBSMSG_ADD_COMMENT_RSP:
		value_str = "'BBSMSG_ADD_COMMENT_RSP-15002'"
	elif enum_value == BBSMSG_INQ_COMMENT_REQ:
		value_str = "'BBSMSG_INQ_COMMENT_REQ-15003'"
	elif enum_value == BBSMSG_INQ_COMMENT_RSP:
		value_str = "'BBSMSG_INQ_COMMENT_RSP-15004'"
	elif enum_value == MSGID_INVALID:
		value_str = "'MSGID_INVALID-0x1fffffffffffffff'"
	else:
		value_str = f'{enum_value}'
	return value_str


