#!/bin/bash
#/*
# * Copyright (c) 2022 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# */

ARCH=`arch`

if [ "$ARCH" == "x86_64" ]; then
   GOARCH=amd64
elif [ "$ARCH" == "aarch64" ]; then
   GOARCH=arm64
else
   echo Please define the GOARCH!
fi

GOOS=linux GOARCH=${GOARCH} go build -o nsd ./cmd/nsd/main.go
GOOS=linux GOARCH=${GOARCH} go build -o nscli ./cmd/nscli/main.go