# -*- coding: utf-8 -*-
#/*
# * Copyright (c) 2022 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# *
# * ############################# IMPORTANT INFORMATION ############################
# * The code of this file is automatically generated by tools(Tools/auto_code),
# * please do not modify it manually!
# * ############################# IMPORTANT INFORMATION ############################
# * ================================================================================
# */

from ctypes import *

DAVE_THREAD_NAME_LEN = 32
DAVE_GLOBALLY_IDENTIFIER_LEN = 33
DAVE_VERNO_STR_LEN = 64
DAVE_NORMAL_NAME_LEN = 128
DAVE_URL_LEN = 128
DAVE_BUILDING_BLOCKS_MAX = 255
DAVE_PATH_LEN = 256
DAVE_HTTP_KEY_LEN = 128
DAVE_HTTP_VALUE_LEN = 512
DAVE_HTTP_HEAD_MAX = 16
