#!/bin/bash
#/*
# * Copyright (c) 2024 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# */

if [ ! -f ./libwasmvm.x86_64.so ]; then
    chmod a+x wasmvm-build && ./wasmvm-build
fi

chmod a+x wormhole-build && ./wormhole-build