#!/bin/bash
#/*
# * Copyright (c) 2023 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# */

PROJECTDIR=/project
POLYGONDIR=${PROJECTDIR}/polygon
POLYGONBIN=${PROJECTDIR}/polygon-edge
GRPCPORT=30000
NODEPORT=30001
JSONPORT=30002
File=$(basename $0)

if [ ! -d ${POLYGONDIR} ]; then
   ./INIT ${PROJECTDIR} ${POLYGONDIR} ${POLYGONBIN} ${NODEPORT}
fi

echo ${File} server start!
${POLYGONBIN} server --data-dir ${POLYGONDIR} --chain genesis.json --grpc-address :${GRPCPORT} --libp2p :${NODEPORT} --jsonrpc :${JSONPORT} --seal