/*
 * Copyright (c) 2022 Renwei
 *
 * This is a free software; you can redistribute it and/or modify
 * it under the terms of the MIT license. See LICENSE for details.
 *
 * ############################# IMPORTANT INFORMATION ############################
 * The code of this file is automatically generated by tools(Tools/auto_code),
 * please do not modify it manually!
 * ############################# IMPORTANT INFORMATION ############################
 * ================================================================================
 */

#ifndef __T_AUTO_ENUMSTR__
#define __T_AUTO_ENUMSTR__
#include "dave_base.h"
#include "database_msg.h"
#include "cv_param.h"
#include "dave_enum.h"
#include "dave_error_code.h"
#include "dave_mcard.h"
#include "http_param.h"
#include "uip_msg.h"
#include "base_ramkv.h"
#include "base_thread.h"
#include "base_enum.h"
#include "base_retcode.h"
#include "base_rxtx.h"
#include "rxtx_param.h"
#include "socket_parameters.h"
#include "sync_param.h"
#include "sync_type.h"

s8 *t_auto_AESKeyBin_str(AESKeyBin enum_value);
s8 *t_auto_AIPlaceType_str(AIPlaceType enum_value);
s8 *t_auto_AIVisionType_str(AIVisionType enum_value);
s8 *t_auto_AudioCodec_str(AudioCodec enum_value);
s8 *t_auto_AuthType_str(AuthType enum_value);
s8 *t_auto_BaseMsgType_str(BaseMsgType enum_value);
s8 *t_auto_BillingAddressType_str(BillingAddressType enum_value);
s8 *t_auto_BillingEvent_str(BillingEvent enum_value);
s8 *t_auto_BillingMeasurementUnit_str(BillingMeasurementUnit enum_value);
s8 *t_auto_BillingRechargeType_str(BillingRechargeType enum_value);
s8 *t_auto_BillingRulesAttrib_str(BillingRulesAttrib enum_value);
s8 *t_auto_BillingRulesPriority_str(BillingRulesPriority enum_value);
s8 *t_auto_BillingRulesType_str(BillingRulesType enum_value);
s8 *t_auto_BillingType_str(BillingType enum_value);
s8 *t_auto_BuildingBlocksOpt_str(BuildingBlocksOpt enum_value);
s8 *t_auto_CVSearchOpt_str(CVSearchOpt enum_value);
s8 *t_auto_CallFunctionType_str(CallFunctionType enum_value);
s8 *t_auto_CallingNumberFlag_str(CallingNumberFlag enum_value);
s8 *t_auto_CountryCode_str(CountryCode enum_value);
s8 *t_auto_CurrencyType_str(CurrencyType enum_value);
s8 *t_auto_DBInqType_str(DBInqType enum_value);
s8 *t_auto_DaveDataType_str(DaveDataType enum_value);
s8 *t_auto_DaveJsonType_str(DaveJsonType enum_value);
s8 *t_auto_EnableKeepAliveFlag_str(EnableKeepAliveFlag enum_value);
s8 *t_auto_EnableNetCardBindFlag_str(EnableNetCardBindFlag enum_value);
s8 *t_auto_EnvironmentFlag_str(EnvironmentFlag enum_value);
s8 *t_auto_ErrCode_str(ErrCode enum_value);
s8 *t_auto_FRAMETYPE_str(FRAMETYPE enum_value);
s8 *t_auto_FRAME_TYPE_str(FRAME_TYPE enum_value);
s8 *t_auto_FileOptFlag_str(FileOptFlag enum_value);
s8 *t_auto_FixedPortFlag_str(FixedPortFlag enum_value);
s8 *t_auto_GPSBaseLocation_str(GPSBaseLocation enum_value);
s8 *t_auto_GuardianMailLevel_str(GuardianMailLevel enum_value);
s8 *t_auto_HTTPListenType_str(HTTPListenType enum_value);
s8 *t_auto_HTTPMathcRule_str(HTTPMathcRule enum_value);
s8 *t_auto_HttpContentType_str(HttpContentType enum_value);
s8 *t_auto_HttpMethod_str(HttpMethod enum_value);
s8 *t_auto_IOStackType_str(IOStackType enum_value);
s8 *t_auto_IPProtocol_str(IPProtocol enum_value);
s8 *t_auto_IPVER_str(IPVER enum_value);
s8 *t_auto_JuphoonBindingStatus_str(JuphoonBindingStatus enum_value);
s8 *t_auto_JuphoonNoticeType_str(JuphoonNoticeType enum_value);
s8 *t_auto_KvAttrib_str(KvAttrib enum_value);
s8 *t_auto_LanguageCode_str(LanguageCode enum_value);
s8 *t_auto_MCardContentType_str(MCardContentType enum_value);
s8 *t_auto_MCardIdentityType_str(MCardIdentityType enum_value);
s8 *t_auto_MCardSource_str(MCardSource enum_value);
s8 *t_auto_MCardTimeType_str(MCardTimeType enum_value);
s8 *t_auto_MCardType_str(MCardType enum_value);
s8 *t_auto_MCardVer_str(MCardVer enum_value);
s8 *t_auto_MainReqSrcType_str(MainReqSrcType enum_value);
s8 *t_auto_MatrixOpt_str(MatrixOpt enum_value);
s8 *t_auto_ModImpuFlag_str(ModImpuFlag enum_value);
s8 *t_auto_MsgMemState_str(MsgMemState enum_value);
s8 *t_auto_MsisdnOperator_str(MsisdnOperator enum_value);
s8 *t_auto_NetAddrType_str(NetAddrType enum_value);
s8 *t_auto_NumberReqType_str(NumberReqType enum_value);
s8 *t_auto_NumberType_str(NumberType enum_value);
s8 *t_auto_ORDER_CODE_str(ORDER_CODE enum_value);
s8 *t_auto_PRODUC_str(PRODUC enum_value);
s8 *t_auto_PackageStatus_str(PackageStatus enum_value);
s8 *t_auto_PhoneNumberType_str(PhoneNumberType enum_value);
s8 *t_auto_PowerMode_str(PowerMode enum_value);
s8 *t_auto_PythonFun_str(PythonFun enum_value);
s8 *t_auto_RESTPushEventType_str(RESTPushEventType enum_value);
s8 *t_auto_RNMBusinessType_str(RNMBusinessType enum_value);
s8 *t_auto_RNMQueryType_str(RNMQueryType enum_value);
s8 *t_auto_ReportMsgType_str(ReportMsgType enum_value);
s8 *t_auto_ReqType_str(ReqType enum_value);
s8 *t_auto_RetCode_str(RetCode enum_value);
s8 *t_auto_SIPCallType_str(SIPCallType enum_value);
s8 *t_auto_SIPConfType_str(SIPConfType enum_value);
s8 *t_auto_SIPTransportType_str(SIPTransportType enum_value);
s8 *t_auto_SMSCodingType_str(SMSCodingType enum_value);
s8 *t_auto_SMSMsgState_str(SMSMsgState enum_value);
s8 *t_auto_SMSOperatorCode_str(SMSOperatorCode enum_value);
s8 *t_auto_SMSPriority_str(SMSPriority enum_value);
s8 *t_auto_SMSSignatureType_str(SMSSignatureType enum_value);
s8 *t_auto_SMSType_str(SMSType enum_value);
s8 *t_auto_SOCCNTTYPE_str(SOCCNTTYPE enum_value);
s8 *t_auto_SOCDOMAIN_str(SOCDOMAIN enum_value);
s8 *t_auto_SOCEVENT_str(SOCEVENT enum_value);
s8 *t_auto_SOCKETINFO_str(SOCKETINFO enum_value);
s8 *t_auto_SOCKETTYPE_str(SOCKETTYPE enum_value);
s8 *t_auto_SOCTYPE_str(SOCTYPE enum_value);
s8 *t_auto_SYNCType_str(SYNCType enum_value);
s8 *t_auto_SyncNotifyEnum_str(SyncNotifyEnum enum_value);
s8 *t_auto_SyncServerType_str(SyncServerType enum_value);
s8 *t_auto_TaskAttribute_str(TaskAttribute enum_value);
s8 *t_auto_TextCoding_str(TextCoding enum_value);
s8 *t_auto_TimeType_str(TimeType enum_value);
s8 *t_auto_TraceLevel_str(TraceLevel enum_value);
s8 *t_auto_UIPSocketType_str(UIPSocketType enum_value);
s8 *t_auto_UIPType_str(UIPType enum_value);
s8 *t_auto_UserType_str(UserType enum_value);
s8 *t_auto_VERLEVEL_str(VERLEVEL enum_value);
s8 *t_auto_VoIPForwardSettingType_str(VoIPForwardSettingType enum_value);
s8 *t_auto_RPCMSG_str(RPCMSG enum_value);

#endif
