/*
 * Copyright (c) 2022 Renwei
 *
 * This is a free software; you can redistribute it and/or modify
 * it under the terms of the MIT license. See LICENSE for details.
 *
 * ############################# IMPORTANT INFORMATION ############################
 * The code of this file is automatically generated by tools(Tools/auto_code),
 * please do not modify it manually!
 * ############################# IMPORTANT INFORMATION ############################
 * ================================================================================
 */

#include "dave_base.h"
#include "dave_os.h"
#include "dave_tools.h"
#include "dave_3rdparty.h"
#include "t_rpc_ver3_enumdata.h"
#include "t_rpc_ver3_metadata.h"
#include "t_rpc_ver3_structdata.h"
#include "tools_log.h"
#include "cv_param.h"
#include "dave_mcard.h"
#include "dave_struct.h"
#include "http_param.h"
#include "base_struct.h"

// =====================================================================

void *
t_rpc_ver3_zip_MCardVerText(MCardVerText *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "MCardVer-version", t_rpc_ver3_zip_MCardVer(zip_data->version));
	t_bson_add_object(pStructBson, "MCardType-type", t_rpc_ver3_zip_MCardType(zip_data->type));
	t_bson_add_object(pStructBson, "s8-user", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->user), 1, DAVE_USER_NAME_LEN));
	t_bson_add_object(pStructBson, "MCardLocation-location", t_rpc_ver3_zip_MCardLocation(&(zip_data->location)));
	t_bson_add_object(pStructBson, "MCardTime-time", t_rpc_ver3_zip_MCardTime(&(zip_data->time)));
	t_bson_add_object(pStructBson, "MBUF-utf8_txt", t_rpc_ver3_zip_MBUF_ptr(zip_data->utf8_txt));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MCardVerText(MCardVerText *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MCardVerText");
		dave_memset(unzip_data, 0x00, sizeof(MCardVerText));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_MCardVer(&(unzip_data->version), t_bson_inq_object(pStructBson, "MCardVer-version"));
		t_rpc_ver3_unzip_MCardType(&(unzip_data->type), t_bson_inq_object(pStructBson, "MCardType-type"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->user), 1, DAVE_USER_NAME_LEN, t_bson_inq_object(pStructBson, "s8-user"));
		t_rpc_ver3_unzip_MCardLocation(&(unzip_data->location), t_bson_inq_object(pStructBson, "MCardLocation-location"));
		t_rpc_ver3_unzip_MCardTime(&(unzip_data->time), t_bson_inq_object(pStructBson, "MCardTime-time"));
		t_rpc_ver3_unzip_MBUF_ptr(&(unzip_data->utf8_txt), t_bson_inq_object(pStructBson, "MBUF-utf8_txt"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MCardVerText_d(MCardVerText *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MCardVerText(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MCardVerText_d(MCardVerText *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MCardVerText));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MCardVerText(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MCardVerMedia(MCardVerMedia *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "MCardVer-version", t_rpc_ver3_zip_MCardVer(zip_data->version));
	t_bson_add_object(pStructBson, "MCardType-type", t_rpc_ver3_zip_MCardType(zip_data->type));
	t_bson_add_object(pStructBson, "MCardSource-source", t_rpc_ver3_zip_MCardSource(zip_data->source));
	t_bson_add_object(pStructBson, "MCardPOI-poi", t_rpc_ver3_zip_MCardPOI(&(zip_data->poi)));
	t_bson_add_object(pStructBson, "s8-author_name", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->author_name), 1, DAVE_USER_NAME_LEN));
	t_bson_add_object(pStructBson, "s8-author_url", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->author_url), 1, DAVE_URL_LEN));
	t_bson_add_object(pStructBson, "LanguageCode-language", t_rpc_ver3_zip_LanguageCode(zip_data->language));
	t_bson_add_object(pStructBson, "s8-author_photo_url", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->author_photo_url), 1, DAVE_URL_LEN));
	t_bson_add_object(pStructBson, "double-rating", t_rpc_ver3_zip_double(zip_data->rating));
	t_bson_add_object(pStructBson, "MBUF-utf8_txt", t_rpc_ver3_zip_MBUF_ptr(zip_data->utf8_txt));
	t_bson_add_object(pStructBson, "ub-second", t_rpc_ver3_zip_ub(zip_data->second));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MCardVerMedia(MCardVerMedia *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MCardVerMedia");
		dave_memset(unzip_data, 0x00, sizeof(MCardVerMedia));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_MCardVer(&(unzip_data->version), t_bson_inq_object(pStructBson, "MCardVer-version"));
		t_rpc_ver3_unzip_MCardType(&(unzip_data->type), t_bson_inq_object(pStructBson, "MCardType-type"));
		t_rpc_ver3_unzip_MCardSource(&(unzip_data->source), t_bson_inq_object(pStructBson, "MCardSource-source"));
		t_rpc_ver3_unzip_MCardPOI(&(unzip_data->poi), t_bson_inq_object(pStructBson, "MCardPOI-poi"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->author_name), 1, DAVE_USER_NAME_LEN, t_bson_inq_object(pStructBson, "s8-author_name"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->author_url), 1, DAVE_URL_LEN, t_bson_inq_object(pStructBson, "s8-author_url"));
		t_rpc_ver3_unzip_LanguageCode(&(unzip_data->language), t_bson_inq_object(pStructBson, "LanguageCode-language"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->author_photo_url), 1, DAVE_URL_LEN, t_bson_inq_object(pStructBson, "s8-author_photo_url"));
		t_rpc_ver3_unzip_double(&(unzip_data->rating), t_bson_inq_object(pStructBson, "double-rating"));
		t_rpc_ver3_unzip_MBUF_ptr(&(unzip_data->utf8_txt), t_bson_inq_object(pStructBson, "MBUF-utf8_txt"));
		t_rpc_ver3_unzip_ub(&(unzip_data->second), t_bson_inq_object(pStructBson, "ub-second"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MCardVerMedia_d(MCardVerMedia *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MCardVerMedia(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MCardVerMedia_d(MCardVerMedia *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MCardVerMedia));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MCardVerMedia(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MCardVerComment(MCardVerComment *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "MCardVer-version", t_rpc_ver3_zip_MCardVer(zip_data->version));
	t_bson_add_object(pStructBson, "MCardCommentHead-head", t_rpc_ver3_zip_MCardCommentHead(&(zip_data->head)));
	t_bson_add_object(pStructBson, "MCardContent-content", t_rpc_ver3_zip_MCardContent(&(zip_data->content)));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MCardVerComment(MCardVerComment *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MCardVerComment");
		dave_memset(unzip_data, 0x00, sizeof(MCardVerComment));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_MCardVer(&(unzip_data->version), t_bson_inq_object(pStructBson, "MCardVer-version"));
		t_rpc_ver3_unzip_MCardCommentHead(&(unzip_data->head), t_bson_inq_object(pStructBson, "MCardCommentHead-head"));
		t_rpc_ver3_unzip_MCardContent(&(unzip_data->content), t_bson_inq_object(pStructBson, "MCardContent-content"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MCardVerComment_d(MCardVerComment *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MCardVerComment(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MCardVerComment_d(MCardVerComment *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MCardVerComment));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MCardVerComment(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MCardLocation(MCardLocation *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "double-latitude", t_rpc_ver3_zip_double(zip_data->latitude));
	t_bson_add_object(pStructBson, "double-longitude", t_rpc_ver3_zip_double(zip_data->longitude));
	t_bson_add_object(pStructBson, "double-altitude", t_rpc_ver3_zip_double(zip_data->altitude));
	t_bson_add_object(pStructBson, "double-course", t_rpc_ver3_zip_double(zip_data->course));
	t_bson_add_object(pStructBson, "double-slope", t_rpc_ver3_zip_double(zip_data->slope));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MCardLocation(MCardLocation *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MCardLocation");
		dave_memset(unzip_data, 0x00, sizeof(MCardLocation));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_double(&(unzip_data->latitude), t_bson_inq_object(pStructBson, "double-latitude"));
		t_rpc_ver3_unzip_double(&(unzip_data->longitude), t_bson_inq_object(pStructBson, "double-longitude"));
		t_rpc_ver3_unzip_double(&(unzip_data->altitude), t_bson_inq_object(pStructBson, "double-altitude"));
		t_rpc_ver3_unzip_double(&(unzip_data->course), t_bson_inq_object(pStructBson, "double-course"));
		t_rpc_ver3_unzip_double(&(unzip_data->slope), t_bson_inq_object(pStructBson, "double-slope"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MCardLocation_d(MCardLocation *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MCardLocation(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MCardLocation_d(MCardLocation *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MCardLocation));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MCardLocation(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MCardTime(MCardTime *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "DateStruct-write_time", t_rpc_ver3_zip_DateStruct(&(zip_data->write_time)));
	t_bson_add_object(pStructBson, "MCardTimeType-failure_type", t_rpc_ver3_zip_MCardTimeType(zip_data->failure_type));
	t_bson_add_object(pStructBson, "DateStruct-failure_time", t_rpc_ver3_zip_DateStruct(&(zip_data->failure_time)));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MCardTime(MCardTime *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MCardTime");
		dave_memset(unzip_data, 0x00, sizeof(MCardTime));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_DateStruct(&(unzip_data->write_time), t_bson_inq_object(pStructBson, "DateStruct-write_time"));
		t_rpc_ver3_unzip_MCardTimeType(&(unzip_data->failure_type), t_bson_inq_object(pStructBson, "MCardTimeType-failure_type"));
		t_rpc_ver3_unzip_DateStruct(&(unzip_data->failure_time), t_bson_inq_object(pStructBson, "DateStruct-failure_time"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MCardTime_d(MCardTime *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MCardTime(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MCardTime_d(MCardTime *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MCardTime));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MCardTime(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MCardContent(MCardContent *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "MCardIdentityType-id", t_rpc_ver3_zip_MCardIdentityType(zip_data->id));
	t_bson_add_object(pStructBson, "MCardContentType-content_type", t_rpc_ver3_zip_MCardContentType(zip_data->content_type));
	t_bson_add_object(pStructBson, "LanguageCode-content_language", t_rpc_ver3_zip_LanguageCode(zip_data->content_language));
	t_bson_add_object(pStructBson, "MBUF-pContent", t_rpc_ver3_zip_MBUF_ptr(zip_data->pContent));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MCardContent(MCardContent *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MCardContent");
		dave_memset(unzip_data, 0x00, sizeof(MCardContent));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_MCardIdentityType(&(unzip_data->id), t_bson_inq_object(pStructBson, "MCardIdentityType-id"));
		t_rpc_ver3_unzip_MCardContentType(&(unzip_data->content_type), t_bson_inq_object(pStructBson, "MCardContentType-content_type"));
		t_rpc_ver3_unzip_LanguageCode(&(unzip_data->content_language), t_bson_inq_object(pStructBson, "LanguageCode-content_language"));
		t_rpc_ver3_unzip_MBUF_ptr(&(unzip_data->pContent), t_bson_inq_object(pStructBson, "MBUF-pContent"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MCardContent_d(MCardContent *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MCardContent(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MCardContent_d(MCardContent *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MCardContent));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MCardContent(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_CVModelResult(CVModelResult *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "CVSearchOpt-search_opt", t_rpc_ver3_zip_CVSearchOpt(zip_data->search_opt));
	t_bson_add_object(pStructBson, "MCardContentType-content_type", t_rpc_ver3_zip_MCardContentType(zip_data->content_type));
	t_bson_add_object(pStructBson, "LanguageCode-language_code", t_rpc_ver3_zip_LanguageCode(zip_data->language_code));
	t_bson_add_object(pStructBson, "s8-image_local_path", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->image_local_path), 1, DAVE_PATH_LEN));
	t_bson_add_object(pStructBson, "s8-image_url_path", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->image_url_path), 1, DAVE_PATH_LEN));
	t_bson_add_object(pStructBson, "ub-opt_number", t_rpc_ver3_zip_ub(zip_data->opt_number));
	t_bson_add_object(pStructBson, "ub-face_number", t_rpc_ver3_zip_ub(zip_data->face_number));
	t_bson_add_object(pStructBson, "s8-vgg_id", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->vgg_id), DAVE_KEY_OPT_MAX, DAVE_SHA1_IMAGE_ID));
	t_bson_add_object(pStructBson, "float-vgg_score", t_rpc_ver3_zip_float_d((float *)(zip_data->vgg_score), DAVE_KEY_OPT_MAX));
	t_bson_add_object(pStructBson, "CVRectangle-rectangle", t_rpc_ver3_zip_CVRectangle_d(zip_data->rectangle, DAVE_KEY_OPT_MAX));
	t_bson_add_object(pStructBson, "s8-image_title", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->image_title), DAVE_KEY_OPT_MAX, DAVE_IMAGE_TITLE_LEN));
	t_bson_add_object(pStructBson, "s8-image_painter", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->image_painter), DAVE_KEY_OPT_MAX, DAVE_USER_NAME_LEN));
	t_bson_add_object(pStructBson, "ub-inliners_num", t_rpc_ver3_zip_ub_d((ub *)(zip_data->inliners_num), DAVE_KEY_OPT_MAX));
	t_bson_add_object(pStructBson, "float-inliners_score", t_rpc_ver3_zip_float_d((float *)(zip_data->inliners_score), DAVE_KEY_OPT_MAX));
	t_bson_add_object(pStructBson, "ub-keypoints_num", t_rpc_ver3_zip_ub_d((ub *)(zip_data->keypoints_num), DAVE_KEY_OPT_MAX));
	t_bson_add_object(pStructBson, "float-keypoints_score", t_rpc_ver3_zip_float_d((float *)(zip_data->keypoints_score), DAVE_KEY_OPT_MAX));
	t_bson_add_object(pStructBson, "dave_bool-confidence", t_rpc_ver3_zip_dave_bool(zip_data->confidence));
	t_bson_add_object(pStructBson, "s8-label", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->label), 1, DAVE_LABEL_STR_MAX));
	t_bson_add_object(pStructBson, "float-score", t_rpc_ver3_zip_float(zip_data->score));
	t_bson_add_object(pStructBson, "ub-cnn_model_work_time", t_rpc_ver3_zip_ub(zip_data->cnn_model_work_time));
	t_bson_add_object(pStructBson, "ub-features_db_req_time", t_rpc_ver3_zip_ub(zip_data->features_db_req_time));
	t_bson_add_object(pStructBson, "ub-features_db_rsp_time", t_rpc_ver3_zip_ub(zip_data->features_db_rsp_time));
	t_bson_add_object(pStructBson, "ub-features_db_process_time", t_rpc_ver3_zip_ub(zip_data->features_db_process_time));
	t_bson_add_object(pStructBson, "ub-introduce_db_req_time", t_rpc_ver3_zip_ub(zip_data->introduce_db_req_time));
	t_bson_add_object(pStructBson, "ub-introduce_db_rsp_time", t_rpc_ver3_zip_ub(zip_data->introduce_db_rsp_time));
	t_bson_add_object(pStructBson, "MBUF-model_raw_data", t_rpc_ver3_zip_MBUF_ptr(zip_data->model_raw_data));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_CVModelResult(CVModelResult *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on CVModelResult");
		dave_memset(unzip_data, 0x00, sizeof(CVModelResult));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_CVSearchOpt(&(unzip_data->search_opt), t_bson_inq_object(pStructBson, "CVSearchOpt-search_opt"));
		t_rpc_ver3_unzip_MCardContentType(&(unzip_data->content_type), t_bson_inq_object(pStructBson, "MCardContentType-content_type"));
		t_rpc_ver3_unzip_LanguageCode(&(unzip_data->language_code), t_bson_inq_object(pStructBson, "LanguageCode-language_code"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->image_local_path), 1, DAVE_PATH_LEN, t_bson_inq_object(pStructBson, "s8-image_local_path"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->image_url_path), 1, DAVE_PATH_LEN, t_bson_inq_object(pStructBson, "s8-image_url_path"));
		t_rpc_ver3_unzip_ub(&(unzip_data->opt_number), t_bson_inq_object(pStructBson, "ub-opt_number"));
		t_rpc_ver3_unzip_ub(&(unzip_data->face_number), t_bson_inq_object(pStructBson, "ub-face_number"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->vgg_id), DAVE_KEY_OPT_MAX, DAVE_SHA1_IMAGE_ID, t_bson_inq_object(pStructBson, "s8-vgg_id"));
		t_rpc_ver3_unzip_float_d((float *)(unzip_data->vgg_score), DAVE_KEY_OPT_MAX, t_bson_inq_object(pStructBson, "float-vgg_score"));
		t_rpc_ver3_unzip_CVRectangle_d(unzip_data->rectangle, DAVE_KEY_OPT_MAX, t_bson_inq_object(pStructBson, "CVRectangle-rectangle"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->image_title), DAVE_KEY_OPT_MAX, DAVE_IMAGE_TITLE_LEN, t_bson_inq_object(pStructBson, "s8-image_title"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->image_painter), DAVE_KEY_OPT_MAX, DAVE_USER_NAME_LEN, t_bson_inq_object(pStructBson, "s8-image_painter"));
		t_rpc_ver3_unzip_ub_d((ub *)(unzip_data->inliners_num), DAVE_KEY_OPT_MAX, t_bson_inq_object(pStructBson, "ub-inliners_num"));
		t_rpc_ver3_unzip_float_d((float *)(unzip_data->inliners_score), DAVE_KEY_OPT_MAX, t_bson_inq_object(pStructBson, "float-inliners_score"));
		t_rpc_ver3_unzip_ub_d((ub *)(unzip_data->keypoints_num), DAVE_KEY_OPT_MAX, t_bson_inq_object(pStructBson, "ub-keypoints_num"));
		t_rpc_ver3_unzip_float_d((float *)(unzip_data->keypoints_score), DAVE_KEY_OPT_MAX, t_bson_inq_object(pStructBson, "float-keypoints_score"));
		t_rpc_ver3_unzip_dave_bool(&(unzip_data->confidence), t_bson_inq_object(pStructBson, "dave_bool-confidence"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->label), 1, DAVE_LABEL_STR_MAX, t_bson_inq_object(pStructBson, "s8-label"));
		t_rpc_ver3_unzip_float(&(unzip_data->score), t_bson_inq_object(pStructBson, "float-score"));
		t_rpc_ver3_unzip_ub(&(unzip_data->cnn_model_work_time), t_bson_inq_object(pStructBson, "ub-cnn_model_work_time"));
		t_rpc_ver3_unzip_ub(&(unzip_data->features_db_req_time), t_bson_inq_object(pStructBson, "ub-features_db_req_time"));
		t_rpc_ver3_unzip_ub(&(unzip_data->features_db_rsp_time), t_bson_inq_object(pStructBson, "ub-features_db_rsp_time"));
		t_rpc_ver3_unzip_ub(&(unzip_data->features_db_process_time), t_bson_inq_object(pStructBson, "ub-features_db_process_time"));
		t_rpc_ver3_unzip_ub(&(unzip_data->introduce_db_req_time), t_bson_inq_object(pStructBson, "ub-introduce_db_req_time"));
		t_rpc_ver3_unzip_ub(&(unzip_data->introduce_db_rsp_time), t_bson_inq_object(pStructBson, "ub-introduce_db_rsp_time"));
		t_rpc_ver3_unzip_MBUF_ptr(&(unzip_data->model_raw_data), t_bson_inq_object(pStructBson, "MBUF-model_raw_data"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_CVModelResult_d(CVModelResult *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_CVModelResult(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_CVModelResult_d(CVModelResult *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(CVModelResult));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_CVModelResult(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_TerminalInformation(TerminalInformation *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "s8-language", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->language), 1, 64));
	t_bson_add_object(pStructBson, "s8-country", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->country), 1, 64));
	t_bson_add_object(pStructBson, "s8-province", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->province), 1, 64));
	t_bson_add_object(pStructBson, "s8-city", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->city), 1, 64));
	t_bson_add_object(pStructBson, "s8-nickname", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->nickname), 1, 64));
	t_bson_add_object(pStructBson, "s8-gender", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->gender), 1, 64));
	t_bson_add_object(pStructBson, "s8-brand", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->brand), 1, 64));
	t_bson_add_object(pStructBson, "s8-model", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->model), 1, 64));
	t_bson_add_object(pStructBson, "s8-version", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->version), 1, 64));
	t_bson_add_object(pStructBson, "s8-system", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->system), 1, 64));
	t_bson_add_object(pStructBson, "s8-platform", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->platform), 1, 64));
	t_bson_add_object(pStructBson, "s8-sdkversion", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->sdkversion), 1, 64));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_TerminalInformation(TerminalInformation *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on TerminalInformation");
		dave_memset(unzip_data, 0x00, sizeof(TerminalInformation));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->language), 1, 64, t_bson_inq_object(pStructBson, "s8-language"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->country), 1, 64, t_bson_inq_object(pStructBson, "s8-country"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->province), 1, 64, t_bson_inq_object(pStructBson, "s8-province"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->city), 1, 64, t_bson_inq_object(pStructBson, "s8-city"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->nickname), 1, 64, t_bson_inq_object(pStructBson, "s8-nickname"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->gender), 1, 64, t_bson_inq_object(pStructBson, "s8-gender"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->brand), 1, 64, t_bson_inq_object(pStructBson, "s8-brand"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->model), 1, 64, t_bson_inq_object(pStructBson, "s8-model"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->version), 1, 64, t_bson_inq_object(pStructBson, "s8-version"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->system), 1, 64, t_bson_inq_object(pStructBson, "s8-system"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->platform), 1, 64, t_bson_inq_object(pStructBson, "s8-platform"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->sdkversion), 1, 64, t_bson_inq_object(pStructBson, "s8-sdkversion"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_TerminalInformation_d(TerminalInformation *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_TerminalInformation(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_TerminalInformation_d(TerminalInformation *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(TerminalInformation));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_TerminalInformation(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_PainterIntroduction(PainterIntroduction *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "ub-table_id", t_rpc_ver3_zip_ub(zip_data->table_id));
	t_bson_add_object(pStructBson, "s8-painter_name", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->painter_name), 1, 128));
	t_bson_add_object(pStructBson, "s8-painter_birth", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->painter_birth), 1, 128));
	t_bson_add_object(pStructBson, "s8-painter_death", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->painter_death), 1, 128));
	t_bson_add_object(pStructBson, "s8-painter_introduction", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->painter_introduction), 1, 16384));
	t_bson_add_object(pStructBson, "s8-painter_avatar_id", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->painter_avatar_id), 1, DAVE_SHA1_IMAGE_ID));
	t_bson_add_object(pStructBson, "s8-painter_avatar_url", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->painter_avatar_url), 1, 512));
	t_bson_add_object(pStructBson, "s8-painter_related_painting", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->painter_related_painting), DAVE_KEY_OPT_MAX, DAVE_SHA1_IMAGE_ID));
	t_bson_add_object(pStructBson, "ub-total_painting_number", t_rpc_ver3_zip_ub(zip_data->total_painting_number));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_PainterIntroduction(PainterIntroduction *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on PainterIntroduction");
		dave_memset(unzip_data, 0x00, sizeof(PainterIntroduction));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_ub(&(unzip_data->table_id), t_bson_inq_object(pStructBson, "ub-table_id"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->painter_name), 1, 128, t_bson_inq_object(pStructBson, "s8-painter_name"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->painter_birth), 1, 128, t_bson_inq_object(pStructBson, "s8-painter_birth"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->painter_death), 1, 128, t_bson_inq_object(pStructBson, "s8-painter_death"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->painter_introduction), 1, 16384, t_bson_inq_object(pStructBson, "s8-painter_introduction"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->painter_avatar_id), 1, DAVE_SHA1_IMAGE_ID, t_bson_inq_object(pStructBson, "s8-painter_avatar_id"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->painter_avatar_url), 1, 512, t_bson_inq_object(pStructBson, "s8-painter_avatar_url"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->painter_related_painting), DAVE_KEY_OPT_MAX, DAVE_SHA1_IMAGE_ID, t_bson_inq_object(pStructBson, "s8-painter_related_painting"));
		t_rpc_ver3_unzip_ub(&(unzip_data->total_painting_number), t_bson_inq_object(pStructBson, "ub-total_painting_number"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_PainterIntroduction_d(PainterIntroduction *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_PainterIntroduction(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_PainterIntroduction_d(PainterIntroduction *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(PainterIntroduction));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_PainterIntroduction(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_SocNetInfoAddr(SocNetInfoAddr *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "SocNetInfoIp-ip", t_rpc_ver3_zip_SocNetInfoIp(&(zip_data->ip)));
	t_bson_add_object(pStructBson, "s8-url", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->url), 1, DAVE_URL_LEN));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_SocNetInfoAddr(SocNetInfoAddr *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on SocNetInfoAddr");
		dave_memset(unzip_data, 0x00, sizeof(SocNetInfoAddr));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_SocNetInfoIp(&(unzip_data->ip), t_bson_inq_object(pStructBson, "SocNetInfoIp-ip"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->url), 1, DAVE_URL_LEN, t_bson_inq_object(pStructBson, "s8-url"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_SocNetInfoAddr_d(SocNetInfoAddr *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_SocNetInfoAddr(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_SocNetInfoAddr_d(SocNetInfoAddr *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(SocNetInfoAddr));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_SocNetInfoAddr(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_SocNetInfoIp(SocNetInfoIp *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "IPVER-ver", t_rpc_ver3_zip_IPVER(zip_data->ver));
	t_bson_add_object(pStructBson, "u8-ip_addr", t_rpc_ver3_zip_u8_d((u8 *)(zip_data->ip_addr), 16));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_SocNetInfoIp(SocNetInfoIp *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on SocNetInfoIp");
		dave_memset(unzip_data, 0x00, sizeof(SocNetInfoIp));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_IPVER(&(unzip_data->ver), t_bson_inq_object(pStructBson, "IPVER-ver"));
		t_rpc_ver3_unzip_u8_d((u8 *)(unzip_data->ip_addr), 16, t_bson_inq_object(pStructBson, "u8-ip_addr"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_SocNetInfoIp_d(SocNetInfoIp *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_SocNetInfoIp(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_SocNetInfoIp_d(SocNetInfoIp *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(SocNetInfoIp));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_SocNetInfoIp(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MCardPOI(MCardPOI *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "MCardLocation-location", t_rpc_ver3_zip_MCardLocation(&(zip_data->location)));
	t_bson_add_object(pStructBson, "AIPlaceType-type", t_rpc_ver3_zip_AIPlaceType(zip_data->type));
	t_bson_add_object(pStructBson, "s8-name", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->name), 1, DAVE_POI_NAME_MAX));
	t_bson_add_object(pStructBson, "s8-phone_number", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->phone_number), 1, DAVE_MSISDN_LEN));
	t_bson_add_object(pStructBson, "s8-address", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->address), 1, DAVE_POI_ADDRESS_MAX));
	t_bson_add_object(pStructBson, "double-rating", t_rpc_ver3_zip_double(zip_data->rating));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MCardPOI(MCardPOI *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MCardPOI");
		dave_memset(unzip_data, 0x00, sizeof(MCardPOI));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_MCardLocation(&(unzip_data->location), t_bson_inq_object(pStructBson, "MCardLocation-location"));
		t_rpc_ver3_unzip_AIPlaceType(&(unzip_data->type), t_bson_inq_object(pStructBson, "AIPlaceType-type"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->name), 1, DAVE_POI_NAME_MAX, t_bson_inq_object(pStructBson, "s8-name"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->phone_number), 1, DAVE_MSISDN_LEN, t_bson_inq_object(pStructBson, "s8-phone_number"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->address), 1, DAVE_POI_ADDRESS_MAX, t_bson_inq_object(pStructBson, "s8-address"));
		t_rpc_ver3_unzip_double(&(unzip_data->rating), t_bson_inq_object(pStructBson, "double-rating"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MCardPOI_d(MCardPOI *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MCardPOI(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MCardPOI_d(MCardPOI *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MCardPOI));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MCardPOI(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MCardCommentHead(MCardCommentHead *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "NoSQLHead-nosql_head", t_rpc_ver3_zip_NoSQLHead(&(zip_data->nosql_head)));
	t_bson_add_object(pStructBson, "MCardCommentHeadData-comment_head", t_rpc_ver3_zip_MCardCommentHeadData(&(zip_data->comment_head)));
	t_bson_add_object(pStructBson, "s8-reserve_data", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->reserve_data), 1, DAVE_MACRD_HEAD_MAX-2976));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MCardCommentHead(MCardCommentHead *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MCardCommentHead");
		dave_memset(unzip_data, 0x00, sizeof(MCardCommentHead));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_NoSQLHead(&(unzip_data->nosql_head), t_bson_inq_object(pStructBson, "NoSQLHead-nosql_head"));
		t_rpc_ver3_unzip_MCardCommentHeadData(&(unzip_data->comment_head), t_bson_inq_object(pStructBson, "MCardCommentHeadData-comment_head"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->reserve_data), 1, DAVE_MACRD_HEAD_MAX-2976, t_bson_inq_object(pStructBson, "s8-reserve_data"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MCardCommentHead_d(MCardCommentHead *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MCardCommentHead(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MCardCommentHead_d(MCardCommentHead *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MCardCommentHead));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MCardCommentHead(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_CVRectangle(CVRectangle *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "float-x1", t_rpc_ver3_zip_float(zip_data->x1));
	t_bson_add_object(pStructBson, "float-y1", t_rpc_ver3_zip_float(zip_data->y1));
	t_bson_add_object(pStructBson, "float-x2", t_rpc_ver3_zip_float(zip_data->x2));
	t_bson_add_object(pStructBson, "float-y2", t_rpc_ver3_zip_float(zip_data->y2));
	t_bson_add_object(pStructBson, "float-w", t_rpc_ver3_zip_float(zip_data->w));
	t_bson_add_object(pStructBson, "float-h", t_rpc_ver3_zip_float(zip_data->h));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_CVRectangle(CVRectangle *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on CVRectangle");
		dave_memset(unzip_data, 0x00, sizeof(CVRectangle));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_float(&(unzip_data->x1), t_bson_inq_object(pStructBson, "float-x1"));
		t_rpc_ver3_unzip_float(&(unzip_data->y1), t_bson_inq_object(pStructBson, "float-y1"));
		t_rpc_ver3_unzip_float(&(unzip_data->x2), t_bson_inq_object(pStructBson, "float-x2"));
		t_rpc_ver3_unzip_float(&(unzip_data->y2), t_bson_inq_object(pStructBson, "float-y2"));
		t_rpc_ver3_unzip_float(&(unzip_data->w), t_bson_inq_object(pStructBson, "float-w"));
		t_rpc_ver3_unzip_float(&(unzip_data->h), t_bson_inq_object(pStructBson, "float-h"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_CVRectangle_d(CVRectangle *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_CVRectangle(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_CVRectangle_d(CVRectangle *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(CVRectangle));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_CVRectangle(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_NoSQLHead(NoSQLHead *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "s8-key_str", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->key_str), 1, DAVE_NOSQL_KEY_STR_MAX));
	t_bson_add_object(pStructBson, "s8-reserve_data", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->reserve_data), 1, 512-DAVE_NOSQL_KEY_STR_MAX));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_NoSQLHead(NoSQLHead *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on NoSQLHead");
		dave_memset(unzip_data, 0x00, sizeof(NoSQLHead));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->key_str), 1, DAVE_NOSQL_KEY_STR_MAX, t_bson_inq_object(pStructBson, "s8-key_str"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->reserve_data), 1, 512-DAVE_NOSQL_KEY_STR_MAX, t_bson_inq_object(pStructBson, "s8-reserve_data"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_NoSQLHead_d(NoSQLHead *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_NoSQLHead(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_NoSQLHead_d(NoSQLHead *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(NoSQLHead));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_NoSQLHead(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MCardCommentHeadData(MCardCommentHeadData *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "MCardType-type", t_rpc_ver3_zip_MCardType(zip_data->type));
	t_bson_add_object(pStructBson, "s8-post_id", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->post_id), 1, DAVE_KEY_LEN_MAX));
	t_bson_add_object(pStructBson, "s8-reply_comment_id", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->reply_comment_id), 1, DAVE_KEY_LEN_MAX));
	t_bson_add_object(pStructBson, "s8-src_uuid", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->src_uuid), 1, DAVE_UUID_LEN));
	t_bson_add_object(pStructBson, "s8-dst_uuid", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->dst_uuid), 1, DAVE_UUID_LEN));
	t_bson_add_object(pStructBson, "s8-src_user", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->src_user), 1, DAVE_USER_NAME_LEN));
	t_bson_add_object(pStructBson, "s8-dst_user", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->dst_user), 1, DAVE_USER_NAME_LEN));
	t_bson_add_object(pStructBson, "MCardLocation-location", t_rpc_ver3_zip_MCardLocation(&(zip_data->location)));
	t_bson_add_object(pStructBson, "MCardTime-time", t_rpc_ver3_zip_MCardTime(&(zip_data->time)));
	t_bson_add_object(pStructBson, "TerminalInformation-ti", t_rpc_ver3_zip_TerminalInformation(&(zip_data->ti)));
	t_bson_add_object(pStructBson, "UserInformation-user", t_rpc_ver3_zip_UserInformation(&(zip_data->user)));
	t_bson_add_object(pStructBson, "ub-comment_attributes", t_rpc_ver3_zip_ub(zip_data->comment_attributes));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MCardCommentHeadData(MCardCommentHeadData *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MCardCommentHeadData");
		dave_memset(unzip_data, 0x00, sizeof(MCardCommentHeadData));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_MCardType(&(unzip_data->type), t_bson_inq_object(pStructBson, "MCardType-type"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->post_id), 1, DAVE_KEY_LEN_MAX, t_bson_inq_object(pStructBson, "s8-post_id"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->reply_comment_id), 1, DAVE_KEY_LEN_MAX, t_bson_inq_object(pStructBson, "s8-reply_comment_id"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->src_uuid), 1, DAVE_UUID_LEN, t_bson_inq_object(pStructBson, "s8-src_uuid"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->dst_uuid), 1, DAVE_UUID_LEN, t_bson_inq_object(pStructBson, "s8-dst_uuid"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->src_user), 1, DAVE_USER_NAME_LEN, t_bson_inq_object(pStructBson, "s8-src_user"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->dst_user), 1, DAVE_USER_NAME_LEN, t_bson_inq_object(pStructBson, "s8-dst_user"));
		t_rpc_ver3_unzip_MCardLocation(&(unzip_data->location), t_bson_inq_object(pStructBson, "MCardLocation-location"));
		t_rpc_ver3_unzip_MCardTime(&(unzip_data->time), t_bson_inq_object(pStructBson, "MCardTime-time"));
		t_rpc_ver3_unzip_TerminalInformation(&(unzip_data->ti), t_bson_inq_object(pStructBson, "TerminalInformation-ti"));
		t_rpc_ver3_unzip_UserInformation(&(unzip_data->user), t_bson_inq_object(pStructBson, "UserInformation-user"));
		t_rpc_ver3_unzip_ub(&(unzip_data->comment_attributes), t_bson_inq_object(pStructBson, "ub-comment_attributes"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MCardCommentHeadData_d(MCardCommentHeadData *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MCardCommentHeadData(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MCardCommentHeadData_d(MCardCommentHeadData *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MCardCommentHeadData));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MCardCommentHeadData(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_UserInformation(UserInformation *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "s8-language", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->language), 1, 64));
	t_bson_add_object(pStructBson, "s8-country", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->country), 1, 64));
	t_bson_add_object(pStructBson, "s8-province", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->province), 1, 64));
	t_bson_add_object(pStructBson, "s8-city", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->city), 1, 64));
	t_bson_add_object(pStructBson, "s8-nickname", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->nickname), 1, 64));
	t_bson_add_object(pStructBson, "s8-gender", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->gender), 1, 16));
	t_bson_add_object(pStructBson, "s8-phone_number_1", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->phone_number_1), 1, 64));
	t_bson_add_object(pStructBson, "s8-phone_number_2", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->phone_number_2), 1, 64));
	t_bson_add_object(pStructBson, "s8-email_1", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->email_1), 1, 64));
	t_bson_add_object(pStructBson, "s8-email_2", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->email_2), 1, 64));
	t_bson_add_object(pStructBson, "s8-home_address", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->home_address), 1, 128));
	t_bson_add_object(pStructBson, "s8-avatar_url", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->avatar_url), 1, 256));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_UserInformation(UserInformation *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on UserInformation");
		dave_memset(unzip_data, 0x00, sizeof(UserInformation));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->language), 1, 64, t_bson_inq_object(pStructBson, "s8-language"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->country), 1, 64, t_bson_inq_object(pStructBson, "s8-country"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->province), 1, 64, t_bson_inq_object(pStructBson, "s8-province"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->city), 1, 64, t_bson_inq_object(pStructBson, "s8-city"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->nickname), 1, 64, t_bson_inq_object(pStructBson, "s8-nickname"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->gender), 1, 16, t_bson_inq_object(pStructBson, "s8-gender"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->phone_number_1), 1, 64, t_bson_inq_object(pStructBson, "s8-phone_number_1"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->phone_number_2), 1, 64, t_bson_inq_object(pStructBson, "s8-phone_number_2"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->email_1), 1, 64, t_bson_inq_object(pStructBson, "s8-email_1"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->email_2), 1, 64, t_bson_inq_object(pStructBson, "s8-email_2"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->home_address), 1, 128, t_bson_inq_object(pStructBson, "s8-home_address"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->avatar_url), 1, 256, t_bson_inq_object(pStructBson, "s8-avatar_url"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_UserInformation_d(UserInformation *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_UserInformation(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_UserInformation_d(UserInformation *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(UserInformation));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_UserInformation(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MBUF(MBUF *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "void-next", t_rpc_ver3_zip_void_ptr(zip_data->next));
	t_bson_add_object(pStructBson, "void-payload", t_rpc_ver3_zip_void_ptr(zip_data->payload));
	t_bson_add_object(pStructBson, "sb-tot_len", t_rpc_ver3_zip_sb(zip_data->tot_len));
	t_bson_add_object(pStructBson, "sb-len", t_rpc_ver3_zip_sb(zip_data->len));
	t_bson_add_object(pStructBson, "sb-ref", t_rpc_ver3_zip_sb(zip_data->ref));
	t_bson_add_object(pStructBson, "sb-alloc_len", t_rpc_ver3_zip_sb(zip_data->alloc_len));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MBUF(MBUF *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MBUF");
		dave_memset(unzip_data, 0x00, sizeof(MBUF));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_void_ptr(&(unzip_data->next), t_bson_inq_object(pStructBson, "void-next"));
		t_rpc_ver3_unzip_void_ptr(&(unzip_data->payload), t_bson_inq_object(pStructBson, "void-payload"));
		t_rpc_ver3_unzip_sb(&(unzip_data->tot_len), t_bson_inq_object(pStructBson, "sb-tot_len"));
		t_rpc_ver3_unzip_sb(&(unzip_data->len), t_bson_inq_object(pStructBson, "sb-len"));
		t_rpc_ver3_unzip_sb(&(unzip_data->ref), t_bson_inq_object(pStructBson, "sb-ref"));
		t_rpc_ver3_unzip_sb(&(unzip_data->alloc_len), t_bson_inq_object(pStructBson, "sb-alloc_len"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MBUF_d(MBUF *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MBUF(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MBUF_d(MBUF *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MBUF));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MBUF(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_GPSLocation(GPSLocation *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "double-latitude", t_rpc_ver3_zip_double(zip_data->latitude));
	t_bson_add_object(pStructBson, "double-longitude", t_rpc_ver3_zip_double(zip_data->longitude));
	t_bson_add_object(pStructBson, "double-altitude", t_rpc_ver3_zip_double(zip_data->altitude));
	t_bson_add_object(pStructBson, "double-course", t_rpc_ver3_zip_double(zip_data->course));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_GPSLocation(GPSLocation *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on GPSLocation");
		dave_memset(unzip_data, 0x00, sizeof(GPSLocation));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_double(&(unzip_data->latitude), t_bson_inq_object(pStructBson, "double-latitude"));
		t_rpc_ver3_unzip_double(&(unzip_data->longitude), t_bson_inq_object(pStructBson, "double-longitude"));
		t_rpc_ver3_unzip_double(&(unzip_data->altitude), t_bson_inq_object(pStructBson, "double-altitude"));
		t_rpc_ver3_unzip_double(&(unzip_data->course), t_bson_inq_object(pStructBson, "double-course"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_GPSLocation_d(GPSLocation *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_GPSLocation(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_GPSLocation_d(GPSLocation *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(GPSLocation));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_GPSLocation(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MCard(MCard *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "MCardVer-version", t_rpc_ver3_zip_MCardVer(zip_data->version));
	t_bson_add_object(pStructBson, "MCardVerText-text", t_rpc_ver3_zip_MCardVerText(&(zip_data->text)));
	t_bson_add_object(pStructBson, "MCardVerMedia-media", t_rpc_ver3_zip_MCardVerMedia(&(zip_data->media)));
	t_bson_add_object(pStructBson, "MCardVerTalk-talk", t_rpc_ver3_zip_MCardVerTalk(&(zip_data->talk)));
	t_bson_add_object(pStructBson, "MCardVerComment-comment", t_rpc_ver3_zip_MCardVerComment(&(zip_data->comment)));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MCard(MCard *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MCard");
		dave_memset(unzip_data, 0x00, sizeof(MCard));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_MCardVer(&(unzip_data->version), t_bson_inq_object(pStructBson, "MCardVer-version"));
		t_rpc_ver3_unzip_MCardVerText(&(unzip_data->text), t_bson_inq_object(pStructBson, "MCardVerText-text"));
		t_rpc_ver3_unzip_MCardVerMedia(&(unzip_data->media), t_bson_inq_object(pStructBson, "MCardVerMedia-media"));
		t_rpc_ver3_unzip_MCardVerTalk(&(unzip_data->talk), t_bson_inq_object(pStructBson, "MCardVerTalk-talk"));
		t_rpc_ver3_unzip_MCardVerComment(&(unzip_data->comment), t_bson_inq_object(pStructBson, "MCardVerComment-comment"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MCard_d(MCard *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MCard(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MCard_d(MCard *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MCard));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MCard(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MCardVerTalk(MCardVerTalk *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "MCardVer-version", t_rpc_ver3_zip_MCardVer(zip_data->version));
	t_bson_add_object(pStructBson, "MCardType-type", t_rpc_ver3_zip_MCardType(zip_data->type));
	t_bson_add_object(pStructBson, "s8-channel", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->channel), 1, DAVE_NORMAL_NAME_LEN));
	t_bson_add_object(pStructBson, "s8-uuid", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->uuid), 1, DAVE_UUID_LEN));
	t_bson_add_object(pStructBson, "ub-app_id", t_rpc_ver3_zip_ub(zip_data->app_id));
	t_bson_add_object(pStructBson, "s8-src_user", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->src_user), 1, DAVE_USER_NAME_LEN));
	t_bson_add_object(pStructBson, "s8-dst_user", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->dst_user), 1, DAVE_USER_NAME_LEN));
	t_bson_add_object(pStructBson, "MCardLocation-location", t_rpc_ver3_zip_MCardLocation(&(zip_data->location)));
	t_bson_add_object(pStructBson, "MCardTime-time", t_rpc_ver3_zip_MCardTime(&(zip_data->time)));
	t_bson_add_object(pStructBson, "ub-main_serial", t_rpc_ver3_zip_ub(zip_data->main_serial));
	t_bson_add_object(pStructBson, "ub-sub_serial", t_rpc_ver3_zip_ub(zip_data->sub_serial));
	t_bson_add_object(pStructBson, "ub-total_sub_serial", t_rpc_ver3_zip_ub(zip_data->total_sub_serial));
	t_bson_add_object(pStructBson, "MCardContent-content", t_rpc_ver3_zip_MCardContent(&(zip_data->content)));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MCardVerTalk(MCardVerTalk *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MCardVerTalk");
		dave_memset(unzip_data, 0x00, sizeof(MCardVerTalk));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_MCardVer(&(unzip_data->version), t_bson_inq_object(pStructBson, "MCardVer-version"));
		t_rpc_ver3_unzip_MCardType(&(unzip_data->type), t_bson_inq_object(pStructBson, "MCardType-type"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->channel), 1, DAVE_NORMAL_NAME_LEN, t_bson_inq_object(pStructBson, "s8-channel"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->uuid), 1, DAVE_UUID_LEN, t_bson_inq_object(pStructBson, "s8-uuid"));
		t_rpc_ver3_unzip_ub(&(unzip_data->app_id), t_bson_inq_object(pStructBson, "ub-app_id"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->src_user), 1, DAVE_USER_NAME_LEN, t_bson_inq_object(pStructBson, "s8-src_user"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->dst_user), 1, DAVE_USER_NAME_LEN, t_bson_inq_object(pStructBson, "s8-dst_user"));
		t_rpc_ver3_unzip_MCardLocation(&(unzip_data->location), t_bson_inq_object(pStructBson, "MCardLocation-location"));
		t_rpc_ver3_unzip_MCardTime(&(unzip_data->time), t_bson_inq_object(pStructBson, "MCardTime-time"));
		t_rpc_ver3_unzip_ub(&(unzip_data->main_serial), t_bson_inq_object(pStructBson, "ub-main_serial"));
		t_rpc_ver3_unzip_ub(&(unzip_data->sub_serial), t_bson_inq_object(pStructBson, "ub-sub_serial"));
		t_rpc_ver3_unzip_ub(&(unzip_data->total_sub_serial), t_bson_inq_object(pStructBson, "ub-total_sub_serial"));
		t_rpc_ver3_unzip_MCardContent(&(unzip_data->content), t_bson_inq_object(pStructBson, "MCardContent-content"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MCardVerTalk_d(MCardVerTalk *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MCardVerTalk(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MCardVerTalk_d(MCardVerTalk *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MCardVerTalk));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MCardVerTalk(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_UniversalLabel(UniversalLabel *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "s8-label_extra_information", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->label_extra_information), 1, DAVE_LABEL_EXTRA_INFO_MAX));
	t_bson_add_object(pStructBson, "ub-label_id", t_rpc_ver3_zip_ub(zip_data->label_id));
	t_bson_add_object(pStructBson, "s8-label_str", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->label_str), 1, DAVE_LABEL_STR_MAX));
	t_bson_add_object(pStructBson, "float-label_score", t_rpc_ver3_zip_float(zip_data->label_score));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_UniversalLabel(UniversalLabel *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on UniversalLabel");
		dave_memset(unzip_data, 0x00, sizeof(UniversalLabel));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->label_extra_information), 1, DAVE_LABEL_EXTRA_INFO_MAX, t_bson_inq_object(pStructBson, "s8-label_extra_information"));
		t_rpc_ver3_unzip_ub(&(unzip_data->label_id), t_bson_inq_object(pStructBson, "ub-label_id"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->label_str), 1, DAVE_LABEL_STR_MAX, t_bson_inq_object(pStructBson, "s8-label_str"));
		t_rpc_ver3_unzip_float(&(unzip_data->label_score), t_bson_inq_object(pStructBson, "float-label_score"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_UniversalLabel_d(UniversalLabel *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_UniversalLabel(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_UniversalLabel_d(UniversalLabel *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(UniversalLabel));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_UniversalLabel(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_CVResult(CVResult *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "CVModelResult-model_result", t_rpc_ver3_zip_CVModelResult(&(zip_data->model_result)));
	t_bson_add_object(pStructBson, "ImageIntroduction-image_introduction", t_rpc_ver3_zip_ImageIntroduction(&(zip_data->image_introduction)));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_CVResult(CVResult *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on CVResult");
		dave_memset(unzip_data, 0x00, sizeof(CVResult));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_CVModelResult(&(unzip_data->model_result), t_bson_inq_object(pStructBson, "CVModelResult-model_result"));
		t_rpc_ver3_unzip_ImageIntroduction(&(unzip_data->image_introduction), t_bson_inq_object(pStructBson, "ImageIntroduction-image_introduction"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_CVResult_d(CVResult *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_CVResult(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_CVResult_d(CVResult *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(CVResult));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_CVResult(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_CVKeyPoint(CVKeyPoint *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "int-width", t_rpc_ver3_zip_int(zip_data->width));
	t_bson_add_object(pStructBson, "int-height", t_rpc_ver3_zip_int(zip_data->height));
	t_bson_add_object(pStructBson, "int-size", t_rpc_ver3_zip_int(zip_data->size));
	t_bson_add_object(pStructBson, "MBUF-_KeyPoint_", t_rpc_ver3_zip_MBUF_ptr(zip_data->_KeyPoint_));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_CVKeyPoint(CVKeyPoint *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on CVKeyPoint");
		dave_memset(unzip_data, 0x00, sizeof(CVKeyPoint));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_int(&(unzip_data->width), t_bson_inq_object(pStructBson, "int-width"));
		t_rpc_ver3_unzip_int(&(unzip_data->height), t_bson_inq_object(pStructBson, "int-height"));
		t_rpc_ver3_unzip_int(&(unzip_data->size), t_bson_inq_object(pStructBson, "int-size"));
		t_rpc_ver3_unzip_MBUF_ptr(&(unzip_data->_KeyPoint_), t_bson_inq_object(pStructBson, "MBUF-_KeyPoint_"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_CVKeyPoint_d(CVKeyPoint *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_CVKeyPoint(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_CVKeyPoint_d(CVKeyPoint *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(CVKeyPoint));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_CVKeyPoint(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_OpenCVMat(OpenCVMat *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "int-type", t_rpc_ver3_zip_int(zip_data->type));
	t_bson_add_object(pStructBson, "int-flags", t_rpc_ver3_zip_int(zip_data->flags));
	t_bson_add_object(pStructBson, "int-dims", t_rpc_ver3_zip_int(zip_data->dims));
	t_bson_add_object(pStructBson, "int-rows", t_rpc_ver3_zip_int(zip_data->rows));
	t_bson_add_object(pStructBson, "int-cols", t_rpc_ver3_zip_int(zip_data->cols));
	t_bson_add_object(pStructBson, "MBUF-Mat", t_rpc_ver3_zip_MBUF_ptr(zip_data->Mat));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_OpenCVMat(OpenCVMat *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on OpenCVMat");
		dave_memset(unzip_data, 0x00, sizeof(OpenCVMat));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_int(&(unzip_data->type), t_bson_inq_object(pStructBson, "int-type"));
		t_rpc_ver3_unzip_int(&(unzip_data->flags), t_bson_inq_object(pStructBson, "int-flags"));
		t_rpc_ver3_unzip_int(&(unzip_data->dims), t_bson_inq_object(pStructBson, "int-dims"));
		t_rpc_ver3_unzip_int(&(unzip_data->rows), t_bson_inq_object(pStructBson, "int-rows"));
		t_rpc_ver3_unzip_int(&(unzip_data->cols), t_bson_inq_object(pStructBson, "int-cols"));
		t_rpc_ver3_unzip_MBUF_ptr(&(unzip_data->Mat), t_bson_inq_object(pStructBson, "MBUF-Mat"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_OpenCVMat_d(OpenCVMat *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_OpenCVMat(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_OpenCVMat_d(OpenCVMat *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(OpenCVMat));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_OpenCVMat(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_WeiChatUserInfo(WeiChatUserInfo *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "s8-uuid", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->uuid), 1, 64));
	t_bson_add_object(pStructBson, "s8-openid", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->openid), 1, 64));
	t_bson_add_object(pStructBson, "s8-code", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->code), 1, 64));
	t_bson_add_object(pStructBson, "s8-user_id", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->user_id), 1, 64));
	t_bson_add_object(pStructBson, "s8-session_key", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->session_key), 1, 64));
	t_bson_add_object(pStructBson, "s8-share_uuid", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->share_uuid), 1, 64));
	t_bson_add_object(pStructBson, "TerminalInformation-ti", t_rpc_ver3_zip_TerminalInformation(&(zip_data->ti)));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_WeiChatUserInfo(WeiChatUserInfo *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on WeiChatUserInfo");
		dave_memset(unzip_data, 0x00, sizeof(WeiChatUserInfo));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->uuid), 1, 64, t_bson_inq_object(pStructBson, "s8-uuid"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->openid), 1, 64, t_bson_inq_object(pStructBson, "s8-openid"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->code), 1, 64, t_bson_inq_object(pStructBson, "s8-code"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->user_id), 1, 64, t_bson_inq_object(pStructBson, "s8-user_id"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->session_key), 1, 64, t_bson_inq_object(pStructBson, "s8-session_key"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->share_uuid), 1, 64, t_bson_inq_object(pStructBson, "s8-share_uuid"));
		t_rpc_ver3_unzip_TerminalInformation(&(unzip_data->ti), t_bson_inq_object(pStructBson, "TerminalInformation-ti"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_WeiChatUserInfo_d(WeiChatUserInfo *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_WeiChatUserInfo(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_WeiChatUserInfo_d(WeiChatUserInfo *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(WeiChatUserInfo));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_WeiChatUserInfo(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_ChannelInfo(ChannelInfo *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "s8-domain", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->domain), 1, DAVE_DOMAIN_LEN));
	t_bson_add_object(pStructBson, "s8-tenant_name", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->tenant_name), 1, DAVE_TENANT_NAME_LEN));
	t_bson_add_object(pStructBson, "ub-tenant_id", t_rpc_ver3_zip_ub(zip_data->tenant_id));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_ChannelInfo(ChannelInfo *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on ChannelInfo");
		dave_memset(unzip_data, 0x00, sizeof(ChannelInfo));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->domain), 1, DAVE_DOMAIN_LEN, t_bson_inq_object(pStructBson, "s8-domain"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->tenant_name), 1, DAVE_TENANT_NAME_LEN, t_bson_inq_object(pStructBson, "s8-tenant_name"));
		t_rpc_ver3_unzip_ub(&(unzip_data->tenant_id), t_bson_inq_object(pStructBson, "ub-tenant_id"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_ChannelInfo_d(ChannelInfo *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_ChannelInfo(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_ChannelInfo_d(ChannelInfo *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(ChannelInfo));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_ChannelInfo(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_DateStruct(DateStruct *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "u16-year", t_rpc_ver3_zip_u16(zip_data->year));
	t_bson_add_object(pStructBson, "u8-month", t_rpc_ver3_zip_u8(zip_data->month));
	t_bson_add_object(pStructBson, "u8-day", t_rpc_ver3_zip_u8(zip_data->day));
	t_bson_add_object(pStructBson, "u8-hour", t_rpc_ver3_zip_u8(zip_data->hour));
	t_bson_add_object(pStructBson, "u8-minute", t_rpc_ver3_zip_u8(zip_data->minute));
	t_bson_add_object(pStructBson, "u8-second", t_rpc_ver3_zip_u8(zip_data->second));
	t_bson_add_object(pStructBson, "u8-week", t_rpc_ver3_zip_u8(zip_data->week));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_DateStruct(DateStruct *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on DateStruct");
		dave_memset(unzip_data, 0x00, sizeof(DateStruct));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_u16(&(unzip_data->year), t_bson_inq_object(pStructBson, "u16-year"));
		t_rpc_ver3_unzip_u8(&(unzip_data->month), t_bson_inq_object(pStructBson, "u8-month"));
		t_rpc_ver3_unzip_u8(&(unzip_data->day), t_bson_inq_object(pStructBson, "u8-day"));
		t_rpc_ver3_unzip_u8(&(unzip_data->hour), t_bson_inq_object(pStructBson, "u8-hour"));
		t_rpc_ver3_unzip_u8(&(unzip_data->minute), t_bson_inq_object(pStructBson, "u8-minute"));
		t_rpc_ver3_unzip_u8(&(unzip_data->second), t_bson_inq_object(pStructBson, "u8-second"));
		t_rpc_ver3_unzip_u8(&(unzip_data->week), t_bson_inq_object(pStructBson, "u8-week"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_DateStruct_d(DateStruct *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_DateStruct(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_DateStruct_d(DateStruct *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(DateStruct));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_DateStruct(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_ImageIntroduction(ImageIntroduction *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "s8-image_id", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->image_id), 1, DAVE_SHA1_IMAGE_ID));
	t_bson_add_object(pStructBson, "PainterIntroduction-painter", t_rpc_ver3_zip_PainterIntroduction(&(zip_data->painter)));
	t_bson_add_object(pStructBson, "MuseumIntroduction-museum", t_rpc_ver3_zip_MuseumIntroduction(&(zip_data->museum)));
	t_bson_add_object(pStructBson, "s8-creat_time", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->creat_time), 1, 128));
	t_bson_add_object(pStructBson, "s8-dimensions", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->dimensions), 1, 128));
	t_bson_add_object(pStructBson, "s8-title", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->title), 1, DAVE_IMAGE_TITLE_LEN));
	t_bson_add_object(pStructBson, "s8-medium", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->medium), 1, 128));
	t_bson_add_object(pStructBson, "s8-image_introduction", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->image_introduction), 1, 16384));
	t_bson_add_object(pStructBson, "s8-image_url", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->image_url), 1, DAVE_URL_LEN));
	t_bson_add_object(pStructBson, "s8-page_url", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->page_url), 1, DAVE_URL_LEN));
	t_bson_add_object(pStructBson, "s8-collection_location", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->collection_location), 1, 512));
	t_bson_add_object(pStructBson, "s8-audio_url", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->audio_url), 1, DAVE_URL_LEN));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_ImageIntroduction(ImageIntroduction *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on ImageIntroduction");
		dave_memset(unzip_data, 0x00, sizeof(ImageIntroduction));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->image_id), 1, DAVE_SHA1_IMAGE_ID, t_bson_inq_object(pStructBson, "s8-image_id"));
		t_rpc_ver3_unzip_PainterIntroduction(&(unzip_data->painter), t_bson_inq_object(pStructBson, "PainterIntroduction-painter"));
		t_rpc_ver3_unzip_MuseumIntroduction(&(unzip_data->museum), t_bson_inq_object(pStructBson, "MuseumIntroduction-museum"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->creat_time), 1, 128, t_bson_inq_object(pStructBson, "s8-creat_time"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->dimensions), 1, 128, t_bson_inq_object(pStructBson, "s8-dimensions"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->title), 1, DAVE_IMAGE_TITLE_LEN, t_bson_inq_object(pStructBson, "s8-title"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->medium), 1, 128, t_bson_inq_object(pStructBson, "s8-medium"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->image_introduction), 1, 16384, t_bson_inq_object(pStructBson, "s8-image_introduction"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->image_url), 1, DAVE_URL_LEN, t_bson_inq_object(pStructBson, "s8-image_url"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->page_url), 1, DAVE_URL_LEN, t_bson_inq_object(pStructBson, "s8-page_url"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->collection_location), 1, 512, t_bson_inq_object(pStructBson, "s8-collection_location"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->audio_url), 1, DAVE_URL_LEN, t_bson_inq_object(pStructBson, "s8-audio_url"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_ImageIntroduction_d(ImageIntroduction *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_ImageIntroduction(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_ImageIntroduction_d(ImageIntroduction *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(ImageIntroduction));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_ImageIntroduction(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_MuseumIntroduction(MuseumIntroduction *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "ub-table_id", t_rpc_ver3_zip_ub(zip_data->table_id));
	t_bson_add_object(pStructBson, "s8-museum_id", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->museum_id), 1, DAVE_SHA1_IMAGE_ID));
	t_bson_add_object(pStructBson, "s8-museum_name", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->museum_name), 1, 128));
	t_bson_add_object(pStructBson, "s8-address", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->address), 1, 1024));
	t_bson_add_object(pStructBson, "s8-ticket", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->ticket), 1, 256));
	t_bson_add_object(pStructBson, "s8-phone", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->phone), 1, 128));
	t_bson_add_object(pStructBson, "s8-web_url", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->web_url), 1, 256));
	t_bson_add_object(pStructBson, "s8-opening_hours", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->opening_hours), 1, 256));
	t_bson_add_object(pStructBson, "s8-museum_introduction", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->museum_introduction), 1, 16384));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_MuseumIntroduction(MuseumIntroduction *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on MuseumIntroduction");
		dave_memset(unzip_data, 0x00, sizeof(MuseumIntroduction));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_ub(&(unzip_data->table_id), t_bson_inq_object(pStructBson, "ub-table_id"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->museum_id), 1, DAVE_SHA1_IMAGE_ID, t_bson_inq_object(pStructBson, "s8-museum_id"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->museum_name), 1, 128, t_bson_inq_object(pStructBson, "s8-museum_name"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->address), 1, 1024, t_bson_inq_object(pStructBson, "s8-address"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->ticket), 1, 256, t_bson_inq_object(pStructBson, "s8-ticket"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->phone), 1, 128, t_bson_inq_object(pStructBson, "s8-phone"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->web_url), 1, 256, t_bson_inq_object(pStructBson, "s8-web_url"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->opening_hours), 1, 256, t_bson_inq_object(pStructBson, "s8-opening_hours"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->museum_introduction), 1, 16384, t_bson_inq_object(pStructBson, "s8-museum_introduction"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_MuseumIntroduction_d(MuseumIntroduction *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_MuseumIntroduction(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_MuseumIntroduction_d(MuseumIntroduction *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(MuseumIntroduction));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_MuseumIntroduction(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_HttpKeyValue(HttpKeyValue *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "s8-key", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->key), 1, DAVE_HTTP_KEY_LEN));
	t_bson_add_object(pStructBson, "s8-value", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->value), 1, DAVE_HTTP_VALUE_LEN));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_HttpKeyValue(HttpKeyValue *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on HttpKeyValue");
		dave_memset(unzip_data, 0x00, sizeof(HttpKeyValue));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->key), 1, DAVE_HTTP_KEY_LEN, t_bson_inq_object(pStructBson, "s8-key"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->value), 1, DAVE_HTTP_VALUE_LEN, t_bson_inq_object(pStructBson, "s8-value"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_HttpKeyValue_d(HttpKeyValue *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_HttpKeyValue(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_HttpKeyValue_d(HttpKeyValue *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(HttpKeyValue));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_HttpKeyValue(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_BuildingBlocks(BuildingBlocks *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "ub-blocks_id", t_rpc_ver3_zip_ub(zip_data->blocks_id));
	t_bson_add_object(pStructBson, "s8-verno", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->verno), 1, DAVE_VERNO_STR_LEN));
	t_bson_add_object(pStructBson, "u8-ip_addr", t_rpc_ver3_zip_u8_d((u8 *)(zip_data->ip_addr), 16));
	t_bson_add_object(pStructBson, "u16-port", t_rpc_ver3_zip_u16(zip_data->port));
	t_bson_add_object(pStructBson, "dave_bool-ready_flag", t_rpc_ver3_zip_dave_bool(zip_data->ready_flag));
	t_bson_add_object(pStructBson, "dave_bool-blocks_flag", t_rpc_ver3_zip_dave_bool(zip_data->blocks_flag));
	t_bson_add_object(pStructBson, "dave_bool-client_flag", t_rpc_ver3_zip_dave_bool(zip_data->client_flag));
	t_bson_add_object(pStructBson, "ub-release_quantity", t_rpc_ver3_zip_ub(zip_data->release_quantity));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_BuildingBlocks(BuildingBlocks *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on BuildingBlocks");
		dave_memset(unzip_data, 0x00, sizeof(BuildingBlocks));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_ub(&(unzip_data->blocks_id), t_bson_inq_object(pStructBson, "ub-blocks_id"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->verno), 1, DAVE_VERNO_STR_LEN, t_bson_inq_object(pStructBson, "s8-verno"));
		t_rpc_ver3_unzip_u8_d((u8 *)(unzip_data->ip_addr), 16, t_bson_inq_object(pStructBson, "u8-ip_addr"));
		t_rpc_ver3_unzip_u16(&(unzip_data->port), t_bson_inq_object(pStructBson, "u16-port"));
		t_rpc_ver3_unzip_dave_bool(&(unzip_data->ready_flag), t_bson_inq_object(pStructBson, "dave_bool-ready_flag"));
		t_rpc_ver3_unzip_dave_bool(&(unzip_data->blocks_flag), t_bson_inq_object(pStructBson, "dave_bool-blocks_flag"));
		t_rpc_ver3_unzip_dave_bool(&(unzip_data->client_flag), t_bson_inq_object(pStructBson, "dave_bool-client_flag"));
		t_rpc_ver3_unzip_ub(&(unzip_data->release_quantity), t_bson_inq_object(pStructBson, "ub-release_quantity"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_BuildingBlocks_d(BuildingBlocks *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_BuildingBlocks(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_BuildingBlocks_d(BuildingBlocks *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(BuildingBlocks));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_BuildingBlocks(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_SocNetInfo(SocNetInfo *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "SOCDOMAIN-domain", t_rpc_ver3_zip_SOCDOMAIN(zip_data->domain));
	t_bson_add_object(pStructBson, "SOCTYPE-type", t_rpc_ver3_zip_SOCTYPE(zip_data->type));
	t_bson_add_object(pStructBson, "NetAddrType-addr_type", t_rpc_ver3_zip_NetAddrType(zip_data->addr_type));
	t_bson_add_object(pStructBson, "SocNetInfoAddr-addr", t_rpc_ver3_zip_SocNetInfoAddr(&(zip_data->addr)));
	t_bson_add_object(pStructBson, "u16-port", t_rpc_ver3_zip_u16(zip_data->port));
	t_bson_add_object(pStructBson, "FixedPortFlag-fixed_src_flag", t_rpc_ver3_zip_FixedPortFlag(zip_data->fixed_src_flag));
	t_bson_add_object(pStructBson, "SocNetInfoIp-src_ip", t_rpc_ver3_zip_SocNetInfoIp(&(zip_data->src_ip)));
	t_bson_add_object(pStructBson, "u16-src_port", t_rpc_ver3_zip_u16(zip_data->src_port));
	t_bson_add_object(pStructBson, "EnableKeepAliveFlag-enable_keepalive_flag", t_rpc_ver3_zip_EnableKeepAliveFlag(zip_data->enable_keepalive_flag));
	t_bson_add_object(pStructBson, "sb-keepalive_second", t_rpc_ver3_zip_sb(zip_data->keepalive_second));
	t_bson_add_object(pStructBson, "EnableNetCardBindFlag-netcard_bind_flag", t_rpc_ver3_zip_EnableNetCardBindFlag(zip_data->netcard_bind_flag));
	t_bson_add_object(pStructBson, "s8-netcard_name", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->netcard_name), 1, DAVE_NORMAL_NAME_LEN));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_SocNetInfo(SocNetInfo *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on SocNetInfo");
		dave_memset(unzip_data, 0x00, sizeof(SocNetInfo));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_SOCDOMAIN(&(unzip_data->domain), t_bson_inq_object(pStructBson, "SOCDOMAIN-domain"));
		t_rpc_ver3_unzip_SOCTYPE(&(unzip_data->type), t_bson_inq_object(pStructBson, "SOCTYPE-type"));
		t_rpc_ver3_unzip_NetAddrType(&(unzip_data->addr_type), t_bson_inq_object(pStructBson, "NetAddrType-addr_type"));
		t_rpc_ver3_unzip_SocNetInfoAddr(&(unzip_data->addr), t_bson_inq_object(pStructBson, "SocNetInfoAddr-addr"));
		t_rpc_ver3_unzip_u16(&(unzip_data->port), t_bson_inq_object(pStructBson, "u16-port"));
		t_rpc_ver3_unzip_FixedPortFlag(&(unzip_data->fixed_src_flag), t_bson_inq_object(pStructBson, "FixedPortFlag-fixed_src_flag"));
		t_rpc_ver3_unzip_SocNetInfoIp(&(unzip_data->src_ip), t_bson_inq_object(pStructBson, "SocNetInfoIp-src_ip"));
		t_rpc_ver3_unzip_u16(&(unzip_data->src_port), t_bson_inq_object(pStructBson, "u16-src_port"));
		t_rpc_ver3_unzip_EnableKeepAliveFlag(&(unzip_data->enable_keepalive_flag), t_bson_inq_object(pStructBson, "EnableKeepAliveFlag-enable_keepalive_flag"));
		t_rpc_ver3_unzip_sb(&(unzip_data->keepalive_second), t_bson_inq_object(pStructBson, "sb-keepalive_second"));
		t_rpc_ver3_unzip_EnableNetCardBindFlag(&(unzip_data->netcard_bind_flag), t_bson_inq_object(pStructBson, "EnableNetCardBindFlag-netcard_bind_flag"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->netcard_name), 1, DAVE_NORMAL_NAME_LEN, t_bson_inq_object(pStructBson, "s8-netcard_name"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_SocNetInfo_d(SocNetInfo *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_SocNetInfo(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_SocNetInfo_d(SocNetInfo *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(SocNetInfo));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_SocNetInfo(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

void *
t_rpc_ver3_zip_IPBaseInfo(IPBaseInfo *zip_data)
{
	void *pStructBson = t_bson_malloc_object();

	t_bson_add_object(pStructBson, "IPProtocol-protocol", t_rpc_ver3_zip_IPProtocol(zip_data->protocol));
	t_bson_add_object(pStructBson, "IPVER-ver", t_rpc_ver3_zip_IPVER(zip_data->ver));
	t_bson_add_object(pStructBson, "u8-src_ip", t_rpc_ver3_zip_u8_d((u8 *)(zip_data->src_ip), 16));
	t_bson_add_object(pStructBson, "u16-src_port", t_rpc_ver3_zip_u16(zip_data->src_port));
	t_bson_add_object(pStructBson, "u8-dst_ip", t_rpc_ver3_zip_u8_d((u8 *)(zip_data->dst_ip), 16));
	t_bson_add_object(pStructBson, "u16-dst_port", t_rpc_ver3_zip_u16(zip_data->dst_port));
	t_bson_add_object(pStructBson, "sb-keepalive_second", t_rpc_ver3_zip_sb(zip_data->keepalive_second));
	t_bson_add_object(pStructBson, "s8-netcard_name", t_rpc_ver3_zip_s8_d((s8 *)(zip_data->netcard_name), 1, DAVE_NORMAL_NAME_LEN));
	t_bson_add_object(pStructBson, "FixedPortFlag-fixed_port_flag", t_rpc_ver3_zip_FixedPortFlag(zip_data->fixed_port_flag));

	return pStructBson;
}

dave_bool
t_rpc_ver3_unzip_IPBaseInfo(IPBaseInfo *unzip_data, void *pStructBson)
{
	dave_bool ret;

	if(pStructBson == NULL)
	{
		TOOLSLTRACE(360,1,"the pBson is NULL on IPBaseInfo");
		dave_memset(unzip_data, 0x00, sizeof(IPBaseInfo));
		ret = dave_false;
	}
	else
	{
		t_rpc_ver3_unzip_IPProtocol(&(unzip_data->protocol), t_bson_inq_object(pStructBson, "IPProtocol-protocol"));
		t_rpc_ver3_unzip_IPVER(&(unzip_data->ver), t_bson_inq_object(pStructBson, "IPVER-ver"));
		t_rpc_ver3_unzip_u8_d((u8 *)(unzip_data->src_ip), 16, t_bson_inq_object(pStructBson, "u8-src_ip"));
		t_rpc_ver3_unzip_u16(&(unzip_data->src_port), t_bson_inq_object(pStructBson, "u16-src_port"));
		t_rpc_ver3_unzip_u8_d((u8 *)(unzip_data->dst_ip), 16, t_bson_inq_object(pStructBson, "u8-dst_ip"));
		t_rpc_ver3_unzip_u16(&(unzip_data->dst_port), t_bson_inq_object(pStructBson, "u16-dst_port"));
		t_rpc_ver3_unzip_sb(&(unzip_data->keepalive_second), t_bson_inq_object(pStructBson, "sb-keepalive_second"));
		t_rpc_ver3_unzip_s8_d((s8 *)(unzip_data->netcard_name), 1, DAVE_NORMAL_NAME_LEN, t_bson_inq_object(pStructBson, "s8-netcard_name"));
		t_rpc_ver3_unzip_FixedPortFlag(&(unzip_data->fixed_port_flag), t_bson_inq_object(pStructBson, "FixedPortFlag-fixed_port_flag"));
		ret = dave_true;
	}

	return ret;
}

void *
t_rpc_ver3_zip_IPBaseInfo_d(IPBaseInfo *zip_data, ub zip_len)
{
	void *pArrayBson = t_bson_malloc_array();
	ub zip_index;

	for(zip_index=0; zip_index<zip_len; zip_index++)
	{
		t_bson_array_add_object(pArrayBson, t_rpc_ver3_zip_IPBaseInfo(&(zip_data[zip_index])));
	}

	return pArrayBson;
}

dave_bool
t_rpc_ver3_unzip_IPBaseInfo_d(IPBaseInfo *unzip_data, ub unzip_len, void *pArrayBson)
{
	sb array_len, array_index;

	dave_memset(unzip_data, 0x00, unzip_len * sizeof(IPBaseInfo));

	if(pArrayBson == NULL)
	{
		return dave_false;
	}

	array_len = t_bson_array_number(pArrayBson);
	if(array_len > (sb)unzip_len)
	{
		array_len = (sb)unzip_len;
	}

	for(array_index=0; array_index<array_len; array_index++)
	{
		t_rpc_ver3_unzip_IPBaseInfo(&unzip_data[array_index], t_bson_array_inq_object(pArrayBson, array_index));
	}

	return dave_true;
}

