package base
/*
 * Copyright (c) 2022 Renwei
 *
 * This is a free software; you can redistribute it and/or modify
 * it under the terms of the MIT license. See LICENSE for details.
 *
 * ############################# IMPORTANT INFORMATION ############################
 * The code of this file is automatically generated by tools(Tools/rpc),
 * please do not modify it manually!
 * ############################# IMPORTANT INFORMATION ############################
 * ================================================================================
 */

const JSON_OBJECT_DEF_HASH_ENTRIES = 16
const JSON_C_TO_STRING_PLAIN = 0
const JSON_C_OPTION_GLOBAL = 0
const JSON_C_OPTION_THREAD = 1
const THREAD_MSG_WAKEUP = 0
const THREAD_TICK_WAKEUP = 0
const THREAD_THREAD_FLAG = 0
const THREAD_REMOTE_FLAG = 0
const THREAD_TRACE_FLAG = 0
const THREAD_PRIVATE_FLAG = 0
const JSON_C_MAJOR_VERSION = 0
const JSON_C_MINOR_VERSION = 15
const JSON_C_MICRO_VERSION = 0
const ARRAY_LIST_DEFAULT_SIZE = 32
const CORE_MEM_MAX = 204800
const FREE_MEM_MAX = 32
const SOCKET_TCP_RECV_MAX_BUF = 32768
const SOCKET_TCP_RECV_MIN_BUF = 8192
const SOCKET_TCP_RECV_ADD_GRADIENT = 2048
const SOCKET_TCP_RECV_DEC_GRADIENT = 16384
const SOCKET_UDP_RECV_MAX_BUF = 4096
const RX_TX_BUF_MIN = 2048
const STACK_HEAD_LENver2 = 10
const JSON_C_HAVE_INTTYPES_H = 1
const JSON_C_STR_HASH_DFLT = 0
const JSON_C_STR_HASH_PERLLIKE = 1
const MAX_VALUE_DEFINE = 0
const SYNC_STACK_HEAD_MAX_LEN = 2048
const THREAD_MAX = 256
const THREAD_THREAD_MAX = 1024
const THREAD_MSG_QUEUE_NUM = 128
const THREAD_SEQ_QUEUE_NUM = 512
const THREAD_WAKEUP_INTERVAL = 1
const DAVE_PATH_LEN = 256
const DAVE_HTTP_KEY_LEN = 128
const DAVE_HTTP_VALUE_LEN = 512
const DAVE_HTTP_HEAD_MAX = 16
const JSON_TOKENER_DEFAULT_DEPTH = 32
const JSON_TOKENER_STRICT = 0
const JSON_TOKENER_ALLOW_TRAILING_CHARS = 0
const JSON_TOKENER_VALIDATE_UTF8 = 0
const JSON_FILE_BUF_SIZE = 4096
const DAVE_THREAD_NAME_LEN = 32
const DAVE_GLOBALLY_IDENTIFIER_LEN = 33
const DAVE_VERNO_STR_LEN = 64
const DAVE_NORMAL_NAME_LEN = 128
const DAVE_URL_LEN = 128
const DAVE_MAC_ADDR_LEN = 6
const DAVE_IP_V4_ADDR_LEN = 4
const DAVE_IP_V6_ADDR_LEN = 16
const DAVE_SERVER_SUPPORT_SOCKET_MAX = 10240
const DAVE_BUILDING_BLOCKS_MAX = 255
const KV_NAME_MAX = 64
const KV_KEY_MAX = 512
const KV_SLOT_NUM = 16
const KV_SLOT_DEPTH = 6
const KV_DATA_DEPTH_MAX = 2048
