#!/bin/bash

PROJECT=${PWD##*/}
HOMEPATH=$(cd `dirname $0`; pwd)
FINDDEPLOY=0

if [ -f ../../../../Deploy/deploy/${PROJECT}/deploy.sh ]; then
   cd ../../../../Deploy/deploy/${PROJECT}/
   FINDDEPLOY=1
elif [ -f ../../../Deploy/deploy/${PROJECT}/deploy.sh ]; then
   cd ../../../Deploy/deploy/${PROJECT}/
   FINDDEPLOY=1
elif [ -f ../../Deploy/deploy/${PROJECT}/deploy.sh ]; then
   cd ../../Deploy/deploy/${PROJECT}/
   FINDDEPLOY=1
fi

if [ ${FINDDEPLOY} == 1 ]; then
   echo deploy ${PROJECT}
   chmod a+x *.sh
   ./deploy.sh ${HOMEPATH}
fi