#!/bin/bash
#/*
# * Copyright (c) 2022 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# */

PROJECT=${PWD##*/}
HOMEPATH=$(cd `dirname $0`; pwd)
FINDDEPLOY=0
DEPLOYPATH=../../../../Deploy/deploy/${PROJECT}

cd ${DEPLOYPATH}

echo deploy ${PROJECT}
chmod a+x *.sh
./deploy.sh ${HOMEPATH}
