#!/bin/bash
#/*
# * Copyright (c) 2023 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# */

HOMEPATH=`pwd`

ACCOUNT=cosmos
CHAINID=${ACCOUNT}
KEYRINGBACKEND=test

DATADIR=${HOMEPATH}/gaiad-data-${CHAINID}
GAIADBIN=${HOMEPATH}/gaiad

echo ACCOUNT:${ACCOUNT}
echo CHAINID:${CHAINID}
echo KEYRINGBACKEND:${KEYRINGBACKEND}
echo DATADIR:${DATADIR}
echo GAIADBIN:${GAIADBIN}

chmod a+x ${GAIADBIN}

if [ ! -d ${DATADIR} ]; then
   echo ====== init ${DATADIR} ======
   ${GAIADBIN} init ${CHAINID} --chain-id ${CHAINID} --home ${DATADIR}
   ${GAIADBIN} config chain-id ${CHAINID} --home ${DATADIR}
   ${GAIADBIN} config keyring-backend ${KEYRINGBACKEND} --home ${DATADIR}
   ${GAIADBIN} keys add ${ACCOUNT} --home ${DATADIR}
   ${GAIADBIN} add-genesis-account ${ACCOUNT} 10000000000000000000000000stake --home ${DATADIR} --keyring-backend ${KEYRINGBACKEND}
   ${GAIADBIN} gentx ${ACCOUNT} 1000000000stake --home ${DATADIR} --chain-id ${CHAINID}
   ${GAIADBIN} collect-gentxs --home ${DATADIR}
   sed -i.bak'' 's/minimum-gas-prices = ""/minimum-gas-prices = "0uatom"/' ${DATADIR}/config/app.toml
fi

${GAIADBIN} start --home ${DATADIR} --x-crisis-skip-assert-invariants
