#!/bin/bash
#/*
# * Copyright (c) 2023 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# */

File=$(basename $0)

if [ ! -d ./gm ]; then
   git clone https://github.com/informalsystems/gm.git
fi