#!/bin/bash
#/*
# * Copyright (c) 2023 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# */

PROJECTDIR=$1
PRIJECTBIN=sconfig
File=$(basename $0)

VERSION=0.2.0

if [ ! -d ./sconfig ]; then
   git clone -bv${VERSION} --depth=1 https://github.com/freshautomations/sconfig.git
fi

cd sconfig && go mod tidy && go build -o ${PRIJECTBIN} main.go

echo ${File} copy ${PRIJECTBIN} to ${PROJECTDIR}
chmod a+x ${PRIJECTBIN}
cp ${PRIJECTBIN} ${PROJECTDIR}