#!/bin/bash
#/*
# * Copyright (c) 2024 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# */

modules_name=$1
if [ -z $modules_name ]; then
    modules_name="Lock"
fi

cd ./hardhat

chmod a+x ./DEPLOY.sh
./DEPLOY.sh $modules_name