package base
/*
 * Copyright (c) 2022 Renwei
 *
 * This is a free software; you can redistribute it and/or modify
 * it under the terms of the MIT license. See LICENSE for details.
 *
 * ############################# IMPORTANT INFORMATION ############################
 * The code of this file is automatically generated by tools(Tools/rpc),
 * please do not modify it manually!
 * ############################# IMPORTANT INFORMATION ############################
 * ================================================================================
 */


import "unsafe"

type SocketBindReq struct {
	Netinfo SocNetInfo
	Ptr unsafe.Pointer
}

type SocketBindRsp struct {
	Socket int32
	Netinfo SocNetInfo
	Bindinfo int32
	Thread_Id uint64
	Ptr unsafe.Pointer
}

type SocketConnectReq struct {
	Netinfo SocNetInfo
	Ptr unsafe.Pointer
}

type SocketConnectRsp struct {
	Socket int32
	Netinfo SocNetInfo
	Connectinfo int32
	Thread_Id uint64
	Ptr unsafe.Pointer
}

type SocketDisconnectReq struct {
	Socket int32
	Ptr unsafe.Pointer
}

type SocketDisconnectRsp struct {
	Socket int32
	Result int32
	Ptr unsafe.Pointer
}

type SocketPlugIn struct {
	Father_Socket int32
	Child_Socket int32
	Netinfo SocNetInfo
	Thread_Id uint64
	Ptr unsafe.Pointer
}

type SocketPlugOut struct {
	Socket int32
	Reason int32
	Netinfo SocNetInfo
	Thread_Id uint64
	Ptr unsafe.Pointer
}

type SocketRead struct {
	Socket int32
	Ipinfo IPBaseInfo
	Data_Len uint64
	Data *MBUF
	Ptr unsafe.Pointer
}

type SocketWrite struct {
	Socket int32
	Ipinfo IPBaseInfo
	Data_Len uint64
	Data *MBUF
	Close_Flag int32
}

type SocketNotify struct {
	Socket int32
	Notify int32
	Data uint64
	Ptr unsafe.Pointer
}

type SocketRawEvent struct {
	Socket int32
	Os_Socket int32
	Event int32
	Netinfo SocNetInfo
	Data *MBUF
	Ptr unsafe.Pointer
}

type TESTMSG struct {
	Test_Msg [4096] byte
}

type TIMERMSG struct {
	Timer_Id int64
}

type WAKEUPMSG struct {
	Null_Msg unsafe.Pointer
	Some_Msg uint32
}

type RUNFUNCTIONMSG struct {
	Thread_Fun unsafe.Pointer
	Last_Fun unsafe.Pointer
	Thread_Dst uint64
	Initialization_Flag int8
}

type DebugReq struct {
	Msg [4096] byte
	Ptr unsafe.Pointer
}

type DebugRsp struct {
	Msg [16384] byte
	Ptr unsafe.Pointer
}

type RESTARTREQMSG struct {
	Reason [128] byte
	Times uint64
}

type RESTARTRSPMSG struct {
	Wait_Flag int8
}

type POWEROFFMSG struct {
	Reason [128] byte
}

type ThreadRemoteReadyMsg struct {
	Remote_Thread_Id uint64
	Remote_Thread_Name [128] byte
}

type ThreadRemoteRemoveMsg struct {
	Remote_Thread_Id uint64
	Remote_Thread_Name [128] byte
}

type TraceSwitchMsg struct {
	Thread_Id uint64
	Trace_On int8
}

type RemoteMsgTimerOutMsg struct {
	Msg_Id uint64
	Msg_Len uint64
	Msg_Body unsafe.Pointer
}

type TemporarilyDefineMessageMsg struct {
	Parameter unsafe.Pointer
}

type SystemMount struct {
	Socket int32
	Verno [DAVE_VERNO_STR_LEN] byte
	Netinfo SocNetInfo
}

type SystemDecoupling struct {
	Socket int32
	Verno [DAVE_VERNO_STR_LEN] byte
	Netinfo SocNetInfo
}

type MemoryWarning struct {
	Used_Percentage uint64
}

type MsgIdEcho struct {
	Echo_Counter uint64
	Echo_Time uint64
	Echo_Multiple int8
	Concurrency_Flag int8
	Msg [256] byte
}

type InternalEvents struct {
	Event_Id uint64
	Ptr unsafe.Pointer
}

type ThreadBusy struct {
	Thread_Id uint64
	Thread_Name [DAVE_THREAD_NAME_LEN] byte
	Msg_Id uint64
	Msg_Number uint64
}

type ThreadIdle struct {
	Thread_Id uint64
	Thread_Name [DAVE_THREAD_NAME_LEN] byte
}

type ClientBusy struct {
	Verno [DAVE_VERNO_STR_LEN] byte
	Ptr unsafe.Pointer
}

type ClientIdle struct {
	Verno [DAVE_VERNO_STR_LEN] byte
	Ptr unsafe.Pointer
}

type ThreadRemoteIDReadyMsg struct {
	Remote_Thread_Id uint64
	Remote_Thread_Name [128] byte
	Globally_Identifier [DAVE_GLOBALLY_IDENTIFIER_LEN] byte
}

type ThreadRemoteIDRemoveMsg struct {
	Remote_Thread_Id uint64
	Remote_Thread_Name [128] byte
	Globally_Identifier [DAVE_GLOBALLY_IDENTIFIER_LEN] byte
}

type ThreadLocalReadyMsg struct {
	Local_Thread_Id uint64
	Local_Thread_Name [128] byte
}

type ThreadLocalRemoveMsg struct {
	Local_Thread_Id uint64
	Local_Thread_Name [128] byte
}

type RPCDebugMsg struct {
	Ret_Debug int64
	S8_Debug byte
	U8_Debug byte
	U16_Debug uint16
	S32_Debug int32
	U32_Debug uint32
	Void_Debug unsafe.Pointer
	Date_Debug DateStruct
	Mbuf_Debug *MBUF
}

type CFGUpdate struct {
	Cfg_Name [DAVE_NORMAL_NAME_LEN] byte
	Cfg_Length uint64
	Cfg_Value [8196] byte
}

type MsgBlocksReq struct {
	Opt int32
	Blocks_Id_1 uint64
	Blocks_Id_2 uint64
	Ptr unsafe.Pointer
}

type MsgBlocksRsp struct {
	Ret int64
	Opt int32
	Blocks [DAVE_BUILDING_BLOCKS_MAX] BuildingBlocks
	Ptr unsafe.Pointer
}

type MsgOSNotify struct {
	Notify_Info uint64
}

