#!/bin/bash

VERSION=2.0

echo ****************************

if [ ! -f v${VERSION}.tar.gz ]; then
   wget https://github.com/linux-test-project/lcov/archive/refs/tags/v${VERSION}.tar.gz
fi
if [ ! -d ./lcov-${VERSION} ]; then
   tar -zxvf v${VERSION}.tar.gz
fi

cd lcov-${VERSION}
make install

apt update
apt install -y perl-CPAN
perl -MCPAN -e 'install JSON::XS'
perl -MCPAN -e 'install Cpanel::JSON::XS'
cpan DateTime Capture::Tiny

cd ../
rm -rf lcov-${VERSION}
