#!/bin/bash
#/*
# * Copyright (c) 2023 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# */

CHAINID=cosmos
HOMEDIR=/project/.gaiad-${CHAINID}
GAIADBIN=/project/gaiad
KEYRINGBACKEND=test

chmod a+x ${GAIADBIN}

if [ ! -f ${HOMEDIR} ]; then
   ${GAIADBIN} init ${CHAINID} --chain-id ${CHAINID} --home ${HOMEDIR}
   ${GAIADBIN} config chain-id ${CHAINID} --home ${HOMEDIR}
   ${GAIADBIN} config keyring-backend ${KEYRINGBACKEND} --home ${HOMEDIR}
   ${GAIADBIN} keys add val --home ${HOMEDIR}
   ${GAIADBIN} add-genesis-account val 10000000000000000000000000stake --home ${HOMEDIR} --keyring-backend ${KEYRINGBACKEND}
   ${GAIADBIN} gentx val 1000000000stake --home ${HOMEDIR} --chain-id ${CHAINID}
   ${GAIADBIN} collect-gentxs --home ${HOMEDIR}
   sed -i.bak'' 's/minimum-gas-prices = ""/minimum-gas-prices = "0uatom"/' ${HOMEDIR}/config/app.toml
fi

${GAIADBIN} start --home ${HOMEDIR} --x-crisis-skip-assert-invariants
