#!/bin/bash
#/*
# * Copyright (c) 2022 Renwei
# *
# * This is a free software; you can redistribute it and/or modify
# * it under the terms of the MIT license. See LICENSE for details.
# */

#
# https://docs.prylabs.network/docs/install/install-with-script
#

NETWORKID=1
DATADIR=ethereum
IDENTITY=${HOSTNAME}-${USER}

./geth --datadir ${DATADIR} --networkid ${NETWORKID} --identity ${IDENTITY} --syncmode snap --gcmode archive --http --http.api eth,net,engine,admin --authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost --authrpc.jwtsecret /project/prysm/jwt.hex
